var WORDS_CYBERPUNK = [
  { en: "abandoned", pl: "opuszczony" },
  { en: "access token", pl: "token dostępu" },
  { en: "adam smasher", pl: "adam smasher" },
  { en: "adrenaline converter", pl: "konwerter adrenaliny" },
  { en: "aerial", pl: "powietrzny" },
  { en: "aerodyne", pl: "aerodyna" },
  { en: "agent", pl: "agent" },
  { en: "aldecaldos", pl: "aldecaldos" },
  { en: "alt", pl: "alt" },
  { en: "alt cunningham", pl: "alt cunningham" },
  { en: "anarchy", pl: "anarchia" },
  { en: "android", pl: "android" },
  { en: "animals", pl: "zwierzęta" },
  { en: "apparition", pl: "zjawa" },
  { en: "arasaka", pl: "arasaka" },
  { en: "arasaka tower", pl: "wieża arasaka" },
  { en: "arcology", pl: "arkologia" },
  { en: "arm", pl: "ramię" },
  { en: "arroyo", pl: "arroyo" },
  { en: "assassin", pl: "skrytobójca" },
  { en: "assault rifle", pl: "karabin szturmowy" },
  { en: "attribute", pl: "atrybut" },
  { en: "augmentation", pl: "augmentacja" },
  { en: "augmented reality", pl: "rzeczywistość rozszerzona" },
  { en: "autofixer", pl: "autozałatwiacz" },
  { en: "autonomous", pl: "autonomiczny" },
  { en: "av", pl: "av" },
  { en: "backpack", pl: "plecak" },
  { en: "badlands", pl: "nieużytki" },
  { en: "bait", pl: "przynęta" },
  { en: "bakaneko", pl: "bakaneko" },
  { en: "baker clan", pl: "klan bakera" },
  { en: "ballistic", pl: "balistyczny" },
  { en: "ballistic coprocessor", pl: "koprocesor balistyczny" },
  { en: "barghest", pl: "barghest" },
  { en: "battery", pl: "bateria" },
  { en: "beaverville", pl: "bobrowo" },
  { en: "berserk", pl: "berserk" },
  { en: "bioagent", pl: "bioagent" },
  { en: "biochip", pl: "biochip" },
  { en: "bioengineering", pl: "bioinżynieria" },
  { en: "biomonitor", pl: "biomonitor" },
  { en: "bioplague", pl: "bioplaga" },
  { en: "bioroid", pl: "bioroid" },
  { en: "biotechnica", pl: "biotechnica" },
  { en: "biotechnica flats", pl: "biotechnica flats" },
  { en: "black ice", pl: "czarny lód" },
  { en: "blackwall", pl: "czarna ściana" },
  { en: "blackwall protocol", pl: "protokół czarnej ściany" },
  { en: "blood pump", pl: "pompa krwi" },
  { en: "bodyguard", pl: "ochroniarz" },
  { en: "bodysculpt", pl: "rzeźbienie ciała" },
  { en: "boostergang", pl: "gang wspomagaczy" },
  { en: "bounce back", pl: "bounce back" },
  { en: "bounty hunter", pl: "łowca nagród" },
  { en: "brain-computer", pl: "mózg-komputer" },
  { en: "braindance", pl: "braindance" },
  { en: "breach", pl: "włamanie" },
  { en: "breach protocol", pl: "protokół włamania" },
  { en: "brick", pl: "brick" },
  { en: "brigitte", pl: "brigitte" },
  { en: "buffer", pl: "bufor" },
  { en: "camouflage", pl: "kamuflaż" },
  { en: "charter hill", pl: "charter hill" },
  { en: "chemical", pl: "chemiczny" },
  { en: "choom", pl: "kumpel" },
  { en: "chrome", pl: "chrom" },
  { en: "chromer", pl: "chromer" },
  { en: "circulatory", pl: "krwionośny" },
  { en: "city center", pl: "centrum miasta" },
  { en: "city database", pl: "baza danych miasta" },
  { en: "claire russell", pl: "claire russell" },
  { en: "claws", pl: "pazury" },
  { en: "clone", pl: "klon" },
  { en: "combat zone", pl: "strefa walk" },
  { en: "combine", pl: "kombajn" },
  { en: "commodification", pl: "utowarowienie" },
  { en: "component", pl: "komponent" },
  { en: "comrades hammer", pl: "młot towarzysza" },
  { en: "consciousness", pl: "świadomość" },
  { en: "construct", pl: "konstrukt" },
  { en: "contagion", pl: "zaraza" },
  { en: "contamination", pl: "skażenie" },
  { en: "corpo", pl: "korp" },
  { en: "corpo plaza", pl: "corpo plaza" },
  { en: "corporate", pl: "korporacyjny" },
  { en: "corporation", pl: "korporacja" },
  { en: "cranial", pl: "czaszkowy" },
  { en: "cripple movement", pl: "spowolnienie ruchu" },
  { en: "crowbar", pl: "łom" },
  { en: "cyberdeck", pl: "cyberdeck" },
  { en: "cyberization", pl: "cyberryzacja" },
  { en: "cyberlimb", pl: "cyberkończyna" },
  { en: "cyberpsycho", pl: "cyberpsychopata" },
  { en: "cyberpsychosis", pl: "cyberpsychoza" },
  { en: "cybersnake", pl: "cybersnake" },
  { en: "cyberspace", pl: "cyberprzestrzeń" },
  { en: "cyberware", pl: "cyberware" },
  { en: "cyberware malfunction", pl: "awaria cyberware" },
  { en: "daemon", pl: "demon" },
  { en: "danger gal", pl: "danger gal" },
  { en: "dark matter", pl: "ciemna materia" },
  { en: "databank", pl: "bank danych" },
  { en: "datamine", pl: "kopalnia danych" },
  { en: "datapool", pl: "zasób danych" },
  { en: "dataterm", pl: "dataterm" },
  { en: "deadeye", pl: "martwe oko" },
  { en: "debt chip", pl: "debt chip" },
  { en: "deckhead", pl: "mózgowiec" },
  { en: "decryption", pl: "deszyfrowanie" },
  { en: "dehumanize", pl: "odczłowieczyć" },
  { en: "delamain", pl: "delamain" },
  { en: "delta", pl: "spadać" },
  { en: "depersonalize", pl: "depersonalizować" },
  { en: "derelict", pl: "opuszczony" },
  { en: "detonate grenade", pl: "detonacja granatu" },
  { en: "dex deshawn", pl: "dex deshawn" },
  { en: "digitize", pl: "digitalizować" },
  { en: "dilapidated", pl: "zniszczony" },
  { en: "dino", pl: "dino" },
  { en: "dogtown", pl: "dogtown" },
  { en: "doll", pl: "lalka" },
  { en: "drug dealer", pl: "handlarz narkotykami" },
  { en: "dum dum", pl: "dum dum" },
  { en: "dystopia", pl: "dystopia" },
  { en: "dystopian", pl: "dystopijny" },
  { en: "eddies", pl: "eurodolary" },
  { en: "edgerunner", pl: "edgerunner" },
  { en: "el capitan", pl: "el capitan" },
  { en: "electric", pl: "elektryczny" },
  { en: "emotion", pl: "emocja" },
  { en: "empathetic", pl: "empatyczny" },
  { en: "empathy", pl: "empatia" },
  { en: "encryption", pl: "szyfrowanie" },
  { en: "engram", pl: "engram" },
  { en: "entropism", pl: "entropizm" },
  { en: "erebus", pl: "erebus" },
  { en: "eurodollar", pl: "eurodolar" },
  { en: "evelyn parker", pl: "evelyn parker" },
  { en: "executive", pl: "dyrektor" },
  { en: "exoskeleton", pl: "egzoszkielet" },
  { en: "experience", pl: "doświadczenie" },
  { en: "exploitation", pl: "eksploatacja" },
  { en: "face", pl: "twarz" },
  { en: "faceplate", pl: "płyta twarzowa" },
  { en: "fallout", pl: "opad radioaktywny" },
  { en: "fast travel", pl: "szybka podróż" },
  { en: "fenrir", pl: "fenrir" },
  { en: "fingers", pl: "fingers" },
  { en: "firewall", pl: "zapora" },
  { en: "fixer", pl: "załatwiacz" },
  { en: "flatline", pl: "zgon" },
  { en: "free state", pl: "wolny stan" },
  { en: "freeway", pl: "autostrada" },
  { en: "frontal cortex", pl: "kora czołowa" },
  { en: "full-conversion", pl: "pełna konwersja" },
  { en: "fuzion", pl: "fuzion" },
  { en: "gig", pl: "fucha" },
  { en: "glen", pl: "glen" },
  { en: "glitter", pl: "glitter" },
  { en: "gonk", pl: "idiota" },
  { en: "gorilla arms", pl: "goryle ramiona" },
  { en: "goro takemura", pl: "goro takemura" },
  { en: "hammer", pl: "młot" },
  { en: "hanako arasaka", pl: "hanako arasaka" },
  { en: "hand", pl: "dłoń" },
  { en: "health booster", pl: "wzmacniacz zdrowia" },
  { en: "heywood", pl: "heywood" },
  { en: "high-tech", pl: "zaawansowana technologia" },
  { en: "hinterland", pl: "głębia lądu" },
  { en: "hologram", pl: "hologram" },
  { en: "hovercraft", pl: "poduszkowiec" },
  { en: "hovertank", pl: "czołg powietrzny" },
  { en: "humanity cost", pl: "koszt człowieczeństwa" },
  { en: "ice", pl: "ICE" },
  { en: "immune system", pl: "układ odpornościowy" },
  { en: "implant", pl: "implant" },
  { en: "incendiary", pl: "zapalający" },
  { en: "industrial", pl: "przemysłowy" },
  { en: "informant", pl: "informator" },
  { en: "input", pl: "partnerka" },
  { en: "integumentary", pl: "powłokowy" },
  { en: "interface plugs", pl: "wtyczki interfejsu" },
  { en: "interlock", pl: "interlock" },
  { en: "inventory", pl: "ekwipunek" },
  { en: "iron", pl: "broń" },
  { en: "irradiated", pl: "napromieniowany" },
  { en: "jack in", pl: "podłączyć się" },
  { en: "jack out", pl: "odłączyć się" },
  { en: "jackie welles", pl: "jackie welles" },
  { en: "japantown", pl: "japantown" },
  { en: "johnny silverhand", pl: "johnny silverhand" },
  { en: "joytoy", pl: "zabawka erotyczna" },
  { en: "judy alvarez", pl: "judy alvarez" },
  { en: "junk", pl: "złom" },
  { en: "kabuki", pl: "kabuki" },
  { en: "kang tao", pl: "kang tao" },
  { en: "katana", pl: "katana" },
  { en: "kendachi", pl: "kendachi" },
  { en: "kerenzikov", pl: "kerenzikov" },
  { en: "kerenzikov boost", pl: "kerenzikov boost" },
  { en: "kerry eurodyne", pl: "kerry eurodyne" },
  { en: "keycard", pl: "karta dostępu" },
  { en: "kiroshi", pl: "kiroshi" },
  { en: "kitsch", pl: "kicz" },
  { en: "knife", pl: "nóż" },
  { en: "konpeki plaza", pl: "konpeki plaza" },
  { en: "kriegmesser", pl: "kriegmesser" },
  { en: "kurt hansen", pl: "kurt hansen" },
  { en: "laguna bend", pl: "laguna bend" },
  { en: "lawman", pl: "stróż prawa" },
  { en: "leg", pl: "noga" },
  { en: "leveling", pl: "poziomowanie" },
  { en: "lifepath", pl: "ścieżka życia" },
  { en: "light machine gun", pl: "lekki karabin maszynowy" },
  { en: "limbic system", pl: "układ limbiczny" },
  { en: "linear frame", pl: "rama liniowa" },
  { en: "lizzie", pl: "lizzie" },
  { en: "lizzies", pl: "lizzies" },
  { en: "lizzy wizzy", pl: "lizzy wizzy" },
  { en: "loot", pl: "łup" },
  { en: "looting", pl: "grabienie" },
  { en: "low-life", pl: "nędzne życie" },
  { en: "maelstrom", pl: "maelstrom" },
  { en: "main job", pl: "zadanie główne" },
  { en: "malorian arms", pl: "malorian arms" },
  { en: "mantis blades", pl: "ostrza modliszki" },
  { en: "matrix", pl: "matryca" },
  { en: "maxdoc", pl: "maxdoc" },
  { en: "maxtac", pl: "maxtac" },
  { en: "mechatronic core", pl: "rdzeń mechatroniczny" },
  { en: "media", pl: "dziennikarz" },
  { en: "medtech", pl: "medtech" },
  { en: "megabuilding", pl: "megabudowla" },
  { en: "megacity", pl: "megamiasto" },
  { en: "megacorporation", pl: "megakorporacja" },
  { en: "megalopolis", pl: "megalopolis" },
  { en: "megastructure", pl: "megastruktura" },
  { en: "melee", pl: "walka wręcz" },
  { en: "memory wipe", pl: "wyczyszczenie pamięci" },
  { en: "mercenary", pl: "najemnik" },
  { en: "metalhead", pl: "metalhead" },
  { en: "microgenerator", pl: "mikrogenerator" },
  { en: "mikoshi", pl: "mikoshi" },
  { en: "militarism", pl: "militaryzm" },
  { en: "militech", pl: "militech" },
  { en: "militech canto", pl: "militech canto" },
  { en: "mitch anderson", pl: "mitch anderson" },
  { en: "monowire", pl: "monodrut" },
  { en: "mox", pl: "mox" },
  { en: "mr hands", pl: "mr hands" },
  { en: "multilevel", pl: "wielopoziomowy" },
  { en: "mutagen", pl: "mutagen" },
  { en: "mutation", pl: "mutacja" },
  { en: "nanorobotics", pl: "nanorobotyka" },
  { en: "nanotech", pl: "nanotechnologia" },
  { en: "narrator", pl: "narrator" },
  { en: "ncart", pl: "ncart" },
  { en: "ncpd", pl: "ncpd" },
  { en: "ncpd scanner", pl: "skaner ncpd" },
  { en: "neokitsch", pl: "neokitsch" },
  { en: "neon", pl: "neon" },
  { en: "neonlights", pl: "neonowe światła" },
  { en: "nervous system", pl: "układ nerwowy" },
  { en: "net architecture", pl: "architektura sieci" },
  { en: "netrunner", pl: "sieciobiegacz" },
  { en: "netwatch", pl: "netwatch" },
  { en: "network news", pl: "network news" },
  { en: "neural", pl: "neuronowy" },
  { en: "neural interface", pl: "interfejs neuronowy" },
  { en: "neural link", pl: "łącze neuronowe" },
  { en: "neuron", pl: "neuron" },
  { en: "new united states", pl: "nowe stany zjednoczone" },
  { en: "night city", pl: "night city" },
  { en: "night city airport", pl: "lotnisko night city" },
  { en: "night corp", pl: "night corp" },
  { en: "nightwatch", pl: "nightwatch" },
  { en: "no-tell motel", pl: "motel no-tell" },
  { en: "nomad", pl: "nomada" },
  { en: "north oak", pl: "north oak" },
  { en: "nova", pl: "zajebisty" },
  { en: "nusa", pl: "nusa" },
  { en: "ocular", pl: "oczny" },
  { en: "oil fields", pl: "pola naftowe" },
  { en: "operating system", pl: "system operacyjny" },
  { en: "optics", pl: "optyka" },
  { en: "orbital air", pl: "orbital air" },
  { en: "orbital station", pl: "stacja orbitalna" },
  { en: "outbreak", pl: "wybuch epidemii" },
  { en: "outlaw", pl: "banita" },
  { en: "output", pl: "partner" },
  { en: "overheat", pl: "przegrzanie" },
  { en: "overpass", pl: "wiadukt" },
  { en: "override", pl: "nadpisanie" },
  { en: "overwatch", pl: "overwatch" },
  { en: "overwrite", pl: "nadpisać" },
  { en: "ozob bozo", pl: "ozob bozo" },
  { en: "pacifica", pl: "pacifica" },
  { en: "pain editor", pl: "edytor bólu" },
  { en: "panam palmer", pl: "panam palmer" },
  { en: "panopticon", pl: "panoptikon" },
  { en: "perk", pl: "perk" },
  { en: "personality", pl: "osobowość" },
  { en: "petrochem", pl: "petrochem" },
  { en: "phantom", pl: "fantom" },
  { en: "phantom liberty", pl: "phantom liberty" },
  { en: "pharmaceutical", pl: "farmaceutyczny" },
  { en: "ping", pl: "ping" },
  { en: "pistol", pl: "pistolet" },
  { en: "placide", pl: "placide" },
  { en: "plasmid", pl: "plazmid" },
  { en: "posergang", pl: "gang pozerów" },
  { en: "posthuman", pl: "postczłowiek" },
  { en: "power", pl: "kinetyczny" },
  { en: "power armor", pl: "pancerz wspomagany" },
  { en: "precision rifle", pl: "karabin precyzyjny" },
  { en: "preem", pl: "zacny" },
  { en: "president", pl: "prezydent" },
  { en: "problem solver", pl: "rozwiązywacz problemów" },
  { en: "projectile", pl: "pocisk" },
  { en: "projectile launch", pl: "wyrzutnia pocisków" },
  { en: "prosthetic", pl: "protetyczny" },
  { en: "proxy", pl: "pełnomocnik" },
  { en: "quarantine", pl: "kwarantanna" },
  { en: "quest", pl: "zadanie" },
  { en: "quickhack", pl: "quickhack" },
  { en: "radiation", pl: "promieniowanie" },
  { en: "raffen shiv", pl: "raffen shiv" },
  { en: "ram", pl: "ram" },
  { en: "ram jolt", pl: "ram jolt" },
  { en: "rancho coronado", pl: "rancho coronado" },
  { en: "ranged", pl: "dystansowy" },
  { en: "razorboi", pl: "laserowy chłopak" },
  { en: "razorgirl", pl: "laserowa dziewczyna" },
  { en: "reboot optics", pl: "restart optyki" },
  { en: "reconstruction", pl: "rekonstrukcja" },
  { en: "regina jones", pl: "regina jones" },
  { en: "relic", pl: "relikt" },
  { en: "request backup", pl: "wezwanie wsparcia" },
  { en: "retcon", pl: "retcon" },
  { en: "revolver", pl: "rewolwer" },
  { en: "rhino", pl: "rhino" },
  { en: "ricochet", pl: "rykoszet" },
  { en: "rioter", pl: "uczestnik zamieszek" },
  { en: "ripperdoc", pl: "ripperdoc" },
  { en: "river ward", pl: "river ward" },
  { en: "rockerboy", pl: "rockerboy" },
  { en: "rockstar", pl: "gwiazda rocka" },
  { en: "rogue ai", pl: "zbuntowane ai" },
  { en: "rogue amendiares", pl: "rogue amendiares" },
  { en: "rosalind myers", pl: "rosalind myers" },
  { en: "royce", pl: "royce" },
  { en: "rush revolution", pl: "rush revolution" },
  { en: "saburo arasaka", pl: "saburo arasaka" },
  { en: "sandevistan", pl: "sandevistan" },
  { en: "santo domingo", pl: "santo domingo" },
  { en: "sapience", pl: "rozumność" },
  { en: "sasquatch", pl: "sasquatch" },
  { en: "satori", pl: "satori" },
  { en: "scavenge", pl: "szperanie" },
  { en: "scavengers", pl: "padlinożercy" },
  { en: "scavs", pl: "scavs" },
  { en: "scop", pl: "szajs" },
  { en: "scratchers", pl: "drapacze" },
  { en: "second heart", pl: "drugie serce" },
  { en: "securicine", pl: "securicine" },
  { en: "seismic", pl: "sejsmiczny" },
  { en: "sentience", pl: "samoświadomość" },
  { en: "shard", pl: "shard" },
  { en: "shock absorber", pl: "absorbator wstrząsów" },
  { en: "short circuit", pl: "zwarcie" },
  { en: "shotgun", pl: "strzelba" },
  { en: "side job", pl: "zadanie poboczne" },
  { en: "sighting", pl: "zgłoszenie" },
  { en: "simulation", pl: "symulacja" },
  { en: "sixth street", pl: "szósta ulica" },
  { en: "skeleton", pl: "szkielet" },
  { en: "skill", pl: "umiejętność" },
  { en: "skippy", pl: "skippy" },
  { en: "skyline", pl: "linia horyzontu" },
  { en: "slice-dice", pl: "krój kraj" },
  { en: "smart", pl: "inteligentny" },
  { en: "smart link", pl: "smart link" },
  { en: "smash", pl: "smash" },
  { en: "sniper rifle", pl: "karabin snajperski" },
  { en: "solo", pl: "solo" },
  { en: "solomon reed", pl: "solomon reed" },
  { en: "songbird", pl: "songbird" },
  { en: "sonic shock", pl: "szok dźwiękowy" },
  { en: "soulkiller", pl: "soulkiller" },
  { en: "space force", pl: "siły kosmiczne" },
  { en: "sprawl", pl: "rozlewisko miejskie" },
  { en: "stamina booster", pl: "wzmacniacz kondycji" },
  { en: "straightedge", pl: "prostolinijny" },
  { en: "street cred", pl: "kredyt uliczny" },
  { en: "subdermal armor", pl: "pancerz podskórny" },
  { en: "submachine gun", pl: "pistolet maszynowy" },
  { en: "suicide", pl: "samobójstwo" },
  { en: "sunset motel", pl: "motel sunset" },
  { en: "surgical", pl: "chirurgiczny" },
  { en: "surveillance", pl: "nadzór" },
  { en: "synapse burnout", pl: "wypalenie synaps" },
  { en: "synaptic accelerator", pl: "akcelerator synaptyczny" },
  { en: "synthblood", pl: "syntetyczna krew" },
  { en: "synthcoke", pl: "synthcoke" },
  { en: "synthetic", pl: "syntetyczny" },
  { en: "synthlungs", pl: "syntetyczne płuca" },
  { en: "system reset", pl: "reset systemu" },
  { en: "tech", pl: "techniczny" },
  { en: "techhair", pl: "techwłosy" },
  { en: "techie", pl: "technik" },
  { en: "technomancer", pl: "technomanta" },
  { en: "tectonic", pl: "tektoniczny" },
  { en: "terrorist", pl: "terrorysta" },
  { en: "the afterlife", pl: "afterlife" },
  { en: "the mox", pl: "the mox" },
  { en: "the stacks", pl: "stosy" },
  { en: "thermal", pl: "termiczny" },
  { en: "thermal katana", pl: "termiczna katana" },
  { en: "tino", pl: "tino" },
  { en: "totalitarian", pl: "totalitarny" },
  { en: "totentanz", pl: "totentanz" },
  { en: "toxic", pl: "toksyczny" },
  { en: "trace", pl: "namierzenie" },
  { en: "transhumanist", pl: "transhumanista" },
  { en: "trauma team", pl: "trauma team" },
  { en: "tyger claws", pl: "tygrysie pazury" },
  { en: "tyrosine injector", pl: "wstrzykiwacz tyrozyny" },
  { en: "undercity", pl: "podziemne miasto" },
  { en: "underground", pl: "podziemie" },
  { en: "urban", pl: "miejski" },
  { en: "utopia", pl: "utopia" },
  { en: "valentinos", pl: "valentinos" },
  { en: "vampyres", pl: "vampyres" },
  { en: "vendor", pl: "sprzedawca" },
  { en: "verticality", pl: "pionowość" },
  { en: "vesta", pl: "vesta" },
  { en: "viktor vector", pl: "viktor vector" },
  { en: "virtual reality", pl: "rzeczywistość wirtualna" },
  { en: "voodoo boys", pl: "voodoo boys" },
  { en: "wakako okada", pl: "wakako okada" },
  { en: "wardrobe", pl: "garderoba" },
  { en: "wasteland", pl: "pustkowie" },
  { en: "watson", pl: "watson" },
  { en: "weapon glitch", pl: "usterka broni" },
  { en: "wellsprings", pl: "wellsprings" },
  { en: "westbrook", pl: "westbrook" },
  { en: "wetware", pl: "wetware" },
  { en: "whistle", pl: "gwizdek" },
  { en: "wire", pl: "drut" },
  { en: "woodman", pl: "woodman" },
  { en: "world news service", pl: "światowe serwisy informacyjne" },
  { en: "wraiths", pl: "widma" },
  { en: "wrench", pl: "klucz francuski" },
  { en: "yorinobu arasaka", pl: "yorinobu arasaka" },
  { en: "zyntec", pl: "zyntec" },
];
