var WORDS_CYBERPUNK = [
  { en: "abandoned", pl: "opuszczony" },
  { en: "access token", pl: "token dostępu" },
  { en: "animals", pl: "zwierzęta" },
  { en: "arm", pl: "ramię" },
  { en: "assassin", pl: "skrytobójca" },
  { en: "attribute", pl: "atrybut" },
  { en: "backpack", pl: "plecak" },
  { en: "black ice", pl: "czarny lód" },
  { en: "bounce back", pl: "bounce back" },
  { en: "brick", pl: "brick" },
  { en: "city center", pl: "centrum miasta" },
  { en: "claws", pl: "pazury" },
  { en: "consciousness", pl: "świadomość" },
  { en: "dark matter", pl: "ciemna materia" },
  { en: "dilapidated", pl: "zniszczony" },
  { en: "electric", pl: "elektryczny" },
  { en: "emotion", pl: "emocja" },
  { en: "experience", pl: "doświadczenie" },
  { en: "face", pl: "twarz" },
  { en: "fast travel", pl: "szybka podróż" },
  { en: "fingers", pl: "fingers" },
  { en: "hand", pl: "dłoń" },
  { en: "ice", pl: "ICE" },
  { en: "iron", pl: "broń" },
  { en: "katana", pl: "katana" },
  { en: "knife", pl: "nóż" },
  { en: "leg", pl: "noga" },
  { en: "light machine gun", pl: "lekki karabin maszynowy" },
  { en: "main job", pl: "zadanie główne" },
  { en: "melee", pl: "walka wręcz" },
  { en: "memory wipe", pl: "wyczyszczenie pamięci" },
  { en: "mercenary", pl: "najemnik" },
  { en: "nervous system", pl: "układ nerwowy" },
  { en: "night city", pl: "night city" },
  { en: "operating system", pl: "system operacyjny" },
  { en: "outlaw", pl: "banita" },
  { en: "pain editor", pl: "edytor bólu" },
  { en: "power", pl: "kinetyczny" },
  { en: "power armor", pl: "pancerz wspomagany" },
  { en: "river ward", pl: "river ward" },
  { en: "second heart", pl: "drugie serce" },
  { en: "side job", pl: "zadanie poboczne" },
  { en: "sixth street", pl: "szósta ulica" },
  { en: "skeleton", pl: "szkielet" },
  { en: "skill", pl: "umiejętność" },
  { en: "smart", pl: "inteligentny" },
  { en: "smash", pl: "smash" },
  { en: "space force", pl: "siły kosmiczne" },
  { en: "the stacks", pl: "stosy" },
  { en: "trace", pl: "namierzenie" },
  { en: "underground", pl: "podziemie" },
  { en: "vendor", pl: "sprzedawca" },
  { en: "whistle", pl: "gwizdek" },
  { en: "wire", pl: "drut" },
  { en: "world news service", pl: "światowe serwisy informacyjne" }
];
