var WORDS_FINALFANTASY = [
  { en: "absorb", pl: "absorbować" },
  { en: "abyss", pl: "otchłań" },
  { en: "ancient forest", pl: "starożytny las" },
  { en: "assassin", pl: "skrytobójca" },
  { en: "axe", pl: "topór" },
  { en: "bad breath", pl: "nieświeży oddech" },
  { en: "balance", pl: "równowaga" },
  { en: "bard", pl: "bard" },
  { en: "berserker", pl: "berserker" },
  { en: "black mage", pl: "czarny mag" },
  { en: "blind", pl: "oślepienie" },
  { en: "blue mage", pl: "niebieski mag" },
  { en: "bolt", pl: "piorun" },
  { en: "broadsword", pl: "miecz szeroki" },
  { en: "calm lands", pl: "spokojne ziemie" },
  { en: "camaraderie", pl: "koleżeństwo" },
  { en: "chain", pl: "łańcuch" },
  { en: "chaos", pl: "chaos" },
  { en: "claw", pl: "szpon" },
  { en: "cocoon", pl: "kokon" },
  { en: "confusion", pl: "dezorientacja" },
  { en: "conspiracy", pl: "spisek" },
  { en: "courage", pl: "odwaga" },
  { en: "creation", pl: "stworzenie" },
  { en: "crossbow", pl: "kusza" },
  { en: "crown", pl: "korona" },
  { en: "crystal", pl: "kryształ" },
  { en: "curse", pl: "klątwa" },
  { en: "dagger", pl: "sztylet" },
  { en: "dark", pl: "mrok" },
  { en: "darkness", pl: "ciemność" },
  { en: "death machine", pl: "maszyna śmierci" },
  { en: "demon", pl: "demon" },
  { en: "destiny", pl: "przeznaczenie" },
  { en: "dimensional", pl: "wymiarowy" },
  { en: "divine", pl: "boski" },
  { en: "drain", pl: "wysysanie" },
  { en: "draw", pl: "pobieranie" },
  { en: "druid", pl: "druid" },
  { en: "duty", pl: "obowiązek" },
  { en: "echo", pl: "echo" },
  { en: "eternity", pl: "wieczność" },
  { en: "extinction", pl: "wyginięcie" },
  { en: "faith", pl: "wiara" },
  { en: "fiend", pl: "czart" },
  { en: "fire", pl: "ogień" },
  { en: "flame", pl: "płomień" },
  { en: "flood", pl: "powódź" },
  { en: "forgiveness", pl: "przebaczenie" },
  { en: "fury", pl: "furia" },
  { en: "gem", pl: "klejnot" },
  { en: "ghost", pl: "duch" },
  { en: "ghoul", pl: "ghul" },
  { en: "giant", pl: "olbrzym" },
  { en: "gnome", pl: "gnom" },
  { en: "gold", pl: "złoty" },
  { en: "gravity", pl: "grawitacja" },
  { en: "green mage", pl: "zielony mag" },
  { en: "grief", pl: "żal" },
  { en: "halberd", pl: "halabarda" },
  { en: "heal", pl: "uzdrowić" },
  { en: "heritage", pl: "spuścizna" },
  { en: "holy", pl: "święty" },
  { en: "hope", pl: "nadzieja" },
  { en: "hurricane", pl: "huragan" },
  { en: "iron giant", pl: "żelazny olbrzym" },
  { en: "jelly", pl: "galareta" },
  { en: "katana", pl: "katana" },
  { en: "legacy", pl: "dziedzictwo" },
  { en: "lightning", pl: "błyskawica" },
  { en: "loyalty", pl: "lojalność" },
  { en: "maidens kiss", pl: "pocałunek dziewicy" },
  { en: "manticore", pl: "mantykora" },
  { en: "melancholy", pl: "melancholia" },
  { en: "memory", pl: "wspomnienie" },
  { en: "monk", pl: "mnich" },
  { en: "morning star", pl: "gwiazda poranna" },
  { en: "mute", pl: "niemota" },
  { en: "northern cave", pl: "północna jaskinia" },
  { en: "ogre", pl: "ogr" },
  { en: "order", pl: "porządek" },
  { en: "paladin", pl: "paladyn" },
  { en: "paralysis", pl: "paraliż" },
  { en: "poison", pl: "trucizna" },
  { en: "potion", pl: "mikstura" },
  { en: "priest", pl: "kapłan" },
  { en: "promise", pl: "obietnica" },
  { en: "prophecy", pl: "proroctwo" },
  { en: "protect", pl: "ochrona" },
  { en: "rage", pl: "szał" },
  { en: "realm", pl: "królestwo" },
  { en: "red mage", pl: "czerwony mag" },
  { en: "reflection", pl: "odbicie/refleksja" },
  { en: "resistance", pl: "ruch oporu" },
  { en: "revelation", pl: "objawienie" },
  { en: "scholar", pl: "uczony" },
  { en: "scimitar", pl: "sejmitar" },
  { en: "sea serpent", pl: "wąż morski" },
  { en: "shadow", pl: "cień" },
  { en: "shell", pl: "skorupa" },
  { en: "shield", pl: "tarcza" },
  { en: "silence", pl: "cisza" },
  { en: "silver", pl: "srebrny" },
  { en: "sin", pl: "grzech/sin" },
  { en: "skeleton", pl: "szkielet" },
  { en: "sleep", pl: "sen" },
  { en: "sleeping bag", pl: "śpiwór" },
  { en: "slime", pl: "szlam" },
  { en: "slow", pl: "spowolnienie" },
  { en: "soldier", pl: "żołnierz" },
  { en: "sorceress", pl: "czarodziejka" },
  { en: "spear", pl: "włócznia" },
  { en: "spirit", pl: "duch" },
  { en: "staff", pl: "laska" },
  { en: "stone", pl: "kamień" },
  { en: "tent", pl: "namiot" },
  { en: "thief", pl: "złodziej" },
  { en: "throne", pl: "tron" },
  { en: "thunder", pl: "grom" },
  { en: "thunder plains", pl: "równiny gromu" },
  { en: "time mage", pl: "mag czasu" },
  { en: "titan", pl: "tytan" },
  { en: "tome", pl: "tom" },
  { en: "treasure", pl: "skarb" },
  { en: "underground", pl: "podziemie" },
  { en: "venom", pl: "jad" },
  { en: "vision", pl: "wizja" },
  { en: "vow", pl: "ślub" },
  { en: "wall", pl: "ściana" },
  { en: "ward", pl: "osłona" },
  { en: "warrior", pl: "wojownik" },
  { en: "warrior of light", pl: "wojownik światła" },
  { en: "water", pl: "woda" },
  { en: "weapon", pl: "broń/monstrum" },
  { en: "whip", pl: "bicz" },
  { en: "white mage", pl: "biały mag" },
  { en: "white wind", pl: "biały wiatr" },
  { en: "zombie", pl: "zombie" }
];
