var WORDS_ONCEHUMAN = [
  { en: "abandoned", pl: "porzucony" },
  { en: "aberration", pl: "aberracja" },
  { en: "abomination", pl: "ohyda" },
  { en: "abrasion", pl: "otarcie" },
  { en: "abscess", pl: "ropień" },
  { en: "absolution", pl: "rozgrzeszenie" },
  { en: "abysmal", pl: "otchłanny" },
  { en: "abyss", pl: "otchłań" },
  { en: "adversity", pl: "przeciwności" },
  { en: "affliction", pl: "dolegliwość" },
  { en: "agony", pl: "agonia" },
  { en: "ailment", pl: "dolegliwość" },
  { en: "alliance", pl: "sojusz" },
  { en: "ambush", pl: "zasadzka" },
  { en: "amnesia", pl: "amnezja" },
  { en: "amputation", pl: "amputacja" },
  { en: "anatomy", pl: "anatomia" },
  { en: "anchor", pl: "kotwica" },
  { en: "ancient", pl: "starożytny" },
  { en: "anguish", pl: "udręka" },
  { en: "annihilation", pl: "zagłada" },
  { en: "anomaly", pl: "anomalia" },
  { en: "antediluvian", pl: "przedpotopowy" },
  { en: "antibody", pl: "przeciwciało" },
  { en: "antidote", pl: "odtrutka" },
  { en: "antitoxin", pl: "antytoksyna" },
  { en: "apocalypse", pl: "apokalipsa" },
  { en: "apocalyptic", pl: "apokaliptyczny" },
  { en: "appalling", pl: "przerażający" },
  { en: "apparition", pl: "zjawa" },
  { en: "arcane", pl: "tajemny" },
  { en: "arid", pl: "suchy" },
  { en: "armageddon", pl: "armagedon" },
  { en: "armory", pl: "zbrojownia" },
  { en: "arsenal", pl: "arsenał" },
  { en: "artifact", pl: "artefakt" },
  { en: "ascension", pl: "wzniesienie" },
  { en: "assault", pl: "szturm" },
  { en: "assembly", pl: "montaż" },
  { en: "assimilation", pl: "asymilacja" },
  { en: "atonement", pl: "zadośćuczynienie" },
  { en: "atrocious", pl: "okropny" },
  { en: "atrophy", pl: "atrofia" },
  { en: "audit", pl: "audyt" },
  { en: "augury", pl: "wróżba" },
  { en: "autopsy", pl: "autopsja" },
  { en: "avalanche", pl: "lawina" },
  { en: "aversion", pl: "awersja" },
  { en: "awakening", pl: "przebudzenie" },
  { en: "bacterium", pl: "bakteria" },
  { en: "badlands", pl: "nieużytki" },
  { en: "ballistic", pl: "balistyczny" },
  { en: "banishment", pl: "wypędzenie" },
  { en: "barbaric", pl: "barbarzyński" },
  { en: "barrage", pl: "kanonada" },
  { en: "barrel", pl: "lufa" },
  { en: "barren", pl: "jałowy" },
  { en: "barricade", pl: "barykada" },
  { en: "bastion", pl: "bastion" },
  { en: "beacon", pl: "latarnia" },
  { en: "behemoth", pl: "behemot" },
  { en: "berserk", pl: "berserk" },
  { en: "biopsy", pl: "biopsja" },
  { en: "bivouac", pl: "biwak" },
  { en: "bleak", pl: "ponury" },
  { en: "blight", pl: "zaraza" },
  { en: "blizzard", pl: "zamieć" },
  { en: "blockade", pl: "blokada" },
  { en: "blueprint", pl: "schemat" },
  { en: "breach", pl: "wyrwa" },
  { en: "broadside", pl: "burta" },
  { en: "brood", pl: "lęg" },
  { en: "brutal", pl: "brutalny" },
  { en: "bulwark", pl: "przedmurze" },
  { en: "bunker", pl: "bunkier" },
  { en: "burrow", pl: "kryjówka" },
  { en: "calamity", pl: "klęska" },
  { en: "caliber", pl: "kaliber" },
  { en: "calibration", pl: "kalibracja" },
  { en: "canyon", pl: "kanion" },
  { en: "carcinogen", pl: "karcynogen" },
  { en: "carcinoma", pl: "rak" },
  { en: "carrion", pl: "padlina" },
  { en: "cartel", pl: "kartel" },
  { en: "cartography", pl: "kartografia" },
  { en: "cartridge", pl: "nabój" },
  { en: "casing", pl: "łuska" },
  { en: "cataclysm", pl: "kataklizm" },
  { en: "catastrophe", pl: "katastrofa" },
  { en: "cave", pl: "jaskinia" },
  { en: "cavern", pl: "pieczara" },
  { en: "celestial", pl: "niebiański" },
  { en: "chaosweaver", pl: "tkacz chaosu" },
  { en: "chasm", pl: "przepaść" },
  { en: "chromosome", pl: "chromosom" },
  { en: "cipher", pl: "szyfr" },
  { en: "citadel", pl: "cytadela" },
  { en: "clairvoyance", pl: "jasnowidzenie" },
  { en: "classified", pl: "utajnione" },
  { en: "cleansing", pl: "oczyszczanie" },
  { en: "cliff", pl: "klif" },
  { en: "cloning", pl: "klonowanie" },
  { en: "clotting", pl: "krzepnięcie" },
  { en: "coagulation", pl: "krzepnięcie" },
  { en: "cognition", pl: "poznanie" },
  { en: "collaborator", pl: "kolaborant" },
  { en: "collusion", pl: "zmowa" },
  { en: "colossus", pl: "kolos" },
  { en: "column", pl: "kolumna" },
  { en: "compliance", pl: "zgodność" },
  { en: "compound", pl: "kompleks" },
  { en: "compulsion", pl: "przymus" },
  { en: "comrade", pl: "towarzysz" },
  { en: "concussion", pl: "wstrząs mózgu" },
  { en: "confidential", pl: "poufne" },
  { en: "conglomerate", pl: "konglomerat" },
  { en: "consciousness", pl: "świadomość" },
  { en: "conspiracy", pl: "spisek" },
  { en: "construction", pl: "konstrukcja" },
  { en: "contagion", pl: "zaraza" },
  { en: "containment", pl: "powstrzymanie" },
  { en: "contamination", pl: "skażenie" },
  { en: "contempt", pl: "pogarda" },
  { en: "contusion", pl: "stłuczenie" },
  { en: "convalescence", pl: "rekonwalescencja" },
  { en: "coordinates", pl: "współrzędne" },
  { en: "corporation", pl: "korporacja" },
  { en: "corruption", pl: "zepsucie" },
  { en: "cosmic", pl: "kosmiczny" },
  { en: "counterattack", pl: "kontratak" },
  { en: "coverup", pl: "ukrywanie" },
  { en: "crag", pl: "urwisko" },
  { en: "craving", pl: "pragnienie" },
  { en: "crawler", pl: "pełzacz" },
  { en: "crosshair", pl: "celownik" },
  { en: "crude", pl: "surowy" },
  { en: "crumbling", pl: "rozpadający się" },
  { en: "crusade", pl: "krucjata" },
  { en: "cultivation", pl: "kultywacja" },
  { en: "culture", pl: "hodowla" },
  { en: "cyclone", pl: "cyklon" },
  { en: "damnation", pl: "potępienie" },
  { en: "deadly", pl: "zabójczy" },
  { en: "debris", pl: "gruz" },
  { en: "decay", pl: "rozkład" },
  { en: "decayed", pl: "zbutwiały" },
  { en: "decomposition", pl: "dekompozycja" },
  { en: "decrepit", pl: "zrujnowany" },
  { en: "defector", pl: "dezerter" },
  { en: "degeneration", pl: "degeneracja" },
  { en: "dehydration", pl: "odwodnienie" },
  { en: "delirium", pl: "majaczenie" },
  { en: "deluge", pl: "potop" },
  { en: "delusion", pl: "urojenie" },
  { en: "dementia", pl: "demencja" },
  { en: "demonic", pl: "demoniczny" },
  { en: "den", pl: "nora" },
  { en: "deplorable", pl: "godny ubolewania" },
  { en: "deprivation", pl: "deprywacja" },
  { en: "derelict", pl: "opuszczony" },
  { en: "desire", pl: "pożądanie" },
  { en: "desolate", pl: "opustoszały" },
  { en: "desolation", pl: "spustoszenie" },
  { en: "despair", pl: "beznadzieja" },
  { en: "deterioration", pl: "pogorszenie" },
  { en: "devastation", pl: "dewastacja" },
  { en: "deviant", pl: "odmieniec" },
  { en: "deviation", pl: "odchylenie" },
  { en: "diabolical", pl: "diabelski" },
  { en: "diagnosis", pl: "diagnoza" },
  { en: "dilapidated", pl: "zniszczony" },
  { en: "dimensional", pl: "wymiarowy" },
  { en: "disassembly", pl: "demontaż" },
  { en: "disdain", pl: "lekceważenie" },
  { en: "disgust", pl: "obrzydzenie" },
  { en: "dismal", pl: "ponury" },
  { en: "disruption", pl: "zakłócenie" },
  { en: "dissection", pl: "sekcja" },
  { en: "distortion", pl: "zniekształcenie" },
  { en: "distress", pl: "rozpacz" },
  { en: "divination", pl: "wróżbiarstwo" },
  { en: "downpour", pl: "ulewa" },
  { en: "dread", pl: "strach" },
  { en: "dreadful", pl: "straszny" },
  { en: "dreary", pl: "ponury" },
  { en: "drought", pl: "susza" },
  { en: "dugout", pl: "ziemianka" },
  { en: "duplication", pl: "duplikacja" },
  { en: "duststorm", pl: "burza pyłowa" },
  { en: "dystopian", pl: "dystopijny" },
  { en: "ego", pl: "ego" },
  { en: "eldritch", pl: "przerażający" },
  { en: "encampment", pl: "obozowisko" },
  { en: "encirclement", pl: "okrążenie" },
  { en: "enclave", pl: "enklawa" },
  { en: "endurance", pl: "wytrzymałość" },
  { en: "enlightenment", pl: "oświecenie" },
  { en: "enterprise", pl: "przedsiębiorstwo" },
  { en: "esoteric", pl: "ezoteryczny" },
  { en: "eternaland", pl: "wiecznoziemie" },
  { en: "ethereal", pl: "nieziemski" },
  { en: "etiology", pl: "etiologia" },
  { en: "evacuation", pl: "ewakuacja" },
  { en: "evolution", pl: "ewolucja" },
  { en: "excavation", pl: "wykopalisko" },
  { en: "execution", pl: "egzekucja" },
  { en: "exfiltration", pl: "eksfiltracja" },
  { en: "exhaustion", pl: "wyczerpanie" },
  { en: "exile", pl: "wygnaniec" },
  { en: "exorcism", pl: "egzorcyzm" },
  { en: "expedition", pl: "ekspedycja" },
  { en: "experimentation", pl: "eksperymentowanie" },
  { en: "extinction", pl: "wyginięcie" },
  { en: "extraction", pl: "ekstrakcja" },
  { en: "fabrication", pl: "wytwarzanie" },
  { en: "faction", pl: "frakcja" },
  { en: "fallout", pl: "opad" },
  { en: "famine", pl: "głód" },
  { en: "fatigue", pl: "zmęczenie" },
  { en: "feral", pl: "zdziczały" },
  { en: "festering", pl: "ropiejący" },
  { en: "firearm", pl: "broń palna" },
  { en: "fixation", pl: "fiksacja" },
  { en: "flanking", pl: "oskrzydlanie" },
  { en: "flashflood", pl: "powódź błyskawiczna" },
  { en: "fluctuation", pl: "fluktuacja" },
  { en: "foraging", pl: "zbieractwo" },
  { en: "forsaken", pl: "opuszczony" },
  { en: "fortification", pl: "fortyfikacja" },
  { en: "fortitude", pl: "męstwo" },
  { en: "fortress", pl: "twierdza" },
  { en: "foul", pl: "ohydny" },
  { en: "foxhole", pl: "okop" },
  { en: "franchise", pl: "franczyza" },
  { en: "frenzy", pl: "furia" },
  { en: "frequency", pl: "częstotliwość" },
  { en: "frontier", pl: "pogranicze" },
  { en: "frostbite", pl: "odmrożenie" },
  { en: "fugitive", pl: "zbieg" },
  { en: "fungus", pl: "grzyb" },
  { en: "gale", pl: "wichura" },
  { en: "gangrene", pl: "zgorzel" },
  { en: "gangrenous", pl: "zgorzelinowy" },
  { en: "garrison", pl: "garnizon" },
  { en: "genetic", pl: "genetyczny" },
  { en: "genome", pl: "genom" },
  { en: "ghastly", pl: "upiorny" },
  { en: "ghoulish", pl: "upiorny" },
  { en: "gloomy", pl: "posępny" },
  { en: "gorge", pl: "wąwóz" },
  { en: "grief", pl: "żal" },
  { en: "grim", pl: "złowieszczy" },
  { en: "grisly", pl: "przerażający" },
  { en: "grotesque", pl: "groteskowy" },
  { en: "grotto", pl: "grota" },
  { en: "grudge", pl: "uraza" },
  { en: "gruesome", pl: "makabryczny" },
  { en: "hailstorm", pl: "gradobicie" },
  { en: "hallucination", pl: "halucynacja" },
  { en: "harbinger", pl: "zwiastun" },
  { en: "hardship", pl: "trudności" },
  { en: "harsh", pl: "surowy" },
  { en: "haunting", pl: "nawiedzanie" },
  { en: "heatstroke", pl: "udar cieplny" },
  { en: "hellish", pl: "piekielny" },
  { en: "hemorrhage", pl: "krwotok" },
  { en: "hideous", pl: "ohydny" },
  { en: "hinterland", pl: "głębia lądu" },
  { en: "hive", pl: "ul" },
  { en: "holdout", pl: "punkt oporu" },
  { en: "horde", pl: "horda" },
  { en: "horrendous", pl: "straszliwy" },
  { en: "horrifying", pl: "przerażający" },
  { en: "hurricane", pl: "huragan" },
  { en: "hypothermia", pl: "hipotermia" },
  { en: "hysteria", pl: "histeria" },
  { en: "identity", pl: "tożsamość" },
  { en: "igna", pl: "Igna (antagonista)" },
  { en: "illusion", pl: "iluzja" },
  { en: "immunization", pl: "uodpornienie" },
  { en: "improvised", pl: "improwizowany" },
  { en: "impulse", pl: "impuls" },
  { en: "incision", pl: "nacięcie" },
  { en: "incorporeal", pl: "bezcielesny" },
  { en: "incubation", pl: "inkubacja" },
  { en: "incursion", pl: "wtargnięcie" },
  { en: "infection", pl: "infekcja" },
  { en: "infernal", pl: "piekielny" },
  { en: "infestation", pl: "plaga" },
  { en: "infiltration", pl: "infiltracja" },
  { en: "infirmity", pl: "niemoc" },
  { en: "inflammation", pl: "zapalenie" },
  { en: "inhospitable", pl: "niegościnny" },
  { en: "inoculation", pl: "szczepienie" },
  { en: "inquiry", pl: "śledztwo" },
  { en: "insanity", pl: "obłęd" },
  { en: "instinct", pl: "instynkt" },
  { en: "insurrection", pl: "insurekcja" },
  { en: "interdimensional", pl: "międzywymiarowy" },
  { en: "interference", pl: "zakłócenia" },
  { en: "intuition", pl: "intuicja" },
  { en: "inundation", pl: "zalanie" },
  { en: "invasion", pl: "inwazja" },
  { en: "investigation", pl: "dochodzenie" },
  { en: "isolation", pl: "izolacja" },
  { en: "judgment", pl: "osąd" },
  { en: "juggernaut", pl: "siłacz" },
  { en: "juryrigged", pl: "naprawiony na szybko" },
  { en: "justice", pl: "sprawiedliwość" },
  { en: "laceration", pl: "rany szarpane" },
  { en: "lair", pl: "legowisko" },
  { en: "lamentable", pl: "opłakany" },
  { en: "landmark", pl: "punkt orientacyjny" },
  { en: "ledge", pl: "półka skalna" },
  { en: "lesion", pl: "zmiana" },
  { en: "lethal", pl: "śmiertelny" },
  { en: "lethality", pl: "śmiertelność" },
  { en: "leviathan", pl: "lewiatan" },
  { en: "liability", pl: "odpowiedzialność" },
  { en: "lightning", pl: "błyskawica" },
  { en: "loathing", pl: "wstręt" },
  { en: "lockdown", pl: "blokada" },
  { en: "longing", pl: "pragnienie" },
  { en: "lookout", pl: "punkt obserwacyjny" },
  { en: "lunacy", pl: "obłęd" },
  { en: "lurker", pl: "czający się" },
  { en: "lymphoma", pl: "chłoniak" },
  { en: "macabre", pl: "makabryczny" },
  { en: "madness", pl: "szaleństwo" },
  { en: "magazine", pl: "magazynek" },
  { en: "makeshift", pl: "prowizoryczny" },
  { en: "malady", pl: "choroba" },
  { en: "malevolent", pl: "wrogi" },
  { en: "malicious", pl: "złośliwy" },
  { en: "malignancy", pl: "złośliwość" },
  { en: "malnutrition", pl: "niedożywienie" },
  { en: "malpractice", pl: "błąd w sztuce" },
  { en: "mania", pl: "mania" },
  { en: "manifestation", pl: "manifestacja" },
  { en: "manufacturing", pl: "produkcja" },
  { en: "mayfly", pl: "jętka" },
  { en: "medium", pl: "medium" },
  { en: "melancholy", pl: "melancholia" },
  { en: "melanoma", pl: "czerniak" },
  { en: "memetic", pl: "memetyczny" },
  { en: "merciless", pl: "bezlitosny" },
  { en: "metahuman", pl: "meta-człowiek" },
  { en: "metamorphosis", pl: "metamorfoza" },
  { en: "metastasis", pl: "przerzut" },
  { en: "mildew", pl: "pleśń" },
  { en: "mirage", pl: "miraż" },
  { en: "miserable", pl: "nieszczęśliwy" },
  { en: "mitsuko", pl: "Mitsuko (pierwsza meta-człowiek)" },
  { en: "mold", pl: "pleśń" },
  { en: "monolith", pl: "monolit" },
  { en: "monopoly", pl: "monopol" },
  { en: "monsoon", pl: "monsun" },
  { en: "monstrosity", pl: "potworność" },
  { en: "monstrous", pl: "potworny" },
  { en: "morbid", pl: "morbityczny" },
  { en: "morphology", pl: "morfologia" },
  { en: "munition", pl: "amunicja" },
  { en: "mutagen", pl: "mutagen" },
  { en: "mutant", pl: "mutant" },
  { en: "mutation", pl: "mutacja" },
  { en: "mutilation", pl: "okaleczenie" },
  { en: "muzzle", pl: "wylot lufy" },
  { en: "mystical", pl: "mistyczny" },
  { en: "navigate", pl: "nawigować" },
  { en: "necropsy", pl: "nekropsja" },
  { en: "necrosis", pl: "martwica" },
  { en: "nefarious", pl: "nikczemny" },
  { en: "negligence", pl: "zaniedbanie" },
  { en: "nest", pl: "gniazdo" },
  { en: "nightmare", pl: "koszmar" },
  { en: "nomad", pl: "nomada" },
  { en: "nostalgia", pl: "nostalgia" },
  { en: "noxious", pl: "trujący" },
  { en: "obliteration", pl: "unicestwienie" },
  { en: "obsession", pl: "obsesja" },
  { en: "occult", pl: "okultystyczny" },
  { en: "offensive", pl: "ofensywa" },
  { en: "omen", pl: "omen" },
  { en: "ominous", pl: "złowrogi" },
  { en: "onslaught", pl: "natarcie" },
  { en: "oracle", pl: "wyrocznia" },
  { en: "ordinance", pl: "uzbrojenie" },
  { en: "orienteering", pl: "orientacja" },
  { en: "outback", pl: "odludzie" },
  { en: "outcast", pl: "wyrzutek" },
  { en: "outpost", pl: "placówka" },
  { en: "overhang", pl: "nawis" },
  { en: "palisade", pl: "palisada" },
  { en: "pandemic", pl: "pandemia" },
  { en: "paranoia", pl: "paranoja" },
  { en: "paranormal", pl: "paranormalny" },
  { en: "parasite", pl: "pasożyt" },
  { en: "pariah", pl: "parias" },
  { en: "pathogen", pl: "patogen" },
  { en: "pathology", pl: "patologia" },
  { en: "penance", pl: "pokuta" },
  { en: "penetration", pl: "penetracja" },
  { en: "perception", pl: "percepcja" },
  { en: "perilous", pl: "niebezpieczny" },
  { en: "perimeter", pl: "obwód" },
  { en: "permafrost", pl: "wieczna zmarzlina" },
  { en: "perseverance", pl: "wytrwałość" },
  { en: "pestilence", pl: "zaraza" },
  { en: "phantasm", pl: "fantazmat" },
  { en: "phantasmal", pl: "fantazmatyczny" },
  { en: "phantom", pl: "fantom" },
  { en: "physiology", pl: "fizjologia" },
  { en: "pilgrim", pl: "pielgrzym" },
  { en: "pincer", pl: "kleszcze" },
  { en: "pitiful", pl: "żałosny" },
  { en: "pitiless", pl: "nielitościwy" },
  { en: "plateau", pl: "płaskowyż" },
  { en: "pollution", pl: "zanieczyszczenie" },
  { en: "poltergeist", pl: "poltergeist" },
  { en: "possession", pl: "opętanie" },
  { en: "postapocalyptic", pl: "postapokaliptyczny" },
  { en: "precarious", pl: "niepewny" },
  { en: "precipice", pl: "przepaść" },
  { en: "precognition", pl: "prekognicja" },
  { en: "predator", pl: "drapieżnik" },
  { en: "prehistoric", pl: "prehistoryczny" },
  { en: "preternatural", pl: "nadnaturalny" },
  { en: "primal", pl: "pierwotny" },
  { en: "primitive", pl: "prymitywny" },
  { en: "primordial", pl: "pierwotny" },
  { en: "prognosis", pl: "rokowanie" },
  { en: "projectile", pl: "pocisk" },
  { en: "prophecy", pl: "proroctwo" },
  { en: "prophet", pl: "prorok" },
  { en: "protocol", pl: "protokół" },
  { en: "provisioning", pl: "zaopatrywanie" },
  { en: "prowler", pl: "podkradacz" },
  { en: "psionic", pl: "psioniczny" },
  { en: "psyche", pl: "psychika" },
  { en: "psychic", pl: "psychiczny" },
  { en: "psychosis", pl: "psychoza" },
  { en: "purge", pl: "czystka" },
  { en: "putrefaction", pl: "gnicie" },
  { en: "putrid", pl: "cuchnący" },
  { en: "quarantine", pl: "kwarantanna" },
  { en: "radiation", pl: "promieniowanie" },
  { en: "rampart", pl: "wał obronny" },
  { en: "rank", pl: "śmierdzący" },
  { en: "rapture", pl: "uniesienie" },
  { en: "ravine", pl: "jar" },
  { en: "rebellion", pl: "bunt" },
  { en: "reckoning", pl: "rozrachunek" },
  { en: "reclamation", pl: "odzyskiwanie" },
  { en: "recoil", pl: "odrzut" },
  { en: "redacted", pl: "ocenzurowane" },
  { en: "redemption", pl: "odkupienie" },
  { en: "refinement", pl: "uszlachetnianie" },
  { en: "refuge", pl: "schronienie" },
  { en: "refugee", pl: "uchodźca" },
  { en: "regeneration", pl: "regeneracja" },
  { en: "rehabilitation", pl: "rehabilitacja" },
  { en: "reinforcement", pl: "wzmocnienie" },
  { en: "relapse", pl: "nawrót" },
  { en: "relentless", pl: "nieubłagany" },
  { en: "relic", pl: "relikwia" },
  { en: "remission", pl: "remisja" },
  { en: "remnant", pl: "pozostałość" },
  { en: "remorseless", pl: "bez skruchy" },
  { en: "renegade", pl: "renegat" },
  { en: "replication", pl: "replikacja" },
  { en: "repurpose", pl: "przeznaczyć ponownie" },
  { en: "resentment", pl: "uraza" },
  { en: "resilience", pl: "odporność" },
  { en: "resistance", pl: "ruch oporu" },
  { en: "resuscitation", pl: "reanimacja" },
  { en: "retaliation", pl: "odwet" },
  { en: "retreat", pl: "odwrót" },
  { en: "retribution", pl: "zapłata" },
  { en: "revelation", pl: "objawienie" },
  { en: "revulsion", pl: "odraza" },
  { en: "ricochet", pl: "rykoszet" },
  { en: "ridge", pl: "grzbiet" },
  { en: "rift", pl: "szczelina" },
  { en: "roamer", pl: "łazik" },
  { en: "rosetta", pl: "Rosetta (korporacja)" },
  { en: "rotting", pl: "gnijący" },
  { en: "rout", pl: "rozgromienie" },
  { en: "rubble", pl: "rumowisko" },
  { en: "rudimentary", pl: "prymitywny" },
  { en: "ruination", pl: "ruina" },
  { en: "ruthless", pl: "bezwzględny" },
  { en: "salvage", pl: "odzysk" },
  { en: "salvation", pl: "zbawienie" },
  { en: "salvo", pl: "salwa" },
  { en: "sample", pl: "próbka" },
  { en: "sanctuary", pl: "sanktuarium" },
  { en: "sandstorm", pl: "burza piaskowa" },
  { en: "sanity", pl: "poczytalność" },
  { en: "sarcoma", pl: "mięsak" },
  { en: "savage", pl: "dziki" },
  { en: "scarring", pl: "bliznowacenie" },
  { en: "scavenger", pl: "padlinożerca" },
  { en: "scavenging", pl: "szperanie" },
  { en: "scenario", pl: "scenariusz" },
  { en: "scope", pl: "celownik" },
  { en: "scorching", pl: "palący" },
  { en: "scorn", pl: "pogarda" },
  { en: "scrap", pl: "złom" },
  { en: "scrutiny", pl: "kontrola" },
  { en: "seance", pl: "seans" },
  { en: "seer", pl: "jasnowidz" },
  { en: "sentence", pl: "wyrok" },
  { en: "sepsis", pl: "sepsa" },
  { en: "settlement", pl: "osada" },
  { en: "shade", pl: "cień" },
  { en: "shelter", pl: "schron" },
  { en: "siege", pl: "oblężenie" },
  { en: "signal", pl: "sygnał" },
  { en: "silo", pl: "silos" },
  { en: "sinister", pl: "złowieszczy" },
  { en: "skirmish", pl: "potyczka" },
  { en: "snowstorm", pl: "śnieżyca" },
  { en: "somber", pl: "ponury" },
  { en: "sorrow", pl: "smutek" },
  { en: "sortie", pl: "wypad" },
  { en: "spawn", pl: "pomiot" },
  { en: "specimen", pl: "okaz" },
  { en: "spectral", pl: "widmowy" },
  { en: "spectre", pl: "widmo" },
  { en: "spore", pl: "zarodnik" },
  { en: "squall", pl: "szkwał" },
  { en: "stalker", pl: "prześladowca" },
  { en: "stardust", pl: "gwiezdny pył" },
  { en: "starfall", pl: "gwiezdny upadek" },
  { en: "starvation", pl: "głodowanie" },
  { en: "static", pl: "zakłócenia" },
  { en: "stock", pl: "kolba" },
  { en: "stockade", pl: "ostrokół" },
  { en: "stoppingpower", pl: "siła obalająca" },
  { en: "stronghold", pl: "twierdza" },
  { en: "subconscious", pl: "podświadomość" },
  { en: "subsidiary", pl: "filia" },
  { en: "subsistence", pl: "egzystencja" },
  { en: "supernatural", pl: "nadprzyrodzony" },
  { en: "suppressor", pl: "tłumik" },
  { en: "suppuration", pl: "ropienie" },
  { en: "survivalist", pl: "surwiwalista" },
  { en: "sustenance", pl: "pożywienie" },
  { en: "swarm", pl: "rój" },
  { en: "symptom", pl: "objaw" },
  { en: "syndicate", pl: "syndykat" },
  { en: "syndrome", pl: "syndrom" },
  { en: "synthesis", pl: "synteza" },
  { en: "telekinesis", pl: "telekineza" },
  { en: "telepathy", pl: "telepatia" },
  { en: "tempest", pl: "wichura" },
  { en: "temptation", pl: "pokusa" },
  { en: "tenacity", pl: "zaciętość" },
  { en: "terrifying", pl: "przerażający" },
  { en: "territory", pl: "terytorium" },
  { en: "terror", pl: "terror" },
  { en: "thunderbolt", pl: "grom" },
  { en: "thunderstorm", pl: "burza" },
  { en: "titan", pl: "tytan" },
  { en: "topography", pl: "topografia" },
  { en: "torment", pl: "męka" },
  { en: "tornado", pl: "tornado" },
  { en: "torrent", pl: "rwący potok" },
  { en: "toxic", pl: "toksyczny" },
  { en: "toxicity", pl: "toksyczność" },
  { en: "trajectory", pl: "trajektoria" },
  { en: "transcendence", pl: "transcendencja" },
  { en: "transmission", pl: "transmisja" },
  { en: "transmutation", pl: "transmutacja" },
  { en: "trauma", pl: "trauma" },
  { en: "traverse", pl: "przemierzać" },
  { en: "treacherous", pl: "zdradliwy" },
  { en: "trench", pl: "okop" },
  { en: "trigger", pl: "spust" },
  { en: "tumor", pl: "guz" },
  { en: "tunnel", pl: "tunel" },
  { en: "typhoon", pl: "tajfun" },
  { en: "ulcer", pl: "wrzód" },
  { en: "unforgiving", pl: "bezlitosny" },
  { en: "untamed", pl: "nieokiełznany" },
  { en: "upcycle", pl: "przetworzyć" },
  { en: "uprising", pl: "powstanie" },
  { en: "vaccine", pl: "szczepionka" },
  { en: "vagabond", pl: "włóczęga" },
  { en: "vendetta", pl: "wendeta" },
  { en: "vengeance", pl: "zemsta" },
  { en: "venomous", pl: "jadowity" },
  { en: "verdict", pl: "werdykt" },
  { en: "vestige", pl: "ślad" },
  { en: "vicinity", pl: "okolica" },
  { en: "virulent", pl: "zjadliwy" },
  { en: "virus", pl: "wirus" },
  { en: "vivisection", pl: "wiwisekcja" },
  { en: "volley", pl: "salwa" },
  { en: "vulture", pl: "sęp" },
  { en: "wanderer", pl: "wędrowiec" },
  { en: "wasteland", pl: "pustkowie" },
  { en: "watchtower", pl: "wieża strażnicza" },
  { en: "wayfarer", pl: "podróżnik" },
  { en: "waypoint", pl: "punkt orientacyjny" },
  { en: "whirlwind", pl: "trąba powietrzna" },
  { en: "whistleblower", pl: "demaskator" },
  { en: "whiteout", pl: "biała ciemność" },
  { en: "wilderness", pl: "dzicz" },
  { en: "wistfulness", pl: "tęsknota" },
  { en: "wraith", pl: "zjawa" },
  { en: "wreckage", pl: "wrak" },
  { en: "wretched", pl: "nędzny" },
  { en: "yearning", pl: "tęsknota" },
,
  { en: "bear", pl: "niedźwiedź" },
  { en: "bear cub", pl: "niedźwiadek" },
  { en: "boar", pl: "dzik" },
  { en: "boar piglet", pl: "mały dzik" },
  { en: "buck", pl: "rogacz" },
  { en: "capybara", pl: "kapibara" },
  { en: "crocodile", pl: "krokodyl" },
  { en: "crocodile hatchling", pl: "mały krokodyl" },
  { en: "doe", pl: "łania" },
  { en: "ewe", pl: "owca" },
  { en: "fawn", pl: "jelonek" },
  { en: "flamingo", pl: "flaming" },
  { en: "fox", pl: "lis" },
  { en: "leopard", pl: "lampart" },
  { en: "lamb", pl: "jagnię" },
  { en: "little capybara", pl: "mała kapibara" },
  { en: "little flamingo", pl: "mały flaming" },
  { en: "little leopard", pl: "mały lampart" },
  { en: "polar bear", pl: "niedźwiedź polarny" },
  { en: "access permit", pl: "zezwolenie dostępu" },
  { en: "ammo", pl: "amunicja" },
  { en: "battle pass token", pl: "token karnetu bojowego" },
  { en: "blueprint fragments", pl: "fragmenty planów" },
  { en: "blueprints", pl: "plany" },
  { en: "bonus", pl: "bonus" },
  { en: "bottoms", pl: "dolna część garderoby" },
  { en: "calibration blueprints", pl: "plany kalibracji" },
  { en: "charm", pl: "amulet" },
  { en: "collection", pl: "kolekcja" },
  { en: "consumable", pl: "materiał eksploatacyjny" },
  { en: "cradle charms", pl: "ozdoby kolebki" },
  { en: "decorative item", pl: "przedmiot dekoracyjny" },
  { en: "deviations", pl: "odchylenia" },
  { en: "door card", pl: "karta dostępu" },
  { en: "emblem", pl: "godło" },
  { en: "expression", pl: "ekspresja" },
  { en: "eyewear", pl: "okulary" },
  { en: "facewear", pl: "nakrycie twarzy" },
  { en: "facilities", pl: "obiekty" },
  { en: "fashion trial card", pl: "karta próbna mody" },
  { en: "feed", pl: "pasza" },
  { en: "festival item", pl: "przedmiot festiwalowy" },
  { en: "food", pl: "jedzenie" },
  { en: "formula", pl: "receptura" },
  { en: "fuel", pl: "paliwo" },
  { en: "gear", pl: "ekwipunek" },
  { en: "gear mod", pl: "modyfikacja ekwipunku" },
  { en: "gloves", pl: "rękawice" },
  { en: "gun", pl: "broń palna" },
  { en: "hairstyle", pl: "fryzura" },
  { en: "headwear", pl: "nakrycie głowy" },
  { en: "impasse material", pl: "materiał specjalny" },
  { en: "large fish", pl: "duża ryba" },
  { en: "makeup", pl: "makijaż" },
  { en: "material", pl: "materiał" },
  { en: "materials", pl: "materiały" },
  { en: "medal", pl: "medal" },
  { en: "medium fish", pl: "średnia ryba" },
  { en: "melee weapon", pl: "broń biała" },
  { en: "mission item", pl: "przedmiot misji" },
  { en: "motorcycle", pl: "motocykl" },
  { en: "off-roader", pl: "pojazd terenowy" },
  { en: "pickup truck", pl: "pickup" },
  { en: "plate trailer", pl: "przyczepa" },
  { en: "profiles", pl: "profile" },
  { en: "seeds", pl: "nasiona" },
  { en: "shoes", pl: "buty" },
  { en: "small fish", pl: "mała ryba" },
  { en: "survival device", pl: "urządzenie przetrwania" },
  { en: "tactical item", pl: "przedmiot taktyczny" },
  { en: "tops", pl: "górna część garderoby" },
  { en: "trial card", pl: "karta próbna" },
  { en: "voucher", pl: "talon" },
  { en: "weapon accessory", pl: "akcesorium broni" },
  { en: "weapon charm", pl: "amulet broni" },
  { en: "weapon skin", pl: "skórka broni" },
  { en: "weapons", pl: "broń" },
  { en: "crossbow", pl: "kusza" },
  { en: "shotgun", pl: "strzelba" },
  { en: "sniper", pl: "snajperka" },
  { en: "assault rifle", pl: "karabin szturmowy" },
  { en: "pistol", pl: "pistolet" },
  { en: "submachine gun", pl: "pistolet maszynowy" },
  { en: "rifle", pl: "karabin" },
  { en: "bow", pl: "łuk" },
  { en: "melee", pl: "walka wręcz" },
  { en: "light machine gun", pl: "lekki karabin maszynowy" },
  { en: "burn", pl: "ogień" },
  { en: "power surge", pl: "przepięcie" },
  { en: "frost vortex", pl: "mroźny wir" },
  { en: "the bull's eye", pl: "bycze oko" },
  { en: "fortress warfare", pl: "wojna forteczna" },
  { en: "unstable bomber", pl: "niestabilny bombowiec" },
  { en: "fast gunner", pl: "szybki strzelec" },
  { en: "bounce", pl: "rykoszet" },
  { en: "shrapnel", pl: "szrapnel" },
  { en: "normal", pl: "zwykły" },
  { en: "memetics", pl: "memetyka" },
  { en: "cradle", pl: "kolebka" },
  { en: "tech workbench", pl: "warsztat techniczny" },
  { en: "build planner", pl: "planer budowy" },
  { en: "crescent", pl: "półksiężyc" },
  { en: "downstar", pl: "downstar" },
  { en: "mirror", pl: "lustro" },
  { en: "resonance", pl: "rezonans" },
  { en: "wild", pl: "dziki" },
  { en: "shiny", pl: "lśniący" },
  { en: "mod dust", pl: "pył modyfikacyjny" },
  { en: "mod selection crate", pl: "skrzynia z modyfikacjami" },
  { en: "suffix mod crate", pl: "skrzynia z przyrostkami" },
  { en: "extraction permit", pl: "zezwolenie wydobycia" },
  { en: "refinery permit", pl: "zezwolenie rafinerii" },
  { en: "access card", pl: "karta dostępu" },
  { en: "season pass", pl: "karnet sezonowy" },
  { en: "premium", pl: "premium" },
  { en: "crafting", pl: "rzemiosło" },
  { en: "planner", pl: "planer" },
  { en: "calculator", pl: "kalkulator" },
  { en: "cosmetic", pl: "kosmetyk" }
];
