var WORDS_POE_CARDS = [
  { en: "A Chilling Wind", pl: "Mroźny wiatr [Nagroda: Level 21 Vaal Cold Snap Quality: +20% Corrupted]" },
  { en: "A Dab of Ink", pl: "Kropla atramentu [Nagroda: The Poet's Pen]" },
  { en: "A Dusty Memory", pl: "Zakurzone wspomnienie [Nagroda: Item Item Level: 100 Fractured]" },
  { en: "A Familiar Call", pl: "Znajome wezwanie [Nagroda: Jewellery of Farrul Item Level: 100 Shaper + Hunter Item]" },
  { en: "A Fate Worse Than Death", pl: "Los gorszy niż śmierć [Nagroda: Cortex Corrupted]" },
  { en: "A Modest Request", pl: "Skromna prośba [Nagroda: Megalomaniac Corrupted]" },
  { en: "A Mother's Parting Gift", pl: "Pożegnalny dar matki [Nagroda: Fertile Mind Corrupted]" },
  { en: "A Note in the Wind", pl: "Nuta na wietrze [Nagroda: Asenath's Mark]" },
  { en: "A Sea of Blue", pl: "Morze błękitu [Nagroda: 13x Orb of Alteration]" },
  { en: "A Stone Perfected", pl: "Kamień udoskonalony [Nagroda: Jewel Primordial 1-2 Implicit Corrupted]" },
  { en: "Abandoned Wealth", pl: "Porzucone bogactwo [Nagroda: 3x Exalted Orb]" },
  { en: "Acclimatisation", pl: "Aklimatyzacja [Nagroda: 20x Orb of Alteration]" },
  { en: "Akil's Prophecy", pl: "Proroctwo Akila [Nagroda: Elegant Round Shield Two-Implicit Corrupted]" },
  { en: "Alivia's Grace", pl: "Gracja Alivii [Nagroda: Queen of the Forest]" },
  { en: "Alluring Bounty", pl: "Kusząca nagroda [Nagroda: 10x Exalted Orb]" },
  { en: "Alone in the Darkness", pl: "Samotny w ciemności [Nagroda: Delve Item]" },
  { en: "Altered Perception", pl: "Zmieniony Perception [Nagroda: Simulacrum]" },
  { en: "Ambitious Obsession", pl: "Ambitna obsesja [Nagroda: Skittering Delirium Orb]" },
  { en: "Anarchy's Price", pl: "Anarchy's cena [Nagroda: Voltaxic Rift Corrupted]" },
  { en: "Apocalypse", pl: "Apocalypse [Nagroda: Eyes of the Greatwolf Item Level: 82 One Corruption Implicit]" },
  { en: "Arrogance of the Vaal", pl: "Arogancja Vaal [Nagroda: Item Two-Implicit Corrupted]" },
  { en: "Assassin's Favour", pl: "Assassin's Favour [Nagroda: Dagger]" },
  { en: "Assassin's Gift", pl: "Assassin's dar [Nagroda: Divinarius Two-Implicit Corrupted]" },
  { en: "Astral Protection", pl: "Astralna ochrona [Nagroda: Shield Shaper Item]" },
  { en: "Atziri's Arsenal", pl: "Arsenał Atziri [Nagroda: Weapon Corrupted]" },
  { en: "Audacity", pl: "Śmiałość [Nagroda: Doryani's Fist Corrupted]" },
  { en: "Auspicious Ambitions", pl: "Pomyślny ambicje [Nagroda: Experimented Item Item Level: 100 Double-Influenced Item]" },
  { en: "Avian Pursuit", pl: "Ptasi Pursuit [Nagroda: 1,500x Vivid Crystallised Lifeforce]" },
  { en: "Azure Rage", pl: "Azure Rage [Nagroda: Punishing Map Map Tier: 16]" },
  { en: "Azyran's Reward", pl: "Azyran's nagroda [Nagroda: Prismatic Jewel Corrupted]" },
  { en: "Baited Expectations", pl: "Przynęta oczekiwań [Nagroda: Fishing Item]" },
  { en: "Beauty Through Death", pl: "Piękno przez śmierć [Nagroda: Atziri's Reflection]" },
  { en: "Bijoux", pl: "Klejnoty [Nagroda: Cluster Jewel Item Level: 84]" },
  { en: "Birth of the Three", pl: "Narodziny z trzy [Nagroda: The Goddess Bound]" },
  { en: "Blessing of God", pl: "Błogosławieństwo z God [Nagroda: Elreon's Jewellery Item Level: 85]" },
  { en: "Blind Venture", pl: "Ślepe przedsięwzięcie [Nagroda: Ring Corrupted]" },
  { en: "Boon of Justice", pl: "Dobrodziejstwo z sprawiedliwość [Nagroda: Offering to the Goddess]" },
  { en: "Boon of the First Ones", pl: "Dobrodziejstwo z pierwszy jedni [Nagroda: Bestiary Item]" },
  { en: "Bound by Flame", pl: "Związany przez płomień [Nagroda: Level 21 Flame Link Quality: +20%]" },
  { en: "Boundless Realms", pl: "Bezgraniczny Realms [Nagroda: Map]" },
  { en: "Bowyer's Dream", pl: "Marzenie łuczarza [Nagroda: Six-Link Harbinger Bow Item Level: 91]" },
  { en: "Broken Promises", pl: "Złamany Promises [Nagroda: Diamond Ring Item Level: 87 Two-Implicit Synthesised]" },
  { en: "Broken Truce", pl: "Złamany Truce [Nagroda: Cold Iron Point]" },
  { en: "Brother's Gift", pl: "Brother's dar [Nagroda: 5x Divine Orb]" },
  { en: "Brother's Stash", pl: "Skarb brata [Nagroda: 5x Exalted Orb]" },
  { en: "Brotherhood in Exile", pl: "Braterstwo na wygnaniu [Nagroda: One With Nothing Corrupted]" },
  { en: "Brush, Paint and Palette", pl: "Pędzel farba i Palette [Nagroda: The Artist]" },
  { en: "Buried Treasure", pl: "Zakopany skarb [Nagroda: Sulphite Scarab]" },
  { en: "Burning Blood", pl: "Płonąca krew [Nagroda: Xoph's Blood Corrupted]" },
  { en: "Call to the First Ones", pl: "Wezwanie do Pierwszych [Nagroda: Tier 1 Talisman Corrupted]" },
  { en: "Cameria's Cut", pl: "Dział Camerii [Nagroda: Scarab]" },
  { en: "Cartographer's Delight", pl: "Zachwyt kartografa [Nagroda: Map Map Tier: 5]" },
  { en: "Chaotic Disposition", pl: "Chaotic Disposition [Nagroda: 5x Chaos Orb]" },
  { en: "Chasing Risk", pl: "Goniąc ryzyko [Nagroda: Synthesis Item]" },
  { en: "Checkmate", pl: "Checkmate [Nagroda: 76x Simulacrum Splinter]" },
  { en: "Choking Guilt", pl: "Dławiący wina [Nagroda: Stranglegasp]" },
  { en: "Costly Curio", pl: "Costly Curio [Nagroda: Item Double-Influenced Item]" },
  { en: "Council of Cats", pl: "Council z Cats [Nagroda: Farrul Item]" },
  { en: "Coveted Possession", pl: "Pożądana własność [Nagroda: 5x Regal Orb]" },
  { en: "Cursed Words", pl: "Cursed słowa [Nagroda: Maw of Mischief]" },
  { en: "Damnation", pl: "Potępienie [Nagroda: The Original Scripture Item Level: 83]" },
  { en: "Dark Dreams", pl: "Mroczne sny [Nagroda: Bone Helmet Elder Item]" },
  { en: "Dark Temptation", pl: "Mroczna pokusa [Nagroda: Obliteration]" },
  { en: "Darker Half", pl: "Darker Half [Nagroda: 5x Eldritch Chaos Orb]" },
  { en: "Deadly Joy", pl: "Deadly Joy [Nagroda: Torrent's Reclamation Two-Implicit Corrupted]" },
  { en: "Death", pl: "Death [Nagroda: Mon'tregul's Grasp]" },
  { en: "Deathly Designs", pl: "Zabójcze plany [Nagroda: Level 21 Trap Gem Quality: +23% Corrupted]" },
  { en: "Dementophobia", pl: "Dementophobia [Nagroda: 10x Delirium Orb]" },
  { en: "Demigod's Wager", pl: "Zakład półboga [Nagroda: Orb of Annulment]" },
  { en: "Desecrated Virtue", pl: "Zbezczeszczona cnota [Nagroda: Level 4 Exceptional Support Gem Quality: +23% Corrupted]" },
  { en: "Desperate Crusade", pl: "Desperacka krucjata [Nagroda: Prism Guardian]" },
  { en: "Destined to Crumble", pl: "Przeznaczony do rozpadu [Nagroda: Body Armour Item Level: 100]" },
  { en: "Dialla's Subjugation", pl: "Ujarzmienie Dialli [Nagroda: Support Gem Quality: +23% Corrupted]" },
  { en: "Disdain", pl: "Pogarda [Nagroda: Delirium Orb]" },
  { en: "Divine Beauty", pl: "Boskie piękno [Nagroda: 7x Divine Orb]" },
  { en: "Divine Justice", pl: "Boska sprawiedliwość [Nagroda: Grand Spectrum Corrupted]" },
  { en: "Doedre's Madness", pl: "Szaleństwo Doedre [Nagroda: Doedre Item]" },
  { en: "Doryani's Epiphany", pl: "Objawienie Doryaniego [Nagroda: Level 21 Transfigured Gem Quality: +20% Corrupted]" },
  { en: "Draped in Dreams", pl: "Draped w sny [Nagroda: Six-Link Astral Plate Item Level: 100 Influenced Item]" },
  { en: "Duality", pl: "Duality [Nagroda: Body Armour Item Level: 100 Double-Influenced Item]" },
  { en: "Dying Anguish", pl: "Umierająca udręka [Nagroda: Level 19 Transfigured Gem Quality: +19%]" },
  { en: "Dying Light", pl: "Umierający światło [Nagroda: Diamond Ring Item Level: 100 Shaper + Elder Item]" },
  { en: "Earth Drinker", pl: "Pijący ziemię [Nagroda: Granite Flask]" },
  { en: "Echoes of Love", pl: "Echa miłości [Nagroda: Fidelitas' Spike Two-Implicit Corrupted]" },
  { en: "Eldritch Perfection", pl: "Eldrytowy perfekcja [Nagroda: Item Item Level: 100 Perfect Eldritch Implicit Modifier]" },
  { en: "Emperor of Purity", pl: "Cesarz czystości [Nagroda: Six-Link Holy Chainmail Item Level: 60]" },
  { en: "Emperor's Luck", pl: "Szczęście cesarza [Nagroda: 5x Currency]" },
  { en: "Endless Night", pl: "Niekończący noc [Nagroda: Maloney's Mechanism]" },
  { en: "Etched in Blood", pl: "Etched w krew [Nagroda: Rigwald's Quills Two-Implicit Corrupted]" },
  { en: "Eternal Bonds", pl: "Wieczny Bonds [Nagroda: Replica Cortex]" },
  { en: "Ever-Changing", pl: "Ever Changing [Nagroda: 10x Orb of Unmaking]" },
  { en: "Fateful Meeting", pl: "Fateful Meeting [Nagroda: League-Specific Item Double-Influenced Item Item Level: 97 Two-Implicit Corrupted]" },
  { en: "Father's Love", pl: "Miłość ojca [Nagroda: Sublime Vision]" },
  { en: "Fire Of Unknown Origin", pl: "Ogień z Unknown pochodzenie [Nagroda: Nimis]" },
  { en: "Forbidden Power", pl: "Zakazana moc [Nagroda: Balefire Corrupted]" },
  { en: "Friendship", pl: "Friendship [Nagroda: Aul's Uprising]" },
  { en: "From Bone to Ashes", pl: "From Bone do popioły [Nagroda: Ngamahu's Flame Two-Implicit Corrupted]" },
  { en: "Further Invention", pl: "Further Invention [Nagroda: Helmet Double-Influenced Item Item Level: 100]" },
  { en: "Gemcutter's Mercy", pl: "Miłosierdzie szlifierza [Nagroda: Empower, Enhance or Enlighten]" },
  { en: "Gemcutter's Promise", pl: "Obietnica szlifierza [Nagroda: Gem Quality: +20%]" },
  { en: "Gift of Asenath", pl: "Dar Asenath [Nagroda: Asenath's Gentle Touch Two-Implicit Corrupted]" },
  { en: "Gift of the Gemling Queen", pl: "Dar Królowej Klejnotów [Nagroda: Level 20 Support Gem]" },
  { en: "Glimmer of Hope", pl: "Błysk nadziei [Nagroda: Gold Ring]" },
  { en: "Grave Knowledge", pl: "Grobowa wiedza [Nagroda: Summon Raging Spirit Quality: +20%]" },
  { en: "Guardian's Challenge", pl: "Wyzwanie strażnika [Nagroda: Shaper Guardian Map]" },
  { en: "Harmony of Souls", pl: "Harmonia z dusze [Nagroda: 9x Shrieking Essence]" },
  { en: "Haunting Shadows", pl: "Nawiedzające cienie [Nagroda: Metamorph Item]" },
  { en: "Her Mask", pl: "Jej maska [Nagroda: Sacrifice Fragment]" },
  { en: "Heterochromia", pl: "Heterochromia [Nagroda: Two-Stone Ring]" },
  { en: "History", pl: "Historia [Nagroda: 2x Hinekora's Lock]" },
  { en: "Home", pl: "Dom [Nagroda: Empower, Enhance or Enlighten Quality: +1-20%]" },
  { en: "Hope", pl: "Nadzieja [Nagroda: Prismatic Ring Corrupted]" },
  { en: "House of Mirrors", pl: "Dom zwierciadeł [Nagroda: Mirror of Kalandra]" },
  { en: "Hubris", pl: "Pycha [Nagroda: Ring]" },
  { en: "Humility", pl: "Pokora [Nagroda: Tabula Rasa]" },
  { en: "Hunter's Resolve", pl: "Determinacja łowcy [Nagroda: Bow]" },
  { en: "Hunter's Reward", pl: "Nagroda łowcy [Nagroda: The Taming]" },
  { en: "I See Brothers", pl: "Widzę braci [Nagroda: 2x Fracturing Orb]" },
  { en: "Immortal Resolve", pl: "Nieśmiertelna determinacja [Nagroda: Six-Linked Body Armour Influenced Item]" },
  { en: "Imperfect Memories", pl: "Niedoskonałe wspomnienia [Nagroda: Jewellery Item Level: 100 Three-Implicit Synthesised]" },
  { en: "Imperial Legacy", pl: "Cesarskie dziedzictwo [Nagroda: Six-Link Imperial Bow Item Level: 100]" },
  { en: "Jack in the Box", pl: "Pudełko z niespodzianką [Nagroda: Item]" },
  { en: "Judging Voices", pl: "Judging Voices [Nagroda: Forbidden Shako]" },
  { en: "Justified Ambition", pl: "Justified ambicja [Nagroda: Synthesis Map]" },
  { en: "Keeper's Corruption", pl: "Keeper's Corruption [Nagroda: Eldritch Bone Helmet (Concentrated Effect) Item Level: 89 Elder Item]" },
  { en: "Lachrymal Necrosis", pl: "Martwica łzowa [Nagroda: Jewel Implicit Modifier: Corrupted Blood cannot be inflicted on you Corrupted]" },
  { en: "Lantador's Lost Love", pl: "Utracona miłość Lantadora [Nagroda: Two-Stone Ring]" },
  { en: "Last Hope", pl: "Ostatnia nadzieja [Nagroda: Mortal Hope]" },
  { en: "Last Stand", pl: "Ostatni ostoja [Nagroda: The Surrender]" },
  { en: "Left to Fate", pl: "Pozostawiony do los [Nagroda: Map Map Tier: 16 Unidentified Corrupted]" },
  { en: "Lethean Temptation", pl: "Letejska pokusa [Nagroda: Nebulis]" },
  { en: "Light and Truth", pl: "Światło i prawda [Nagroda: Crystal Sceptre]" },
  { en: "Lingering Remnants", pl: "Pozostałe resztki [Nagroda: Vaal Temple Map Corrupted]" },
  { en: "Lonely Warrior", pl: "Samotny wojownik [Nagroda: Defiance of Destiny]" },
  { en: "Lost Worlds", pl: "Utracony Worlds [Nagroda: Map Map Tier: 15]" },
  { en: "Love Through Ice", pl: "Miłość przez lód [Nagroda: Unnatural Instinct Two-Implicit Corrupted]" },
  { en: "Loyalty", pl: "Lojalność [Nagroda: 3x Orb of Fusing]" },
  { en: "Luck of the Vaal", pl: "Szczęście z Vaal [Nagroda: Vaal Gauntlets Corrupted]" },
  { en: "Lucky Bastion", pl: "Lucky Bastion [Nagroda: Svalinn]" },
  { en: "Lucky Connections", pl: "Lucky połączenia [Nagroda: 20x Orb of Fusing]" },
  { en: "Lucky Deck", pl: "Lucky Deck [Nagroda: 10x Stacked Deck]" },
  { en: "Luminous Trove", pl: "Świetlisty skarb [Nagroda: Voices Corrupted]" },
  { en: "Lysah's Respite", pl: "Lysah's Respite [Nagroda: Agate Amulet Corrupted]" },
  { en: "Magnum Opus", pl: "Arcydzieło [Nagroda: Item Item Level: 100 Three-Implicit Synthesised]" },
  { en: "Man With Bear", pl: "Człowiek z niedźwiedź [Nagroda: Bestiary Scarab]" },
  { en: "Matryoshka", pl: "Matryoshka [Nagroda: Onyx Amulet Item Level: 85 Quality: +20% Influenced Item Four Anointments Incubating Talisman Item Corrupted]" },
  { en: "Mawr Blaidd", pl: "Mawr Blaidd [Nagroda: Eyes of the Greatwolf]" },
  { en: "Merciless Armament", pl: "Bezlitosne uzbrojenie [Nagroda: Merciless Two-Hand Weapon Item Level: 100]" },
  { en: "Might is Right", pl: "Siła to racja [Nagroda: Trypanon]" },
  { en: "Misery in Darkness", pl: "Niedola w ciemność [Nagroda: Shroud of the Lightless]" },
  { en: "Mitts", pl: "Mitts [Nagroda: Gloves]" },
  { en: "Monochrome", pl: "Monochromatyczność [Nagroda: Valdo's Puzzle Box]" },
  { en: "More is Never Enough", pl: "Więcej nigdy nie wystarcza [Nagroda: 4x Scarab]" },
  { en: "No Traces", pl: "Bez śladów [Nagroda: 30x Orb of Scouring]" },
  { en: "Nook's Crown", pl: "Korona Nooka [Nagroda: Bone Helmet Item Level: 100 Elder Item]" },
  { en: "One Last Score", pl: "Ostatni skok [Nagroda: Experimented Jewellery Item Level: 86]" },
  { en: "Outfoxed", pl: "Outfoxed [Nagroda: Veiled Exalted Orb]" },
  { en: "Parasitic Passengers", pl: "Parasitic Passengers [Nagroda: 10x Incubator Item Level: 84]" },
  { en: "Peaceful Moments", pl: "Spokojne chwile [Nagroda: Timeless Jewel]" },
  { en: "Perfection", pl: "Perfekcja [Nagroda: Jewellery Item Level: 100 Shaper Item]" },
  { en: "Poisoned Faith", pl: "Poisoned Faith [Nagroda: Arakaali's Fang Corrupted]" },
  { en: "Prejudice", pl: "Uprzedzenie [Nagroda: Item Influenced Item]" },
  { en: "Pride Before the Fall", pl: "Duma przed upadkiem [Nagroda: Kaom's Heart Corrupted]" },
  { en: "Pride of the First Ones", pl: "Duma Pierwszych [Nagroda: Farrul's Fur]" },
  { en: "Prometheus' Armoury", pl: "Zbrojownia Prometeusza [Nagroda: One-Hand Weapon Item Level: 100 Double-Influenced Item]" },
  { en: "Prosperity", pl: "Dobrobyt [Nagroda: Perandus' Gold Ring]" },
  { en: "Rain Tempter", pl: "Kusiciel deszczu [Nagroda: Map Map Tier: 6]" },
  { en: "Rain of Chaos", pl: "Deszcz chaosu [Nagroda: Chaos Orb]" },
  { en: "Rats", pl: "Szczury [Nagroda: Rat's Nest]" },
  { en: "Rebirth", pl: "Odrodzenie [Nagroda: Charan's Sword]" },
  { en: "Rebirth and Renewal", pl: "Odrodzenie i odnowa [Nagroda: Horned Scarab]" },
  { en: "Reckless Ambition", pl: "Reckless ambicja [Nagroda: Omeyocan]" },
  { en: "Reflection of the Heart", pl: "Odbicie z serce [Nagroda: Kalandra's Touch]" },
  { en: "Remembrance", pl: "Wspomnienie [Nagroda: Precursor's Emblem Corrupted]" },
  { en: "Runic Luck", pl: "Runiczne szczęście [Nagroda: 10x Vendor Refresh Currency]" },
  { en: "Sambodhi's Vow", pl: "Ślubowanie Sambodhiego [Nagroda: Mortal Fragment]" },
  { en: "Sambodhi's Wisdom", pl: "Mądrość Sambodhiego [Nagroda: Tabula Rasa Two-Implicit Corrupted]" },
  { en: "Scholar of the Seas", pl: "Uczony mórz [Nagroda: Mao Kun]" },
  { en: "Seven Years Bad Luck", pl: "Siedem lat nieszczęścia [Nagroda: Mirror Shard]" },
  { en: "Shard of Fate", pl: "Odłamek losu [Nagroda: Vivid Jewel]" },
  { en: "Silence and Frost", pl: "Silence i Frost [Nagroda: The Pandemonius]" },
  { en: "Society's Remorse", pl: "Skrucha społeczeństwa [Nagroda: 10x Orb of Alteration]" },
  { en: "Something Dark", pl: "Coś mrocznego [Nagroda: Blueprint Area Level: 83 Fully Revealed]" },
  { en: "Soul Quenched", pl: "Dusza Quenched [Nagroda: Disabled]" },
  { en: "Squandered Prosperity", pl: "Roztrwoniony dobrobyt [Nagroda: The Light of Meaning Corrupted]" },
  { en: "Struck by Lightning", pl: "Rażony piorunem [Nagroda: Electrocuting Jewellery Item Level: 76]" },
  { en: "Succor of the Sinless", pl: "Pomoc bezgrzesznych [Nagroda: Bottled Faith]" },
  { en: "Temperance", pl: "Umiarkowanie [Nagroda: Relic Item Level: 83]" },
  { en: "Terrible Secret of Space", pl: "Terrible sekret z Space [Nagroda: Level 21 Transfigured Golem Gem Quality: +23% Corrupted]" },
  { en: "The Academic", pl: "Akademik [Nagroda: Inspired Learning]" },
  { en: "The Admirer", pl: "Wielbiciel [Nagroda: Atziri Item]" },
  { en: "The Adventuring Spirit", pl: "Przygoda duch [Nagroda: Victario's Influence]" },
  { en: "The Aesthete", pl: "Esteta [Nagroda: Shavronne Item]" },
  { en: "The Apothecary", pl: "Aptekarz [Nagroda: Mageblood]" },
  { en: "The Archmage's Right Hand", pl: "Prawa ręka arcymaga [Nagroda: Glyphic Prophecy Wand Item Level: 100]" },
  { en: "The Arena Champion", pl: "Czempion areny [Nagroda: Map Map Tier: 12]" },
  { en: "The Army of Blood", pl: "Armia krwi [Nagroda: Bloodbond]" },
  { en: "The Artist", pl: "Artysta [Nagroda: Level 4 Enhance Corrupted]" },
  { en: "The Aspirant", pl: "Aspirant [Nagroda: Item Elevated Item Influenced Item]" },
  { en: "The Astromancer", pl: "Astromanta [Nagroda: The Eternity Shroud Two-Implicit Corrupted]" },
  { en: "The Avenger", pl: "Mściciel [Nagroda: Mjölner Corrupted]" },
  { en: "The Awakened", pl: "Awakened [Nagroda: Jewellery Item Level: 86 Double-Influenced Item]" },
  { en: "The Bargain", pl: "Transakcja [Nagroda: Disabled]" },
  { en: "The Battle Born", pl: "Zrodzony w bitwie [Nagroda: Axe]" },
  { en: "The Bear Woman", pl: "Niedźwiedź Woman [Nagroda: Fecund Ursine Pelt Warlord Item]" },
  { en: "The Beast", pl: "Bestia [Nagroda: Belly of the Beast]" },
  { en: "The Betrayal", pl: "Zdrada [Nagroda: Maligaro's Virtuosity]" },
  { en: "The Bitter Blossom", pl: "Gorzki kwiat [Nagroda: Level 21 Chaos Gem Quality: +23% Corrupted]" },
  { en: "The Blazing Fire", pl: "Blazing ogień [Nagroda: Chin Sol]" },
  { en: "The Blessing of Moosh", pl: "Błogosławieństwo z Moosh [Nagroda: Level 21 Transfigured Gem Corrupted]" },
  { en: "The Body", pl: "Ciało [Nagroda: Body Armour]" },
  { en: "The Bones", pl: "Kości [Nagroda: Level 21 Vaal Summon Skeletons Corrupted]" },
  { en: "The Brawny Battle Mage", pl: "Krzepki mag bitewny [Nagroda: Merciless Tornado Wand Item Level: 100]" },
  { en: "The Breach", pl: "Wyrwa [Nagroda: Breach Item]" },
  { en: "The Brittle Emperor", pl: "Brittle cesarz [Nagroda: Voll's Devotion Corrupted]" },
  { en: "The Cache", pl: "Cache [Nagroda: Jewellery]" },
  { en: "The Cacophony", pl: "Cacophony [Nagroda: 3x Deafening Essence]" },
  { en: "The Calling", pl: "Wezwanie [Nagroda: Beyond Item]" },
  { en: "The Card Sharp", pl: "Karciarz [Nagroda: Divination Scarab]" },
  { en: "The Carrion Crow", pl: "Czarnowron [Nagroda: Life Armour]" },
  { en: "The Cartographer", pl: "Kartograf [Nagroda: Disabled]" },
  { en: "The Cataclysm", pl: "Kataklizm [Nagroda: Level 21 Spell Gem Corrupted]" },
  { en: "The Catalyst", pl: "Catalyst [Nagroda: Vaal Orb]" },
  { en: "The Catch", pl: "Zdobycz [Nagroda: Fishing Rod Incubated Item Level: 99]" },
  { en: "The Celestial Justicar", pl: "Niebiański sędzia [Nagroda: Six-Link Astral Plate]" },
  { en: "The Celestial Stone", pl: "Niebiański kamień [Nagroda: Opal Ring Item Level: 100 Shaper Item]" },
  { en: "The Chains that Bind", pl: "Łańcuchy, które pętają [Nagroda: Six-Link Body Armour]" },
  { en: "The Cheater", pl: "Cheater [Nagroda: Disabled]" },
  { en: "The Chosen", pl: "Wybraniec [Nagroda: Skin of the Lords Corrupted]" },
  { en: "The Coming Storm", pl: "Nadchodząca burza [Nagroda: Lightning Coil]" },
  { en: "The Conduit", pl: "Przewód [Nagroda: Doryani's Fist]" },
  { en: "The Craving", pl: "Pragnienie [Nagroda: Unending Hunger]" },
  { en: "The Cursed King", pl: "Cursed król [Nagroda: Rigwald's Curse]" },
  { en: "The Damned", pl: "Potępieni [Nagroda: Soul Ripper]" },
  { en: "The Dapper Prodigy", pl: "Eleganckie cudowne dziecko [Nagroda: Six-Link Body Armour Item Level: 100]" },
  { en: "The Dark Mage", pl: "Mroczny mag [Nagroda: Six-Link Staff Item Level: 55]" },
  { en: "The Darkest Dream", pl: "Najciemniejszy sen [Nagroda: Severed in Sleep Corrupted]" },
  { en: "The Deal", pl: "Deal [Nagroda: Cartography Scarab]" },
  { en: "The Deceiver", pl: "Oszust [Nagroda: Belt of the Deceiver Corrupted]" },
  { en: "The Deep Ones", pl: "Głębinowi [Nagroda: Tidebreaker]" },
  { en: "The Demon", pl: "Demon [Nagroda: Headhunter Two-Implicit Corrupted]" },
  { en: "The Demoness", pl: "Demonica [Nagroda: Death's Hand]" },
  { en: "The Destination", pl: "Cel podróży [Nagroda: Watcher's Eye Two-Implicit Corrupted]" },
  { en: "The Devastator", pl: "Niszczyciel [Nagroda: Atziri's Disfavour Corrupted]" },
  { en: "The Doctor", pl: "Lekarz [Nagroda: Headhunter]" },
  { en: "The Doppelganger", pl: "Sobowtór [Nagroda: Mirror Arrow Quality: +20%]" },
  { en: "The Dragon", pl: "Smok [Nagroda: Coruscating Elixir]" },
  { en: "The Dragon's Heart", pl: "Serce smoka [Nagroda: Level 4 Empower Corrupted]" },
  { en: "The Dreamer", pl: "Marzyciel [Nagroda: Chayula Item]" },
  { en: "The Dreamland", pl: "Kraina snów [Nagroda: Poorjoy's Asylum]" },
  { en: "The Drunken Aristocrat", pl: "Drunken arystokrata [Nagroda: Divination Distillate]" },
  { en: "The Dungeon Master", pl: "Mistrz podziemi [Nagroda: Belt Double-Influenced Item]" },
  { en: "The Easy Stroll", pl: "Easy Stroll [Nagroda: Map Map Tier: 15 Modifiers: 8 Corrupted]" },
  { en: "The Eldritch Decay", pl: "Eldrytowy rozkład [Nagroda: Uber Elder Fragment]" },
  { en: "The Emptiness", pl: "Emptiness [Nagroda: Disabled]" },
  { en: "The Encroaching Darkness", pl: "Encroaching ciemność [Nagroda: Map Corrupted]" },
  { en: "The Endless Darkness", pl: "Niekończący ciemność [Nagroda: Voidforge]" },
  { en: "The Endurance", pl: "Wytrzymałość [Nagroda: Vivid Crimson Jewel]" },
  { en: "The Enforcer", pl: "Egzekutor [Nagroda: Spiked Gloves of the Conquest (Culling Strike) Item Level: 86 Warlord Item]" },
  { en: "The Enlightened", pl: "Oświecony [Nagroda: Level 3 Enlighten]" },
  { en: "The Enthusiasts", pl: "Entuzjaści [Nagroda: Victario's Influence Two-Implicit Corrupted]" },
  { en: "The Escape", pl: "Ucieczka [Nagroda: Seven-League Step]" },
  { en: "The Eternal War", pl: "Wieczna wojna [Nagroda: Timeless Jewel Two-Implicit Corrupted]" },
  { en: "The Ethereal", pl: "Eteryczność [Nagroda: Six-Link Vaal Regalia]" },
  { en: "The Everlasting", pl: "Everlasting [Nagroda: Originator Incarnation Item]" },
  { en: "The Explorer", pl: "Explorer [Nagroda: Map Corrupted]" },
  { en: "The Eye of Terror", pl: "Oko terroru [Nagroda: Mageblood Foulborn]" },
  { en: "The Eye of the Dragon", pl: "Oko smoka [Nagroda: Jewel Corrupted]" },
  { en: "The Fathomless Depths", pl: "Fathomless Depths [Nagroda: Lightpoacher]" },
  { en: "The Feast", pl: "Uczta [Nagroda: Romira's Banquet Corrupted]" },
  { en: "The Fiend", pl: "Bies [Nagroda: Headhunter Corrupted]" },
  { en: "The Finishing Touch", pl: "Wykończenie [Nagroda: 1x Fertile Catalyst]" },
  { en: "The Fishmonger", pl: "Sprzedawca ryb [Nagroda: Albino Rhoa Feather]" },
  { en: "The Fletcher", pl: "Łuczarz [Nagroda: Drillneck Corrupted]" },
  { en: "The Flora's Gift", pl: "Dar Flory [Nagroda: Five-Link Staff Item Level: 66]" },
  { en: "The Fool", pl: "Głupiec [Nagroda: 20x Orb of Chance]" },
  { en: "The Forbidden Fruit", pl: "Zakazany owoc [Nagroda: Uber Pinnacle Fragment]" },
  { en: "The Forgotten Treasure", pl: "Zapomniany skarb [Nagroda: Leather Belt Double-Influenced Item]" },
  { en: "The Formless Sea", pl: "Bezkształtne morze [Nagroda: Varunastra]" },
  { en: "The Forsaken", pl: "Forsaken [Nagroda: Umbilicus Immortalis]" },
  { en: "The Fortunate", pl: "Szczęściarz [Nagroda: 2x Divine Orb]" },
  { en: "The Forward Gaze", pl: "Spojrzenie w przód [Nagroda: Replica Item]" },
  { en: "The Fox", pl: "Lis [Nagroda: Level 20 Gem]" },
  { en: "The Fox in the Brambles", pl: "Lis w jeżynach [Nagroda: Bramblejack Two-Implicit Corrupted]" },
  { en: "The Gambler", pl: "Hazardzista [Nagroda: Divination Card]" },
  { en: "The Garish Power", pl: "Jaskrawa moc [Nagroda: Jewel]" },
  { en: "The Gemcutter", pl: "Szlifierz [Nagroda: Gemcutter's Prism]" },
  { en: "The Gentleman", pl: "Dżentelmen [Nagroda: Sword Corrupted]" },
  { en: "The Gladiator", pl: "Gladiator [Nagroda: Nightmare Bascinet]" },
  { en: "The Golden Era", pl: "Złota era [Nagroda: Flaring Eclipse Staff Item Level: 100]" },
  { en: "The Greatest Intentions", pl: "Najwspanialsze intencje [Nagroda: The Saviour Two-Implicit Corrupted]" },
  { en: "The Gulf", pl: "Zatoka [Nagroda: Thread of Hope Two-Implicit Corrupted]" },
  { en: "The Hale Heart", pl: "Hale serce [Nagroda: Item Item Level: 100 Elder Item]" },
  { en: "The Harvester", pl: "Żniwiarz [Nagroda: The Harvest]" },
  { en: "The Hermit", pl: "Pustelnik [Nagroda: Lifesprig]" },
  { en: "The Heroic Shot", pl: "Heroic Shot [Nagroda: 17x Chromatic Orb]" },
  { en: "The Hive of Knowledge", pl: "Hive z wiedza [Nagroda: Machina Mitts Two-Implicit Corrupted]" },
  { en: "The Hoarder", pl: "Zbieracz [Nagroda: Exalted Orb]" },
  { en: "The Hook", pl: "Hak [Nagroda: Level 21 Transfigured Gem Quality: +23% Corrupted]" },
  { en: "The Hunger", pl: "Hunger [Nagroda: Taste of Hate]" },
  { en: "The Immortal", pl: "Nieśmiertelny [Nagroda: House of Mirrors]" },
  { en: "The Incantation", pl: "Inkantacja [Nagroda: The Whispering Ice]" },
  { en: "The Innocent", pl: "Innocent [Nagroda: 40x Orb of Regret]" },
  { en: "The Inoculated", pl: "Zaszczepiony [Nagroda: Seraphim's Armour]" },
  { en: "The Insane Cat", pl: "Szalony kot [Nagroda: Mageblood Item Level: 84 Corrupted]" },
  { en: "The Insatiable", pl: "Insatiable [Nagroda: The Harvest Corrupted]" },
  { en: "The Inventor", pl: "Wynalazca [Nagroda: 10x Vaal Orb]" },
  { en: "The Jester", pl: "Błazen [Nagroda: Merciless One-Hand Weapon Item Level: 100]" },
  { en: "The Jeweller's Boon", pl: "Dobrodziejstwo jubilera [Nagroda: Five-Linked Body Armour Influenced Item]" },
  { en: "The Journalist", pl: "Journalist [Nagroda: Helmet Double-Veiled Item]" },
  { en: "The Journey", pl: "Journey [Nagroda: Journey Tattoo]" },
  { en: "The King's Blade", pl: "Ostrze króla [Nagroda: Bloodthirsty Eternal Sword Item Level: 66]" },
  { en: "The King's Heart", pl: "Serce króla [Nagroda: Kaom's Heart]" },
  { en: "The Lake", pl: "Jezioro [Nagroda: Reflecting Mist]" },
  { en: "The Landing", pl: "Lądowanie [Nagroda: Disabled]" },
  { en: "The Last Laugh", pl: "Ostatni śmiech [Nagroda: Replica Dragonfang's Flight Corrupted]" },
  { en: "The Last One Standing", pl: "Ostatni na placu boju [Nagroda: Atziri's Disfavour]" },
  { en: "The Last Supper", pl: "Ostatnia wieczerza [Nagroda: Bino's Kitchen Knife]" },
  { en: "The Leviathan", pl: "Leviathan [Nagroda: Maven Item Two-Implicit Corrupted]" },
  { en: "The Lich", pl: "Lisz [Nagroda: Midnight Bargain Corrupted]" },
  { en: "The Life Thief", pl: "Życie Thief [Nagroda: Zerphi's Heart]" },
  { en: "The Lion", pl: "Lew [Nagroda: Lioneye Item]" },
  { en: "The Long Con", pl: "Długa gra [Nagroda: Elderslayer's Exalted Orb]" },
  { en: "The Long Watch", pl: "Długi Watch [Nagroda: The Fourth Vow]" },
  { en: "The Lord in Black", pl: "Pan w czerni [Nagroda: Ring of Bameth Item Level: 83]" },
  { en: "The Lord of Celebration", pl: "Władca świętowania [Nagroda: Sceptre of Celebration Shaper Item]" },
  { en: "The Lover", pl: "Kochanek [Nagroda: Jewellery Item Level: 79]" },
  { en: "The Lunaris Priestess", pl: "Kapłanka Lunaris [Nagroda: Sire of Shards]" },
  { en: "The Mad King", pl: "Szalony król [Nagroda: Vaal Aspect]" },
  { en: "The Magma Crab", pl: "Krab magmowy [Nagroda: Level 21 Vaal Molten Shell Corrupted]" },
  { en: "The Master", pl: "Mistrz [Nagroda: Disabled]" },
  { en: "The Master Artisan", pl: "Mistrz rzemiosła [Nagroda: 20x Quality Currency]" },
  { en: "The Mayor", pl: "Burmistrz [Nagroda: The Light of Meaning]" },
  { en: "The Mercenary", pl: "Najemnik [Nagroda: Shield Corrupted]" },
  { en: "The Messenger", pl: "Posłaniec [Nagroda: Harbinger Item]" },
  { en: "The Metalsmith's Gift", pl: "Metalsmith's dar [Nagroda: Prismatic Ring]" },
  { en: "The Mind's Eyes", pl: "Oczy umysłu [Nagroda: Astral Projector]" },
  { en: "The Miracle", pl: "Cud [Nagroda: Awakened Exceptional Gem]" },
  { en: "The Mountain", pl: "Góra [Nagroda: Jewel of Potency]" },
  { en: "The Nurse", pl: "Pielęgniarka [Nagroda: The Doctor]" },
  { en: "The Oath", pl: "Przemoc / Przysięga [Nagroda: Death's Oath]" },
  { en: "The Obscured", pl: "Przesłonięty [Nagroda: Disabled]" },
  { en: "The Offering", pl: "Ofiara [Nagroda: Shavronne's Wrappings]" },
  { en: "The Offspring", pl: "Potomstwo [Nagroda: Ryslatha's Coil]" },
  { en: "The Old Man", pl: "Starzec [Nagroda: Fishing Rod Two-Implicit Corrupted]" },
  { en: "The One That Got Away", pl: "Jeden That Got daleko [Nagroda: Replica Bated Breath]" },
  { en: "The One With All", pl: "Ten ze wszystkim [Nagroda: Le Heup of All Corrupted]" },
  { en: "The Opulent", pl: "Bogaty [Nagroda: Ring Item Level: 100]" },
  { en: "The Pack Leader", pl: "Wataha przywódca [Nagroda: Alpha's Howl]" },
  { en: "The Pact", pl: "Pakt [Nagroda: Pledge of Hands]" },
  { en: "The Patient", pl: "Pacjent [Nagroda: The Nurse]" },
  { en: "The Penitent", pl: "Pokutnik [Nagroda: Unset Ring]" },
  { en: "The Poet", pl: "Poeta [Nagroda: Blood of Corruption Corrupted]" },
  { en: "The Polymath", pl: "Polihistor [Nagroda: Astramentis]" },
  { en: "The Porcupine", pl: "Porcupine (Jozin) [Nagroda: Six-Link Short Bow Item Level: 50]" },
  { en: "The Price of Devotion", pl: "Cena oddania [Nagroda: Mageblood Quality: +20% Two-Implicit Corrupted]" },
  { en: "The Price of Loyalty", pl: "Cena z lojalność [Nagroda: Skin of the Loyal Item Level: 25 Two-Implicit Corrupted]" },
  { en: "The Price of Prescience", pl: "Cena przeczucia [Nagroda: Vaal Temple Map Delirium: 100% Corrupted]" },
  { en: "The Price of Protection", pl: "Cena ochrony [Nagroda: Elder Guardian Occupied Map Modifiers: 8 Corrupted]" },
  { en: "The Primordial", pl: "Pierwotny [Nagroda: Jewel Primordial]" },
  { en: "The Prince of Darkness", pl: "Książę ciemności [Nagroda: Elegant Hubris]" },
  { en: "The Professor", pl: "Profesor [Nagroda: The Putrid Cloister]" },
  { en: "The Progeny of Lunaris", pl: "Potomstwo Lunaris [Nagroda: Dying Sun]" },
  { en: "The Puzzle", pl: "Układanka [Nagroda: Disabled]" },
  { en: "The Queen", pl: "Królowa [Nagroda: Atziri's Acuity]" },
  { en: "The Rabbit's Foot", pl: "Rabbit's Foot [Nagroda: 10x Incursion Vial]" },
  { en: "The Rabid Rhoa", pl: "Rabid Rhoa [Nagroda: Malicious Gemini Claw Item Level: 83]" },
  { en: "The Realm", pl: "Królestwo [Nagroda: Portal Quality: +1-20%]" },
  { en: "The Return of the Rat", pl: "Powrót szczura [Nagroda: Tavukai]" },
  { en: "The Risk", pl: "Ryzyko [Nagroda: Ventor's Gamble]" },
  { en: "The Rite of Elements", pl: "Rytuał żywiołów [Nagroda: Level 21 Golem Gem Corrupted]" },
  { en: "The Road to Power", pl: "Droga do władzy [Nagroda: Runic One-Hand Weapon Item Level: 100]" },
  { en: "The Rusted Bard", pl: "Zardzewiały bard [Nagroda: 4x Tainted Mythic Orb]" },
  { en: "The Ruthless Ceinture", pl: "Ruthless Ceinture [Nagroda: Meginord's Girdle Corrupted]" },
  { en: "The Sacrifice", pl: "Ofiara [Nagroda: Six-Link Sacrificial Garb Item Level: 100]" },
  { en: "The Saint's Treasure", pl: "Saint's skarb [Nagroda: 2x Exalted Orb]" },
  { en: "The Samurai's Eye", pl: "Oko samuraja [Nagroda: Watcher's Eye]" },
  { en: "The Scarred Meadow", pl: "Scarred Meadow [Nagroda: Wake of Destruction]" },
  { en: "The Scavenger", pl: "Padlinożerca [Nagroda: Carcass Jack]" },
  { en: "The Scholar", pl: "Uczony [Nagroda: 40x Scroll of Wisdom]" },
  { en: "The Scout", pl: "Scout [Nagroda: 7x Exalted Orb]" },
  { en: "The Seeker", pl: "Poszukiwacz [Nagroda: 3x Orb of Annulment]" },
  { en: "The Sephirot", pl: "Sefirot [Nagroda: 10x Divine Orb]" },
  { en: "The Shepherd's Sandals", pl: "Shepherd's Sandals [Nagroda: Boots Item Level: 100 Two-Implicit Corrupted]" },
  { en: "The Shieldbearer", pl: "Tarczownik [Nagroda: The Squire]" },
  { en: "The Shortcut", pl: "Skrót [Nagroda: Quicksilver Flask of the Cheetah Item Level: 100]" },
  { en: "The Side Quest", pl: "Zadanie poboczne [Nagroda: Incarnation Echo]" },
  { en: "The Sigil", pl: "Sygnet [Nagroda: Unassailable Amulet]" },
  { en: "The Silly Boy", pl: "Głupi chłopiec [Nagroda: 6x Horned Scarab]" },
  { en: "The Siren", pl: "Syrena [Nagroda: The Whispering Ice Corrupted]" },
  { en: "The Skeleton", pl: "Szkielet [Nagroda: Level 1 Summon Skeletons Quality: +23% Corrupted]" },
  { en: "The Slumbering Beast", pl: "Śpiąca bestia [Nagroda: Hinekora's Lock]" },
  { en: "The Soul", pl: "Dusza [Nagroda: Soul Taker]" },
  { en: "The Spark and the Flame", pl: "Iskra i płomień [Nagroda: Berek's Respite]" },
  { en: "The Spoiled Prince", pl: "Rozpieszczony książę [Nagroda: Dictator's Prophecy Wand Item Level: 100]" },
  { en: "The Standoff", pl: "Pat [Nagroda: Rustic Sash]" },
  { en: "The Stormcaller", pl: "Wzywający burzę [Nagroda: Agnerod Staff]" },
  { en: "The Strategist", pl: "Strategist [Nagroda: Inspired Learning Corrupted]" },
  { en: "The Summoner", pl: "Przyzywacz [Nagroda: Minion Gem Quality: +20%]" },
  { en: "The Sun", pl: "Słońce [Nagroda: Rise of the Phoenix]" },
  { en: "The Surgeon", pl: "Chirurg [Nagroda: Surgeon's Flask]" },
  { en: "The Surveyor", pl: "Geodeta [Nagroda: Map Map Tier: 14]" },
  { en: "The Survivalist", pl: "Survivalista [Nagroda: 7x Orb of Alchemy]" },
  { en: "The Sustenance", pl: "Pożywienie [Nagroda: Disabled]" },
  { en: "The Sword King's Salute", pl: "Salut króla mieczy [Nagroda: Daresso's Salute]" },
  { en: "The Thaumaturgist", pl: "Thaumaturg [Nagroda: Shavronne's Revelation Corrupted]" },
  { en: "The Throne", pl: "Tron [Nagroda: Kaom's Roots Corrupted]" },
  { en: "The Tinkerer's Table", pl: "Stół majsterkowicza [Nagroda: 5x Fossil]" },
  { en: "The Tireless Extractor", pl: "Niestrudzony Extractor [Nagroda: 10x Oil]" },
  { en: "The Tower", pl: "Wieża [Nagroda: Staff]" },
  { en: "The Traitor", pl: "Zdrajca [Nagroda: Wand Corrupted]" },
  { en: "The Transformation", pl: "Transformacja [Nagroda: Tainted Mythic Orb]" },
  { en: "The Trial", pl: "Próba [Nagroda: Map Map Tier: 15 Corrupted]" },
  { en: "The Tumbleweed", pl: "Tumbleweed [Nagroda: Diamond Ring of Redemption Item Level: 100 Redeemer Item]" },
  { en: "The Twilight Moon", pl: "Zmierzch księżyc [Nagroda: The Twilight Temple]" },
  { en: "The Twins", pl: "Bliźnięta [Nagroda: Gemini Claw of Celebration Item Level: 83]" },
  { en: "The Tyrant", pl: "Tyran [Nagroda: Merciless Weapon Item Level: 100]" },
  { en: "The Undaunted", pl: "Nieustraszony [Nagroda: Nemesis Item Corrupted]" },
  { en: "The Undisputed", pl: "Bezsporny [Nagroda: Merciless Vaal Axe Item Level: 100 Elder Item]" },
  { en: "The Unexpected Prize", pl: "Nieoczekiwany Prize [Nagroda: Attribute Transforming Jewel Corrupted]" },
  { en: "The Union", pl: "Unia [Nagroda: 10x Gemcutter's Prism]" },
  { en: "The Valkyrie", pl: "Walkiria [Nagroda: Nemesis Item]" },
  { en: "The Valley of Steel Boxes", pl: "Dolina z stal Boxes [Nagroda: Disabled]" },
  { en: "The Vast", pl: "Rozległy [Nagroda: Song of the Sirens]" },
  { en: "The Visionary", pl: "Visionary [Nagroda: Lioneye's Vision]" },
  { en: "The Void", pl: "Pustka [Nagroda: ]" },
  { en: "The Warden", pl: "Strażnik [Nagroda: Amulet Corrupted]" },
  { en: "The Warlord", pl: "Wódz [Nagroda: Six-Link Coronal Maul Item Level: 83]" },
  { en: "The Watcher", pl: "Obserwator [Nagroda: Crown of Eyes]" },
  { en: "The Web", pl: "Sieć [Nagroda: Weapon of Crafting]" },
  { en: "The Wedding Gift", pl: "Prezent ślubny [Nagroda: Arakaali's Fang]" },
  { en: "The White Knight", pl: "Biały rycerz [Nagroda: Six-Link Astral Plate Item Level: 100 Crusader Item]" },
  { en: "The Whiteout", pl: "Śnieżyca [Nagroda: Cospri's Malice]" },
  { en: "The Wilted Rose", pl: "Zwiędła róża [Nagroda: Level 21 Aura Gem Corrupted]" },
  { en: "The Wind", pl: "Wiatr [Nagroda: Windripper]" },
  { en: "The Witch", pl: "Czarownica [Nagroda: Kiara's Determination]" },
  { en: "The Wolf", pl: "Wilk [Nagroda: Rigwald Item]" },
  { en: "The Wolf's Legacy", pl: "Dziedzictwo wilka [Nagroda: Vaults of Atziri]" },
  { en: "The Wolf's Shadow", pl: "Cień wilka [Nagroda: Hyaon's Fury]" },
  { en: "The Wolven King's Bite", pl: "Wilcza King's ugryzienie [Nagroda: Rigwald's Quills]" },
  { en: "The Wolverine", pl: "Wolverine [Nagroda: Claw Corrupted]" },
  { en: "The World Eater", pl: "Pożeracz światów [Nagroda: Starforge]" },
  { en: "The Wrath", pl: "Gniew [Nagroda: 10x Chaos Orb]" },
  { en: "The Wretched", pl: "Nędzarz [Nagroda: Belt]" },
  { en: "Thirst for Knowledge", pl: "Pragnienie wiedzy [Nagroda: Gluttony]" },
  { en: "Three Faces in the Dark", pl: "Trzy twarze w ciemności [Nagroda: 3x Chaos Orb]" },
  { en: "Three Voices", pl: "Trzy Voices [Nagroda: 3x Essence]" },
  { en: "Thunderous Skies", pl: "Thunderous Skies [Nagroda: Storm Cloud]" },
  { en: "Time-Lost Relic", pl: "Zaginiona w czasie relikwia [Nagroda: League-Specific Item]" },
  { en: "Toxic Tidings", pl: "Toxic Tidings [Nagroda: Dendrobate Two-Implicit Corrupted]" },
  { en: "Tranquillity", pl: "Spokój [Nagroda: Voltaxic Rift]" },
  { en: "Treasure Hunter", pl: "Poszukiwacz skarbów [Nagroda: Vaults of Atziri Corrupted]" },
  { en: "Treasures of the Vaal", pl: "Treasures z Vaal [Nagroda: Vaal Jewel Two-Implicit Corrupted]" },
  { en: "Triskaidekaphobia", pl: "Triskaidekaphobia [Nagroda: Map Map Tier: 13 Delirium: 100% Modifiers: 8 Corrupted]" },
  { en: "Turn the Other Cheek", pl: "Nadstaw drugi policzek [Nagroda: Pacifism Corrupted]" },
  { en: "Unchained", pl: "Oswobodzony [Nagroda: Facebreaker Two-Implicit Corrupted]" },
  { en: "Underground Forest", pl: "Podziemny las [Nagroda: 10x Grand Eldritch Ichor]" },
  { en: "Unrequited Love", pl: "Nieodwzajemniona miłość [Nagroda: 19x Mirror Shard]" },
  { en: "Vanity", pl: "Próżność [Nagroda: Tabula Rasa Corrupted]" },
  { en: "Vile Power", pl: "Vile moc [Nagroda: Doomfletch]" },
  { en: "Vinia's Token", pl: "Symbol Vinii [Nagroda: 10x Orb of Regret]" },
  { en: "Void of the Elements", pl: "Pustka żywiołów [Nagroda: Overpowering Opal Ring Item Level: 100 Elder Item]" },
  { en: "Volatile Power", pl: "Niestabilna moc [Nagroda: Vaal Gem Quality: +20% Corrupted]" },
  { en: "Wealth and Power", pl: "Bogactwo i władza [Nagroda: Level 4 Enlighten Corrupted]" },
  { en: "When Currents Blaze", pl: "When Currents Blaze [Nagroda: Stormfire Quality: +20% Corrupted]" },
  { en: "Who Asked", pl: "Who pytany [Nagroda: Dictator's Weapon Item Level: 83 Fractured]" },
  { en: "Winter's Embrace", pl: "Uścisk zimy [Nagroda: Circle of Fear Three-Implicit Synthesised]" },
];
