var WORDS_RESIDENTEVIL = [
  { en: "survival horror", pl: "horror przetrwania" },
  { en: "biohazard", pl: "biozagrożenie" },
  { en: "zombie", pl: "zombie" },
  { en: "mutant", pl: "mutant" },
  { en: "virus", pl: "wirus" },
  { en: "t-virus", pl: "T-Virus" },
  { en: "g-virus", pl: "G-Virus" },
  { en: "uroboros", pl: "uroboros" },
  { en: "las plagas", pl: "las plagas" },
  { en: "mold", pl: "pleśń" },
  { en: "megamycete", pl: "megamycete" },
  { en: "progenitor virus", pl: "wirus progenitor" },
  { en: "c-virus", pl: "C-Virus" },
  { en: "outbreak", pl: "epidemia" },
  { en: "infection", pl: "infekcja" },
  { en: "contamination", pl: "skażenie" },
  { en: "pandemic", pl: "pandemia" },
  { en: "quarantine", pl: "kwarantanna" },
  { en: "tyrant", pl: "tyrant" },
  { en: "nemesis", pl: "nemesis" },
  { en: "licker", pl: "liżący" },
  { en: "hunter", pl: "łowca" },
  { en: "cerberus", pl: "cerber" },
  { en: "crimson head", pl: "karmazynowa głowa" },
  { en: "regenerator", pl: "regenerator" },
  { en: "iron maiden", pl: "żelazna dziewica" },
  { en: "garrador", pl: "garrador" },
  { en: "verdugo", pl: "verdugo" },
  { en: "el gigante", pl: "el gigante" },
  { en: "dr salvador", pl: "dr salvador" },
  { en: "chainsaw ganado", pl: "ganado z piłą" },
  { en: "molded", pl: "uformowany" },
  { en: "lycan", pl: "likantrop" },
  { en: "eveline", pl: "eveline" },
  { en: "lady dimitrescu", pl: "lady dimitrescu" },
  { en: "heisenberg", pl: "heisenberg" },
  { en: "fish man", pl: "człowiek ryba" },
  { en: "boss fight", pl: "walka z bossem" },
  { en: "bio organic weapon", pl: "broń bioorganiczna" },
  { en: "bow", pl: "BOW" },
  { en: "bioterrorism", pl: "bioterroryzm" },
  { en: "mutagenic", pl: "mutagenny" },
  { en: "viral", pl: "wirusowy" },
  { en: "genetic", pl: "genetyczny" },
  { en: "bioengineering", pl: "bioinżynieria" },
  { en: "mutation", pl: "mutacja" },
  { en: "parasite", pl: "pasożyt" },
  { en: "host", pl: "gospodarz" },
  { en: "antibody", pl: "przeciwciało" },
  { en: "antidote", pl: "odtrutka" },
  { en: "vaccine", pl: "szczepionka" },
  { en: "serum", pl: "surowica" },
  { en: "synthesis", pl: "synteza" },
  { en: "laboratory", pl: "laboratorium" },
  { en: "research facility", pl: "placówka badawcza" },
  { en: "specimen", pl: "próbka" },
  { en: "experiment", pl: "eksperyment" },
  { en: "chris redfield", pl: "chris redfield" },
  { en: "jill valentine", pl: "jill valentine" },
  { en: "leon kennedy", pl: "leon kennedy" },
  { en: "claire redfield", pl: "claire redfield" },
  { en: "albert wesker", pl: "albert wesker" },
  { en: "ada wong", pl: "ada wong" },
  { en: "ethan winters", pl: "ethan winters" },
  { en: "mia winters", pl: "mia winters" },
  { en: "grace ashcroft", pl: "grace ashcroft" },
  { en: "rebecca chambers", pl: "rebecca chambers" },
  { en: "barry burton", pl: "barry burton" },
  { en: "sherry birkin", pl: "sherry birkin" },
  { en: "jake muller", pl: "jake muller" },
  { en: "carlos oliveira", pl: "carlos oliveira" },
  { en: "umbrella corporation", pl: "korporacja umbrella" },
  { en: "stars", pl: "S.T.A.R.S." },
  { en: "bsaa", pl: "BSAA" },
  { en: "rpd", pl: "RPD" },
  { en: "los iluminados", pl: "los iluminados" },
  { en: "the connections", pl: "the connections" },
  { en: "neo umbrella", pl: "neo umbrella" },
  { en: "raccoon city", pl: "raccoon city" },
  { en: "spencer mansion", pl: "rezydencja spencera" },
  { en: "raccoon city police department", pl: "komenda policji w raccoon city" },
  { en: "underground lab", pl: "podziemne laboratorium" },
  { en: "baker ranch", pl: "ranczo bakerów" },
  { en: "village of shadows", pl: "wioska cieni" },
  { en: "castle dimitrescu", pl: "zamek dimitrescu" },
  { en: "rockfort island", pl: "wyspa rockfort" },
  { en: "antarctica base", pl: "baza na antarktydzie" },
  { en: "kijuju", pl: "kijuju" },
  { en: "lanshiang", pl: "lanshiang" },
  { en: "save room", pl: "pokój zapisu" },
  { en: "typewriter", pl: "maszyna do pisania" },
  { en: "ink ribbon", pl: "taśma barwiąca" },
  { en: "attache case", pl: "aktówka" },
  { en: "green herb", pl: "zielone ziele" },
  { en: "red herb", pl: "czerwone ziele" },
  { en: "blue herb", pl: "niebieskie ziele" },
  { en: "first aid spray", pl: "spray pierwszej pomocy" },
  { en: "herb mix", pl: "mieszanka ziół" },
  { en: "handgun", pl: "pistolet" },
  { en: "magnum", pl: "magnum" },
  { en: "grenade launcher", pl: "granatnik" },
  { en: "shotgun", pl: "strzelba" },
  { en: "assault rifle", pl: "karabin szturmowy" },
  { en: "sniper rifle", pl: "karabin snajperski" },
  { en: "knife", pl: "nóż" },
  { en: "combat knife", pl: "nóż bojowy" },
  { en: "machete", pl: "maczeta" },
  { en: "samurai edge", pl: "samurai edge" },
  { en: "lightning hawk", pl: "lightning hawk" },
  { en: "matilda", pl: "matilda" },
  { en: "flash grenade", pl: "granat błyskowy" },
  { en: "hand grenade", pl: "granat ręczny" },
  { en: "mine launcher", pl: "wyrzutnia min" },
  { en: "rocket launcher", pl: "wyrzutnia rakiet" },
  { en: "flamethrower", pl: "miotacz ognia" },
  { en: "crossbow", pl: "kusza" },
  { en: "tank controls", pl: "sterowanie czołgowe" },
  { en: "fixed camera", pl: "stała kamera" },
  { en: "over the shoulder", pl: "zza ramienia" },
  { en: "first person view", pl: "widok pierwszoosobowy" },
  { en: "third person", pl: "trzecioosobowy" },
  { en: "puzzle", pl: "zagadka" },
  { en: "inventory", pl: "ekwipunek" },
  { en: "item box", pl: "skrzynka na przedmioty" },
  { en: "ammunition", pl: "amunicja" },
  { en: "reload", pl: "przeładowanie" },
  { en: "aiming", pl: "celowanie" },
  { en: "headshot", pl: "strzał w głowę" },
  { en: "critical hit", pl: "trafienie krytyczne" },
  { en: "melee attack", pl: "atak wręcz" },
  { en: "quick turn", pl: "szybki obrót" },
  { en: "dodge", pl: "unik" },
  { en: "block", pl: "blok" },
  { en: "parry", pl: "parada" },
  { en: "survivor", pl: "ocalały" },
  { en: "zombie outbreak", pl: "epidemia zombie" },
  { en: "undead", pl: "nieumarły" },
  { en: "horror", pl: "horror" },
  { en: "terror", pl: "terror" },
  { en: "dread", pl: "strach" },
  { en: "nightmare", pl: "koszmar" },
  { en: "macabre", pl: "makabryczny" },
  { en: "gruesome", pl: "makabryczny" },
  { en: "grotesque", pl: "groteskowy" },
  { en: "eerie", pl: "niesamowity" },
  { en: "ominous", pl: "złowrogi" },
  { en: "foreboding", pl: "złowróżbny" },
  { en: "gritty", pl: "surowy" },
  { en: "darkness", pl: "ciemność" },
  { en: "flashlight", pl: "latarka" },
  { en: "corridor", pl: "korytarz" },
  { en: "mansion", pl: "rezydencja" },
  { en: "basement", pl: "piwnica" },
  { en: "attic", pl: "strych" },
  { en: "courtyard", pl: "dziedziniec" },
  { en: "sewer", pl: "kanalizacja" },
  { en: "catacombs", pl: "katakumby" },
  { en: "crypt", pl: "krypta" },
  { en: "graveyard", pl: "cmentarz" },
  { en: "hospital", pl: "szpital" },
  { en: "police station", pl: "komisariat" },
  { en: "factory", pl: "fabryka" },
  { en: "village", pl: "wioska" },
  { en: "castle", pl: "zamek" },
  { en: "clock tower", pl: "wieża zegarowa" },
  { en: "mercenaries", pl: "najemnicy" },
  { en: "raid mode", pl: "tryb najazdu" },
  { en: "survivor mode", pl: "tryb ocalałego" },
  { en: "nightmare mode", pl: "tryb koszmaru" },
  { en: "inferno mode", pl: "tryb piekielny" },
  { en: "professional mode", pl: "tryb profesjonalny" },
  { en: "speedrun", pl: "szybkie przejście" },
  { en: "achievement", pl: "osiągnięcie" },
  { en: "unlockable", pl: "do odblokowania" },
  { en: "bonus weapon", pl: "broń bonusowa" },
  { en: "costume", pl: "kostium" },
  { en: "new game plus", pl: "nowa gra plus" },
  { en: "re engine", pl: "RE Engine" },
  { en: "capcom", pl: "capcom" },
  { en: "shinji mikami", pl: "shinji mikami" },
  { en: "biohazard", pl: "biohazard" },
  { en: "resident evil 4", pl: "resident evil 4" },
  { en: "resident evil 7", pl: "resident evil 7" },
  { en: "resident evil village", pl: "resident evil village" },
  { en: "resident evil requiem", pl: "resident evil requiem" },
  { en: "remake", pl: "remake" },
  { en: "live action film", pl: "film aktorski" },
  { en: "animated film", pl: "film animowany" },
  { en: "infinite darkness", pl: "infinite darkness" },
  { en: "degeneration", pl: "degeneracja" },
  { en: "damnation", pl: "potępienie" },
  { en: "vendetta", pl: "vendetta" },
  { en: "death island", pl: "wyspa śmierci" },
];
