var WORDS_7DAYS = [
  { en: "abandoned", pl: "porzucony" },
  { en: "aberration", pl: "aberracja" },
  { en: "abomination", pl: "ohyda" },
  { en: "abyss", pl: "otchłań" },
  { en: "accelerator", pl: "przyspiesznik" },
  { en: "accumulator", pl: "akumulator" },
  { en: "adhesive", pl: "klej" },
  { en: "adrenaline", pl: "adrenalina" },
  { en: "affliction", pl: "dolegliwość" },
  { en: "agility", pl: "zwinność" },
  { en: "agriculture", pl: "rolnictwo" },
  { en: "ailment", pl: "dolegliwość" },
  { en: "alloy", pl: "stop" },
  { en: "aluminum", pl: "aluminium" },
  { en: "ambush", pl: "zasadzka" },
  { en: "ammunition", pl: "amunicja" },
  { en: "amperage", pl: "natężenie" },
  { en: "analgesic", pl: "analgetyk" },
  { en: "annihilation", pl: "zagłada" },
  { en: "anode", pl: "anoda" },
  { en: "antagonist", pl: "antagonista" },
  { en: "antibiotic", pl: "antybiotyk" },
  { en: "antidote", pl: "odtrutka" },
  { en: "antiseptic", pl: "środek odkażający" },
  { en: "antivenom", pl: "antytoksyna" },
  { en: "apocalypse", pl: "apokalipsa" },
  { en: "apocalyptic", pl: "apokaliptyczny" },
  { en: "architect", pl: "architekt" },
  { en: "arid", pl: "suchy" },
  { en: "armageddon", pl: "armagedon" },
  { en: "armorer", pl: "płatnerz" },
  { en: "armory", pl: "zbrojownia" },
  { en: "arsenal", pl: "arsenał" },
  { en: "ashen", pl: "popielaty" },
  { en: "assassin", pl: "skrytobójca" },
  { en: "attribute", pl: "atrybut" },
  { en: "automated", pl: "zautomatyzowany" },
  { en: "axle", pl: "oś" },
  { en: "backfill", pl: "zasypka" },
  { en: "badlands", pl: "nieużytki" },
  { en: "ballistic", pl: "balistyczny" },
  { en: "bandage", pl: "bandaż" },
  { en: "bandit", pl: "bandyta" },
  { en: "barbaric", pl: "barbarzyński" },
  { en: "barbedwire", pl: "drut kolczasty" },
  { en: "barn", pl: "stodoła" },
  { en: "barrage", pl: "kanonada" },
  { en: "barrel", pl: "lufa" },
  { en: "barren", pl: "jałowy" },
  { en: "barricade", pl: "barykada" },
  { en: "barricaded", pl: "zabarykadowany" },
  { en: "bastion", pl: "bastion" },
  { en: "battalion", pl: "batalion" },
  { en: "battery", pl: "bateria" },
  { en: "battery bank", pl: "bank baterii" },
  { en: "beam", pl: "belka" },
  { en: "behemoth", pl: "behemot" },
  { en: "besieged", pl: "oblężony" },
  { en: "bicycle", pl: "rower" },
  { en: "biker", pl: "motocyklista" },
  { en: "biome", pl: "biom" },
  { en: "bipod", pl: "dwójnóg" },
  { en: "blacksmith", pl: "kowal" },
  { en: "bleak", pl: "posępny" },
  { en: "bloated", pl: "rozdęty" },
  { en: "blood moon", pl: "krwawy księżyc" },
  { en: "blunderbuss", pl: "garłacz" },
  { en: "boarded up", pl: "zabity deskami" },
  { en: "bog", pl: "torfowisko" },
  { en: "bolt", pl: "zamek" },
  { en: "boobytrap", pl: "pułapka minowa" },
  { en: "boomstick", pl: "strzelba" },
  { en: "brawler", pl: "awanturnik" },
  { en: "breach", pl: "wyrwa" },
  { en: "breaker", pl: "wyłącznik" },
  { en: "breech", pl: "zamek" },
  { en: "brickwork", pl: "ceglarstwo" },
  { en: "brigade", pl: "brygada" },
  { en: "broadside", pl: "burta" },
  { en: "bronze", pl: "brąz" },
  { en: "brood", pl: "lęg" },
  { en: "brutal", pl: "brutalny" },
  { en: "brute", pl: "brutal" },
  { en: "builder", pl: "budowniczy" },
  { en: "bulldozer", pl: "buldożer" },
  { en: "bulwark", pl: "przedmurze" },
  { en: "bunker", pl: "bunkier" },
  { en: "butcher", pl: "rzeźnik" },
  { en: "butchering", pl: "rozbiór tuszy" },
  { en: "butte", pl: "ostańiec" },
  { en: "buttress", pl: "przypora" },
  { en: "buttstock", pl: "kolba" },
  { en: "cable", pl: "kabel" },
  { en: "cache", pl: "skrytka" },
  { en: "cadaver", pl: "zwłoki" },
  { en: "calamity", pl: "klęska" },
  { en: "caliber", pl: "kaliber" },
  { en: "caltrop", pl: "kalka" },
  { en: "cannonade", pl: "kanonada" },
  { en: "cantilever", pl: "wspornik" },
  { en: "canyon", pl: "kanion" },
  { en: "capacitor", pl: "kondensator" },
  { en: "caravan", pl: "karawana" },
  { en: "carbine", pl: "karabinek" },
  { en: "carbon fiber", pl: "włókno węglowe" },
  { en: "carburetor", pl: "gaźnik" },
  { en: "carcass", pl: "ścierwo" },
  { en: "cargo", pl: "ładunek" },
  { en: "carrion", pl: "padlina" },
  { en: "cartridge", pl: "nabój" },
  { en: "casing", pl: "łuska" },
  { en: "cassadore", pl: "Cassadore" },
  { en: "cast", pl: "gips" },
  { en: "cast iron", pl: "żeliwo" },
  { en: "cataclysm", pl: "kataklizm" },
  { en: "catastrophe", pl: "katastrofa" },
  { en: "cathode", pl: "katoda" },
  { en: "caulking", pl: "uszczelnianie" },
  { en: "cavern", pl: "pieczara" },
  { en: "cement", pl: "cement" },
  { en: "cesspool", pl: "szambo" },
  { en: "chamber", pl: "komora" },
  { en: "charged", pl: "naładowany" },
  { en: "charred", pl: "zwęglony" },
  { en: "chasm", pl: "przepaść" },
  { en: "chassis", pl: "podwozie" },
  { en: "cheerleader", pl: "cheerleaderka" },
  { en: "chromium", pl: "chrom" },
  { en: "circuit", pl: "obwód" },
  { en: "circuit board", pl: "płytka drukowana" },
  { en: "citadel", pl: "cytadela" },
  { en: "cliff", pl: "klif" },
  { en: "coal", pl: "węgiel" },
  { en: "cobblestone", pl: "bruk" },
  { en: "collapse", pl: "zawalenie" },
  { en: "colossus", pl: "kolos" },
  { en: "compaction", pl: "zagęszczenie" },
  { en: "compensator", pl: "kompensator" },
  { en: "composite", pl: "kompozyt" },
  { en: "compost", pl: "kompost" },
  { en: "compound", pl: "kompleks" },
  { en: "concertina", pl: "concertina" },
  { en: "concrete", pl: "beton" },
  { en: "concussion", pl: "wstrząs" },
  { en: "condemned", pl: "przeznaczony do rozbiórki" },
  { en: "conductor", pl: "przewodnik" },
  { en: "connector", pl: "złącze" },
  { en: "constitution", pl: "kondycja" },
  { en: "contagious", pl: "zaraźliwy" },
  { en: "containment", pl: "powstrzymanie" },
  { en: "contaminated", pl: "skażony" },
  { en: "converter", pl: "przetwornik" },
  { en: "convoy", pl: "konwój" },
  { en: "coop", pl: "kurnik" },
  { en: "corpse", pl: "ciało" },
  { en: "corral", pl: "zagroda" },
  { en: "covering fire", pl: "ogień osłaniający" },
  { en: "crafting", pl: "rzemiosło" },
  { en: "crag", pl: "urwisko" },
  { en: "crane", pl: "dźwig" },
  { en: "crawler", pl: "pełzacz" },
  { en: "crevasse", pl: "rozpadlina" },
  { en: "crop", pl: "uprawa" },
  { en: "crossbow", pl: "kusza" },
  { en: "crossfire", pl: "ogień krzyżowy" },
  { en: "crosshair", pl: "celownik" },
  { en: "crucible", pl: "tygiel" },
  { en: "crumbling", pl: "rozpadający się" },
  { en: "cultivation", pl: "uprawa" },
  { en: "debilitation", pl: "osłabienie" },
  { en: "debris", pl: "gruz" },
  { en: "decayed", pl: "zbutwiały" },
  { en: "decimator", pl: "dziesiątkarz" },
  { en: "decomposition", pl: "rozkład" },
  { en: "deconstruction", pl: "dekonstrukcja" },
  { en: "decrepit", pl: "zrujnowany" },
  { en: "defensive", pl: "obronny" },
  { en: "dehydration", pl: "odwodnienie" },
  { en: "delirium", pl: "majaczenie" },
  { en: "demoliser", pl: "burzyciel" },
  { en: "demolition", pl: "demolka" },
  { en: "demolitionist", pl: "specjalista od burzenia" },
  { en: "deprivation", pl: "deprywacja" },
  { en: "derelict", pl: "opuszczony" },
  { en: "desalination", pl: "odsalanie" },
  { en: "desert", pl: "pustynia" },
  { en: "deserted", pl: "wyludniony" },
  { en: "desolate", pl: "opustoszały" },
  { en: "desolation", pl: "spustoszenie" },
  { en: "detonator", pl: "detonator" },
  { en: "devastation", pl: "dewastacja" },
  { en: "dexterity", pl: "zręczność" },
  { en: "dilapidated", pl: "zniszczony" },
  { en: "diode", pl: "dioda" },
  { en: "diseased", pl: "chory" },
  { en: "disinfectant", pl: "dezynfektor" },
  { en: "dismal", pl: "ponury" },
  { en: "distillation", pl: "destylacja" },
  { en: "division", pl: "dywizja" },
  { en: "doomsday", pl: "dzień sądu" },
  { en: "drainage", pl: "odwodnienie" },
  { en: "drawbridge", pl: "most zwodzony" },
  { en: "dreadful", pl: "straszny" },
  { en: "dreary", pl: "ponury" },
  { en: "dressing", pl: "opatrunek" },
  { en: "drop zone", pl: "strefa zrzutu" },
  { en: "drywall", pl: "płyta gipsowa" },
  { en: "duct tape", pl: "taśma klejąca" },
  { en: "ductwork", pl: "kanały wentylacyjne" },
  { en: "dugout", pl: "ziemianka" },
  { en: "duke", pl: "książę" },
  { en: "dynamite", pl: "dynamit" },
  { en: "dysentery", pl: "czerwonka" },
  { en: "dystopian", pl: "dystopijny" },
  { en: "eerie", pl: "niesamowity" },
  { en: "electrical parts", pl: "części elektryczne" },
  { en: "electricity", pl: "elektryczność" },
  { en: "electrode", pl: "elektroda" },
  { en: "electronic", pl: "elektroniczny" },
  { en: "embankment", pl: "nasyp" },
  { en: "embrasure", pl: "otwór strzelniczy" },
  { en: "encampment", pl: "obozowisko" },
  { en: "encirclement", pl: "okrążenie" },
  { en: "enclave", pl: "enklawa" },
  { en: "endurance", pl: "wytrzymałość" },
  { en: "engine", pl: "silnik" },
  { en: "engineer", pl: "inżynier" },
  { en: "entrenched", pl: "okopany" },
  { en: "epidemic", pl: "epidemia" },
  { en: "epinephrine", pl: "epinefryna" },
  { en: "epoxy", pl: "epoksyd" },
  { en: "evacuation", pl: "ewakuacja" },
  { en: "excavation", pl: "wykop" },
  { en: "excavator", pl: "koparka" },
  { en: "executioner", pl: "kat" },
  { en: "exfiltration", pl: "eksfiltracja" },
  { en: "exhaustion", pl: "wyczerpanie" },
  { en: "explosive", pl: "materiał wybuchowy" },
  { en: "extinction", pl: "wyginięcie" },
  { en: "extraction", pl: "ewakuacja" },
  { en: "fallout", pl: "opad promieniotwórczy" },
  { en: "farmer", pl: "rolnik" },
  { en: "fatigue", pl: "zmęczenie" },
  { en: "faucet", pl: "kran" },
  { en: "feral", pl: "zdziczały" },
  { en: "fertilizer", pl: "nawóz" },
  { en: "festering", pl: "ropiejący" },
  { en: "fiberglass", pl: "włókno szklane" },
  { en: "filtration", pl: "filtracja" },
  { en: "firearm", pl: "broń palna" },
  { en: "fissure", pl: "szczelina" },
  { en: "flamethrower", pl: "miotacz ognia" },
  { en: "flanking", pl: "oskrzydlanie" },
  { en: "floodlight", pl: "światło rozproszone" },
  { en: "floodplain", pl: "równina zalewowa" },
  { en: "flux", pl: "topnik" },
  { en: "footing", pl: "ława" },
  { en: "foreboding", pl: "złowróżbny" },
  { en: "foregrip", pl: "chwyt przedni" },
  { en: "forge", pl: "kuźnia" },
  { en: "forklift", pl: "wózek widłowy" },
  { en: "forsaken", pl: "opuszczony" },
  { en: "fortification", pl: "fortyfikacja" },
  { en: "fortified", pl: "ufortyfikowany" },
  { en: "fortitude", pl: "męstwo" },
  { en: "fortress", pl: "twierdza" },
  { en: "forward base", pl: "wysunięta baza" },
  { en: "foul", pl: "ohydny" },
  { en: "foundation", pl: "fundament" },
  { en: "foxhole", pl: "okop" },
  { en: "frame", pl: "rama" },
  { en: "frigid", pl: "lodowaty" },
  { en: "frontier", pl: "pogranicze" },
  { en: "frostbite", pl: "odmrożenie" },
  { en: "fuse", pl: "bezpiecznik" },
  { en: "galvanized", pl: "ocynkowany" },
  { en: "garrison", pl: "garnizon" },
  { en: "garrisoned", pl: "obsadzony" },
  { en: "gatehouse", pl: "budynek bramny" },
  { en: "gauze", pl: "gaza" },
  { en: "generator", pl: "generator" },
  { en: "ghastly", pl: "upiorny" },
  { en: "ghoulish", pl: "upiorny" },
  { en: "girder", pl: "dźwigar" },
  { en: "gorge", pl: "wąwóz" },
  { en: "granary", pl: "spichlerz" },
  { en: "grassland", pl: "łąka" },
  { en: "greenhouse", pl: "szklarnia" },
  { en: "grenade", pl: "granat" },
  { en: "grim", pl: "ponury" },
  { en: "grip", pl: "chwyt" },
  { en: "grotesque", pl: "groteskowy" },
  { en: "grotto", pl: "grota" },
  { en: "grounding", pl: "uziemienie" },
  { en: "grouting", pl: "fugowanie" },
  { en: "grove", pl: "gaj" },
  { en: "grueling", pl: "wyczerpujący" },
  { en: "gruesome", pl: "makabryczny" },
  { en: "gunslinger", pl: "rewolwerowiec" },
  { en: "gunsmith", pl: "rusznikarz" },
  { en: "gyrocopter", pl: "żyrokopter" },
  { en: "hallucination", pl: "halucynacja" },
  { en: "handlebar", pl: "kierownica" },
  { en: "harrowing", pl: "wstrząsający" },
  { en: "harvest", pl: "żniwa" },
  { en: "harvesting", pl: "zbieractwo" },
  { en: "haul", pl: "przewóz" },
  { en: "haunting", pl: "prześladujący" },
  { en: "hazmat", pl: "gazoszczelny" },
  { en: "heatstroke", pl: "udar cieplny" },
  { en: "hemorrhage", pl: "krwotok" },
  { en: "hideous", pl: "ohydny" },
  { en: "hinterland", pl: "głębia lądu" },
  { en: "hoard", pl: "zapas" },
  { en: "horde", pl: "horda" },
  { en: "horde night", pl: "noc hordy" },
  { en: "horrendous", pl: "straszliwy" },
  { en: "hothouse", pl: "cieplarnia" },
  { en: "hunter", pl: "łowca" },
  { en: "hyperthermia", pl: "przegrzanie" },
  { en: "hypothermia", pl: "hipotermia" },
  { en: "immunity", pl: "odporność" },
  { en: "improvised", pl: "improwizowany" },
  { en: "incursion", pl: "wtargnięcie" },
  { en: "infected", pl: "zainfekowany" },
  { en: "infernal", pl: "piekielny" },
  { en: "infestation", pl: "plaga" },
  { en: "infiltration", pl: "infiltracja" },
  { en: "infiltrator", pl: "infiltrator" },
  { en: "infirmity", pl: "niemoc" },
  { en: "infrared", pl: "podczerwień" },
  { en: "ingot", pl: "sztabka" },
  { en: "inhospitable", pl: "niegościnny" },
  { en: "inner tube", pl: "dętka" },
  { en: "inoculation", pl: "szczepienie" },
  { en: "insomnia", pl: "bezsenność" },
  { en: "insulation", pl: "izolacja" },
  { en: "insulator", pl: "izolator" },
  { en: "integrity", pl: "integralność" },
  { en: "intellect", pl: "intelekt" },
  { en: "inverter", pl: "falownik" },
  { en: "irradiated", pl: "napromieniowany" },
  { en: "irrigation", pl: "nawadnianie" },
  { en: "isolation", pl: "izolacja" },
  { en: "joist", pl: "legar" },
  { en: "juryrigged", pl: "sklecony" },
  { en: "kevlar", pl: "kevlar" },
  { en: "keystone", pl: "zwornik" },
  { en: "landing zone", pl: "strefa lądowania" },
  { en: "landmine", pl: "mina lądowa" },
  { en: "leatherworking", pl: "kaletnictwo" },
  { en: "ledge", pl: "półka skalna" },
  { en: "lethality", pl: "śmiertelność" },
  { en: "livestock", pl: "inwentarz" },
  { en: "loadbearing", pl: "nośny" },
  { en: "lookout", pl: "punkt obserwacyjny" },
  { en: "loophole", pl: "strzelnica" },
  { en: "looted", pl: "splądrowany" },
  { en: "luggage", pl: "bagażnik" },
  { en: "lumberjack", pl: "drwal" },
  { en: "macabre", pl: "makabryczny" },
  { en: "machete", pl: "maczeta" },
  { en: "machinegun", pl: "karabin maszynowy" },
  { en: "magazine", pl: "magazynek" },
  { en: "magnet", pl: "magnes" },
  { en: "magnum", pl: "magnum" },
  { en: "makeshift", pl: "prowizoryczny" },
  { en: "malady", pl: "choroba" },
  { en: "malnutrition", pl: "niedożywienie" },
  { en: "maneuver", pl: "manewr" },
  { en: "manned", pl: "obsadzony" },
  { en: "marauder", pl: "maruder" },
  { en: "marksman", pl: "strzelec wyborowy" },
  { en: "marsh", pl: "mokradło" },
  { en: "masonry", pl: "murarstwo" },
  { en: "mastery", pl: "mistrzostwo" },
  { en: "material", pl: "materiał" },
  { en: "mechanic", pl: "mechanik" },
  { en: "mechanical parts", pl: "części mechaniczne" },
  { en: "medic", pl: "medyk" },
  { en: "menacing", pl: "groźny" },
  { en: "merciless", pl: "bezlitosny" },
  { en: "mesa", pl: "mesa" },
  { en: "militia", pl: "milicja" },
  { en: "minibike", pl: "minimotocykl" },
  { en: "mining", pl: "górnictwo" },
  { en: "molotov", pl: "koktajl Mołotowa" },
  { en: "monstrous", pl: "potworny" },
  { en: "morphine", pl: "morfina" },
  { en: "mortar", pl: "zaprawa" },
  { en: "motionsensor", pl: "czujnik ruchu" },
  { en: "motorcycle", pl: "motocykl" },
  { en: "mulch", pl: "ściółka" },
  { en: "munition", pl: "amunicja" },
  { en: "mutant", pl: "mutant" },
  { en: "muzzle", pl: "wylot lufy" },
  { en: "muzzlebrake", pl: "hamulec wylotowy" },
  { en: "narcotic", pl: "narkotyk" },
  { en: "navezgane", pl: "Navezgane" },
  { en: "necrosis", pl: "martwica" },
  { en: "nitrate", pl: "azotan" },
  { en: "no mans land", pl: "ziemia niczyja" },
  { en: "noxious", pl: "trujący" },
  { en: "nuclear", pl: "atomowy" },
  { en: "ominous", pl: "złowrogi" },
  { en: "onslaught", pl: "natarcie" },
  { en: "orchard", pl: "sad" },
  { en: "ordinance", pl: "uzbrojenie" },
  { en: "ore", pl: "ruda" },
  { en: "outbreak", pl: "wybuch epidemii" },
  { en: "outlaw", pl: "banita" },
  { en: "outpost", pl: "placówka" },
  { en: "overhang", pl: "nawis" },
  { en: "overload", pl: "przeciążenie" },
  { en: "overwatch", pl: "ubezpieczenie" },
  { en: "painkiller", pl: "środek przeciwbólowy" },
  { en: "palisade", pl: "palisada" },
  { en: "pandemic", pl: "pandemia" },
  { en: "paneling", pl: "boazeria" },
  { en: "parapet", pl: "parapet" },
  { en: "parasite", pl: "pasożyt" },
  { en: "pasture", pl: "pastwisko" },
  { en: "pathogen", pl: "patogen" },
  { en: "patrol", pl: "patrol" },
  { en: "payload", pl: "ładunek" },
  { en: "pen", pl: "zagroda" },
  { en: "penetration", pl: "penetracja" },
  { en: "penetrator", pl: "przebijacz" },
  { en: "perception", pl: "percepcja" },
  { en: "perimeter", pl: "obwód" },
  { en: "perk", pl: "perk" },
  { en: "perseverance", pl: "wytrwałość" },
  { en: "pestilent", pl: "zarazowy" },
  { en: "physician", pl: "lekarz" },
  { en: "pillar", pl: "filar" },
  { en: "pillbox", pl: "schron bojowy" },
  { en: "pincer", pl: "kleszcze" },
  { en: "pine forest", pl: "las sosnowy" },
  { en: "piping", pl: "rurociąg" },
  { en: "pistol", pl: "pistolet" },
  { en: "pitiless", pl: "nielitościwy" },
  { en: "plague", pl: "dżuma" },
  { en: "plastic", pl: "plastik" },
  { en: "plateau", pl: "płaskowyż" },
  { en: "platoon", pl: "pluton" },
  { en: "plumbing", pl: "hydraulika" },
  { en: "plundered", pl: "złupiony" },
  { en: "polluted", pl: "zanieczyszczony" },
  { en: "polymer", pl: "polimer" },
  { en: "portcullis", pl: "krata" },
  { en: "portentous", pl: "złowieszczy" },
  { en: "postapocalyptic", pl: "post-apokaliptyczny" },
  { en: "poultry", pl: "drób" },
  { en: "power source", pl: "źródło zasilania" },
  { en: "prairie", pl: "preria" },
  { en: "precipice", pl: "przepaść" },
  { en: "processed", pl: "przetworzony" },
  { en: "projectile", pl: "pocisk" },
  { en: "proximity", pl: "zbliżeniowy" },
  { en: "pummel", pl: "okładanie" },
  { en: "purification", pl: "oczyszczanie" },
  { en: "putrefaction", pl: "gnicie" },
  { en: "putrid", pl: "zgniły" },
  { en: "quarantine", pl: "kwarantanna" },
  { en: "radiated", pl: "napromieniowany" },
  { en: "rafter", pl: "krokiew" },
  { en: "raider", pl: "najeźdźca" },
  { en: "rally point", pl: "punkt zbiórki" },
  { en: "rampart", pl: "wał obronny" },
  { en: "rancher", pl: "ranczer" },
  { en: "ranger", pl: "strażnik" },
  { en: "ransacked", pl: "ograbiony" },
  { en: "ravaged", pl: "spustoszony" },
  { en: "ravine", pl: "jar" },
  { en: "raw", pl: "surowy" },
  { en: "razorwire", pl: "drut żyletkowy" },
  { en: "reaper", pl: "żniwiarz" },
  { en: "reaping", pl: "żniwa" },
  { en: "rebar", pl: "pręt zbrojeniowy" },
  { en: "reclamation", pl: "odzyskiwanie" },
  { en: "recoil", pl: "odrzut" },
  { en: "reconnaissance", pl: "rozpoznanie" },
  { en: "rectifier", pl: "prostownik" },
  { en: "redoubt", pl: "reduta" },
  { en: "reeking", pl: "cuchnący" },
  { en: "refined", pl: "rafinowany" },
  { en: "regiment", pl: "pułk" },
  { en: "regulator", pl: "regulator" },
  { en: "reinforcement", pl: "wzmocnienie" },
  { en: "relay", pl: "przekaźnik" },
  { en: "relentless", pl: "nieubłagany" },
  { en: "rendezvous", pl: "punkt spotkania" },
  { en: "renegade", pl: "renegat" },
  { en: "repurpose", pl: "zmienić przeznaczenie" },
  { en: "resilience", pl: "odporność" },
  { en: "resin", pl: "żywica" },
  { en: "resistance", pl: "ruch oporu" },
  { en: "resistor", pl: "rezystor" },
  { en: "resource", pl: "surowiec" },
  { en: "retaining wall", pl: "mur oporowy" },
  { en: "revolver", pl: "rewolwer" },
  { en: "ricochet", pl: "rykoszet" },
  { en: "ridge", pl: "grzbiet" },
  { en: "rifle", pl: "karabin" },
  { en: "rotting", pl: "gnijący" },
  { en: "rubber", pl: "guma" },
  { en: "rubble", pl: "rumowisko" },
  { en: "rudimentary", pl: "prymitywny" },
  { en: "ruination", pl: "ruina" },
  { en: "ruthless", pl: "bezwzględny" },
  { en: "safehouse", pl: "kryjówka" },
  { en: "salient", pl: "występ" },
  { en: "salvage", pl: "odzysk" },
  { en: "salvo", pl: "salwa" },
  { en: "savage", pl: "dziki" },
  { en: "savanna", pl: "sawanna" },
  { en: "scaffold", pl: "rusztowanie" },
  { en: "scavenged", pl: "wyszukany" },
  { en: "scavenger", pl: "padlinożerca" },
  { en: "scavenging", pl: "szperanie" },
  { en: "scope", pl: "celownik" },
  { en: "scorched", pl: "wypalony" },
  { en: "scouting", pl: "zwiad" },
  { en: "scrap", pl: "złom" },
  { en: "scrap iron", pl: "żelastwo" },
  { en: "screamer", pl: "krzykacz" },
  { en: "sealant", pl: "uszczelniacz" },
  { en: "searchlight", pl: "reflektor" },
  { en: "sedative", pl: "środek uspokajający" },
  { en: "semiconductor", pl: "półprzewodnik" },
  { en: "sentry", pl: "wartownik" },
  { en: "septdiurnal", pl: "septdiurnalny" },
  { en: "septic", pl: "septyczny" },
  { en: "serum", pl: "surowica" },
  { en: "sewer", pl: "kanalizacja" },
  { en: "shale", pl: "łupek" },
  { en: "sharpshooter", pl: "strzelec wyborowy" },
  { en: "sheet metal", pl: "blacha" },
  { en: "shelter", pl: "schronienie" },
  { en: "short circuit", pl: "zwarcie" },
  { en: "shotgun", pl: "strzelba" },
  { en: "siding", pl: "siding" },
  { en: "siege", pl: "oblężenie" },
  { en: "silencer", pl: "tłumik" },
  { en: "silicone", pl: "silikon" },
  { en: "silo", pl: "silos" },
  { en: "sinister", pl: "złowieszczy" },
  { en: "skinning", pl: "skórowanie" },
  { en: "skirmish", pl: "potyczka" },
  { en: "skullcrusher", pl: "miażdżyciel czaszek" },
  { en: "sledgehammer", pl: "młot oburęczny" },
  { en: "smoking", pl: "dymiący" },
  { en: "smoldering", pl: "tlący się" },
  { en: "snare", pl: "sidła" },
  { en: "sniper", pl: "snajper" },
  { en: "solar panel", pl: "panel słoneczny" },
  { en: "solder", pl: "lut" },
  { en: "somber", pl: "ponury" },
  { en: "sortie", pl: "wypad" },
  { en: "sowing", pl: "siew" },
  { en: "spawn", pl: "pomiot" },
  { en: "spike", pl: "kolec" },
  { en: "spitter", pl: "plwacz" },
  { en: "splint", pl: "szyna" },
  { en: "sprinkler", pl: "zraszacz" },
  { en: "squad", pl: "oddział" },
  { en: "squatted", pl: "zajęty przez squattersów" },
  { en: "stable", pl: "stajnia" },
  { en: "staging area", pl: "rejon wyjściowy" },
  { en: "stalker", pl: "prześladowca" },
  { en: "stamina", pl: "wytrzymałość" },
  { en: "starvation", pl: "głodowanie" },
  { en: "stash", pl: "składzik" },
  { en: "stench", pl: "smród" },
  { en: "sterilization", pl: "sterylizacja" },
  { en: "stimulant", pl: "stymulant" },
  { en: "stitch", pl: "ścig" },
  { en: "stock", pl: "kolba" },
  { en: "stockade", pl: "ostrokół" },
  { en: "stockpile", pl: "zapas" },
  { en: "strategic", pl: "strategiczny" },
  { en: "strength", pl: "siła" },
  { en: "stripper", pl: "obdzieracz" },
  { en: "stronghold", pl: "stronghold" },
  { en: "structural", pl: "strukturalny" },
  { en: "stud", pl: "słupek" },
  { en: "submachinegun", pl: "pistolet maszynowy" },
  { en: "suppressing fire", pl: "ogień zaporowy" },
  { en: "suppressor", pl: "tłumik" },
  { en: "surge", pl: "przepięcie" },
  { en: "surgeon", pl: "chirurg" },
  { en: "surveillance", pl: "nadzór" },
  { en: "survival", pl: "przetrwanie" },
  { en: "survivor", pl: "ocalały" },
  { en: "suspension", pl: "zawieszenie" },
  { en: "suture", pl: "szew" },
  { en: "swamp", pl: "bagno" },
  { en: "swarm", pl: "rój" },
  { en: "switch", pl: "przełącznik" },
  { en: "tactical", pl: "taktyczny" },
  { en: "taiga", pl: "tajga" },
  { en: "tanner", pl: "garbarz" },
  { en: "tanning", pl: "garbowanie" },
  { en: "taxidermy", pl: "taksydermia" },
  { en: "temperate", pl: "umiarkowany" },
  { en: "tenacity", pl: "zaciętość" },
  { en: "terminal", pl: "zacisk" },
  { en: "thermal", pl: "termiczny" },
  { en: "tinkerer", pl: "majsterkowicz" },
  { en: "tire", pl: "opona" },
  { en: "titanium", pl: "tytan" },
  { en: "torrid", pl: "gorący" },
  { en: "tourniquet", pl: "opaska uciskowa" },
  { en: "tow", pl: "holować" },
  { en: "tracker", pl: "tropiciel" },
  { en: "tractor", pl: "traktor" },
  { en: "trajectory", pl: "trajektoria" },
  { en: "transformer", pl: "transformator" },
  { en: "transistor", pl: "tranzystor" },
  { en: "transport", pl: "transport" },
  { en: "trap", pl: "pułapka" },
  { en: "trench", pl: "okop" },
  { en: "trigger", pl: "spust" },
  { en: "tripod", pl: "trójnóg" },
  { en: "tripwire", pl: "linka potykowa" },
  { en: "truss", pl: "kratownica" },
  { en: "tundra", pl: "tundra" },
  { en: "tungsten", pl: "wolfram" },
  { en: "turret", pl: "wieżyczka" },
  { en: "tyrant", pl: "tyran" },
  { en: "uncanny", pl: "niepokojący" },
  { en: "undead", pl: "nieumarły" },
  { en: "unforgiving", pl: "bezlitosny" },
  { en: "uninhabitable", pl: "niezdatny do mieszkania" },
  { en: "upcycle", pl: "przetworzyć" },
  { en: "vaccine", pl: "szczepionka" },
  { en: "valve", pl: "zawór" },
  { en: "vault", pl: "krypta" },
  { en: "vehicle", pl: "pojazd" },
  { en: "venison", pl: "dziczyzna" },
  { en: "ventilation", pl: "wentylacja" },
  { en: "vineyard", pl: "winnica" },
  { en: "virulent", pl: "zjadliwy" },
  { en: "virus", pl: "wirus" },
  { en: "vitality", pl: "witalność" },
  { en: "volley", pl: "salwa" },
  { en: "voltage", pl: "napięcie" },
  { en: "warhead", pl: "głowica" },
  { en: "warlord", pl: "dyktator" },
  { en: "wasteland", pl: "pustkowie" },
  { en: "watchtower", pl: "wieża strażnicza" },
  { en: "waterproof", pl: "wodoodporny" },
  { en: "wattage", pl: "moc" },
  { en: "wellness", pl: "kondycja" },
  { en: "wetland", pl: "teren podmokły" },
  { en: "wheel", pl: "koło" },
  { en: "wight", pl: "widmo" },
  { en: "wilderness", pl: "dzicz" },
  { en: "winch", pl: "wyciągarka" },
  { en: "wiring", pl: "okablowanie" },
  { en: "workbench", pl: "stół warsztatowy" },
  { en: "wreckage", pl: "wrak" },
  { en: "yield", pl: "plon" },
  { en: "zombie", pl: "zombie" },
  { en: "arlene", pl: "Arlene" },
  { en: "marlene", pl: "Marlene" },
  { en: "party girl", pl: "imprezowiczka" },
  { en: "nurse", pl: "pielęgniarka" },
  { en: "businessman", pl: "biznesmen" },
  { en: "joe", pl: "Joe" },
  { en: "steve", pl: "Steve" },
  { en: "tom clark", pl: "Tom Clark" },
  { en: "burnt zombie", pl: "spalony zombie" },
  { en: "spider zombie", pl: "pajęczy zombie" },
  { en: "boe", pl: "Boe" },
  { en: "moe", pl: "Moe" },
  { en: "yo", pl: "Yo" },
  { en: "janitor", pl: "woźny" },
  { en: "inmate", pl: "więzień" },
  { en: "utility worker", pl: "pracownik techniczny" },
  { en: "darlene", pl: "Darlene" },
  { en: "lab worker", pl: "pracownik laboratorium" },
  { en: "hazmat zombie", pl: "zombie hazmat" },
  { en: "crawler", pl: "pełzacz" },
  { en: "thug", pl: "bandzior" },
  { en: "soldier", pl: "żołnierz" },
  { en: "wight", pl: "widmo" },
  { en: "biker", pl: "motocyklista" },
  { en: "lumberjack", pl: "drwal" },
  { en: "tourist", pl: "turysta" },
  { en: "bowler", pl: "kręglarz" },
  { en: "big mama", pl: "gruba mama" },
  { en: "cop zombie", pl: "zombie glina" },
  { en: "screamer", pl: "krzykacz" },
  { en: "demolition zombie", pl: "zombie burzyciel" },
  { en: "rancher", pl: "ranczer" },
  { en: "chuck", pl: "Chuck" },
  { en: "mutated zombie", pl: "zmutowany zombie" },
  { en: "feral", pl: "zdziczały" },
  { en: "radiated", pl: "napromieniowany" },
  { en: "charged", pl: "naładowany" },
  { en: "infernal", pl: "piekielny" },
  { en: "zombie dog", pl: "zombie pies" },
  { en: "zombie vulture", pl: "zombie sęp" },
  { en: "dire wolf", pl: "wilk straszliwy" },
  { en: "zombie bear", pl: "zombie niedźwiedź" },
  { en: "grace", pl: "Grace" },
  { en: "boar", pl: "dzik" },
  { en: "wooden club", pl: "drewniana pałka" },
  { en: "baseball bat", pl: "kij baseballowy" },
  { en: "steel club", pl: "stalowa pałka" },
  { en: "candy cane club", pl: "pałka z laseczki cukrowej" },
  { en: "stone sledgehammer", pl: "kamienny młot" },
  { en: "iron sledgehammer", pl: "żelazny młot" },
  { en: "steel sledgehammer", pl: "stalowy młot" },
  { en: "stone spear", pl: "kamienna włócznia" },
  { en: "iron spear", pl: "żelazna włócznia" },
  { en: "steel spear", pl: "stalowa włócznia" },
  { en: "bone knife", pl: "nóż z kości" },
  { en: "hunting knife", pl: "nóż myśliwski" },
  { en: "machete", pl: "maczeta" },
  { en: "candy cane knife", pl: "nóż z laseczki cukrowej" },
  { en: "knuckle wraps", pl: "owijki na pięści" },
  { en: "iron knuckles", pl: "żelazne kastety" },
  { en: "steel knuckles", pl: "stalowe kastety" },
  { en: "pipe baton", pl: "rurowa pałka" },
  { en: "stun baton", pl: "pałka ogłuszająca" },
  { en: "wooden bow", pl: "drewniany łuk" },
  { en: "primitive bow", pl: "prymitywny łuk" },
  { en: "iron crossbow", pl: "żelazna kusza" },
  { en: "compound bow", pl: "łuk bloczkowy" },
  { en: "compound crossbow", pl: "kusza bloczkowa" },
  { en: "pipe shotgun", pl: "rurowa strzelba" },
  { en: "double barrel shotgun", pl: "dwururka" },
  { en: "pump shotgun", pl: "pompka" },
  { en: "auto shotgun", pl: "strzelba automatyczna" },
  { en: "pipe rifle", pl: "karabin rurowy" },
  { en: "hunting rifle", pl: "karabin myśliwski" },
  { en: "lever-action rifle", pl: "karabin dźwigniowy" },
  { en: "sniper rifle", pl: "karabin snajperski" },
  { en: "pipe machine gun", pl: "rurowy karabin maszynowy" },
  { en: "ak-47", pl: "AK-47" },
  { en: "tactical assault rifle", pl: "taktyczny karabin szturmowy" },
  { en: "m60", pl: "M60" },
  { en: "pipe pistol", pl: "pistolet rurowy" },
  { en: "pistol", pl: "pistolet" },
  { en: "44 magnum", pl: ".44 Magnum" },
  { en: "44 desert vulture", pl: ".44 Desert Vulture" },
  { en: "smg-5", pl: "SMG-5" },
  { en: "rocket launcher", pl: "wyrzutnia rakiet" },
  { en: "exploding arrow", pl: "wybuchająca strzała" },
  { en: "exploding crossbow bolt", pl: "wybuchający bełt" },
  { en: "pipe bomb", pl: "rurowa bomba" },
  { en: "grenade", pl: "granat" },
  { en: "contact grenade", pl: "granat kontaktowy" },
  { en: "timed charge", pl: "ładunek czasowy" },
  { en: "molotov cocktail", pl: "koktajl Mołotowa" },
  { en: "tin land mine", pl: "mina z puszki" },
  { en: "cooking pot mine", pl: "mina z garnka" },
  { en: "hub cap land mine", pl: "mina z kołpaka" },
  { en: "air filter land mine", pl: "mina z filtra powietrza" },
  { en: "rusty barrel", pl: "zardzewiała beczka" },
  { en: "robotic drone", pl: "zrobotyzowany dron" },
  { en: "robotic sledge", pl: "zrobotyzowany młot" },
  { en: "robotic turret", pl: "zrobotyzowana wieżyczka" },
  { en: "primitive armor", pl: "prymitywna zbroja" },
  { en: "light armor", pl: "lekka zbroja" },
  { en: "medium armor", pl: "średnia zbroja" },
  { en: "heavy armor", pl: "ciężka zbroja" },
  { en: "athletic armor", pl: "zbroja atletyczna" },
  { en: "enforcer armor", pl: "zbroja egzekutora" },
  { en: "lumberjack armor", pl: "zbroja drwala" },
  { en: "preacher armor", pl: "zbroja kaznodziei" },
  { en: "rogue armor", pl: "zbroja łotrzyka" },
  { en: "assassin armor", pl: "zbroja skrytobójcy" },
  { en: "biker armor", pl: "zbroja motocyklisty" },
  { en: "commando armor", pl: "zbroja komandosa" },
  { en: "farmer armor", pl: "zbroja farmera" },
  { en: "ranger armor", pl: "zbroja strażnika" },
  { en: "scavenger armor", pl: "zbroja złomiarza" },
  { en: "miner armor", pl: "zbroja górnika" },
  { en: "nomad armor", pl: "zbroja nomada" },
  { en: "nerd armor", pl: "zbroja kujona" },
  { en: "raider armor", pl: "zbroja najeźdźcy" },
  { en: "primitive hood", pl: "prymitywny kaptur" },
  { en: "primitive outfit", pl: "prymitywny strój" },
  { en: "primitive gloves", pl: "prymitywne rękawice" },
  { en: "primitive shoes", pl: "prymitywne buty" },
  { en: "athletic hat", pl: "czapka atletyczna" },
  { en: "athletic outfit", pl: "strój atletyczny" },
  { en: "athletic gloves", pl: "rękawice atletyczne" },
  { en: "athletic shoes", pl: "buty atletyczne" },
  { en: "enforcer sunglasses", pl: "okulary egzekutora" },
  { en: "enforcer outfit", pl: "strój egzekutora" },
  { en: "enforcer gloves", pl: "rękawice egzekutora" },
  { en: "enforcer shoes", pl: "buty egzekutora" },
  { en: "lumberjack hat", pl: "czapka drwala" },
  { en: "lumberjack outfit", pl: "strój drwala" },
  { en: "lumberjack gloves", pl: "rękawice drwala" },
  { en: "lumberjack boots", pl: "buty drwala" },
  { en: "preacher hat", pl: "kapelusz kaznodziei" },
  { en: "preacher outfit", pl: "strój kaznodziei" },
  { en: "preacher gloves", pl: "rękawice kaznodziei" },
  { en: "preacher boots", pl: "buty kaznodziei" },
  { en: "rogue hood", pl: "kaptur łotrzyka" },
  { en: "rogue outfit", pl: "strój łotrzyka" },
  { en: "rogue gloves", pl: "rękawice łotrzyka" },
  { en: "rogue boots", pl: "buty łotrzyka" },
  { en: "assassin hood", pl: "kaptur skrytobójcy" },
  { en: "assassin outfit", pl: "strój skrytobójcy" },
  { en: "assassin gloves", pl: "rękawice skrytobójcy" },
  { en: "assassin boots", pl: "buty skrytobójcy" },
  { en: "biker helmet", pl: "kask motocyklisty" },
  { en: "biker outfit", pl: "strój motocyklisty" },
  { en: "biker gloves", pl: "rękawice motocyklisty" },
  { en: "biker boots", pl: "buty motocyklisty" },
  { en: "commando helmet", pl: "hełm komandosa" },
  { en: "commando outfit", pl: "strój komandosa" },
  { en: "commando gloves", pl: "rękawice komandosa" },
  { en: "commando boots", pl: "buty komandosa" },
  { en: "farmer hat", pl: "kapelusz farmera" },
  { en: "farmer outfit", pl: "strój farmera" },
  { en: "farmer gloves", pl: "rękawice farmera" },
  { en: "farmer boots", pl: "buty farmera" },
  { en: "ranger hat", pl: "kapelusz strażnika" },
  { en: "ranger outfit", pl: "strój strażnika" },
  { en: "ranger gloves", pl: "rękawice strażnika" },
  { en: "ranger boots", pl: "buty strażnika" },
  { en: "scavenger hat", pl: "czapka złomiarza" },
  { en: "scavenger outfit", pl: "strój złomiarza" },
  { en: "scavenger gloves", pl: "rękawice złomiarza" },
  { en: "scavenger boots", pl: "buty złomiarza" },
  { en: "miner helmet", pl: "hełm górnika" },
  { en: "miner outfit", pl: "strój górnika" },
  { en: "miner gloves", pl: "rękawice górnika" },
  { en: "miner boots", pl: "buty górnika" },
  { en: "nerd goggles", pl: "gogle kujona" },
  { en: "nerd outfit", pl: "strój kujona" },
  { en: "nerd gloves", pl: "rękawice kujona" },
  { en: "nerd boots", pl: "buty kujona" },
  { en: "nomad headgear", pl: "nakrycie głowy nomada" },
  { en: "nomad outfit", pl: "strój nomada" },
  { en: "nomad gloves", pl: "rękawice nomada" },
  { en: "nomad boots", pl: "buty nomada" },
  { en: "raider helmet", pl: "hełm najeźdźcy" },
  { en: "raider outfit", pl: "strój najeźdźcy" },
  { en: "raider gloves", pl: "rękawice najeźdźcy" },
  { en: "raider boots", pl: "buty najeźdźcy" },
  { en: "santa hat", pl: "czapka Mikołaja" },
  { en: "pummel pete", pl: "Pummel Pete" },
  { en: "skull crusher", pl: "Miażdżyciel Czaszek" },
  { en: "boomstick", pl: "Boomstick" },
  { en: "spear master", pl: "Mistrz Włóczni" },
  { en: "demolitions expert", pl: "Ekspert od Burzenia" },
  { en: "dead eye", pl: "Martwe Oko" },
  { en: "the brawler", pl: "Awanturnik" },
  { en: "machine gunner", pl: "Karabinowy" },
  { en: "deep cuts", pl: "Głębokie Cięcia" },
  { en: "archery", pl: "Łucznictwo" },
  { en: "gunslinger", pl: "Rewolwerowiec" },
  { en: "electrocutioner", pl: "Elektrokuter" },
  { en: "robotics inventor", pl: "Wynalazca Robotyki" },
  { en: "from the shadows", pl: "Z Cienia" },
  { en: "strength", pl: "siła" },
  { en: "perception", pl: "percepcja" },
  { en: "fortitude", pl: "hart ducha" },
  { en: "agility", pl: "zwinność" },
  { en: "intelligence", pl: "inteligencja" },
  { en: "blood moon", pl: "krwawy księżyc" },
  { en: "gamestage", pl: "etap gry" },
  { en: "structural integrity", pl: "integralność strukturalna" },
  { en: "heatmap", pl: "mapa ciepła" },
  { en: "feral sense", pl: "zmysł zdziczenia" },
  { en: "dismemberment", pl: "rozczłonkowanie" },
  { en: "stealth system", pl: "system skradania" },
  { en: "stunned", pl: "ogłuszony" },
  { en: "fatigue", pl: "zmęczenie" },
  { en: "sprained leg", pl: "skręcona noga" },
  { en: "sprained arm", pl: "skręcona ręka" },
  { en: "laceration", pl: "rany szarpane" },
  { en: "bleeding", pl: "krwawienie" },
  { en: "infection", pl: "infekcja" },
  { en: "rad remover mod", pl: "mod na usuwanie radiacji" },
  { en: "stun resistance", pl: "odporność na ogłuszenie" },
  { en: "critical injury resistance", pl: "odporność na krytyczne obrażenia" },
  { en: "bicycle", pl: "rower" },
  { en: "minibike", pl: "minimotocykl" },
  { en: "motorcycle", pl: "motocykl" },
  { en: "4x4 truck", pl: "ciężarówka 4x4" },
  { en: "gyrocopter", pl: "żyrokopter" },
  { en: "beer", pl: "piwo" },
  { en: "small stone", pl: "mały kamień" },
  { en: "snowball", pl: "śnieżka" },
  { en: "stone axe", pl: "kamienny topór" },
  { en: "claw hammer", pl: "młotek ciesielski" },
  { en: "nailgun", pl: "gwoździarka" },
  { en: "wood spike", pl: "drewniany kolec" },
  { en: "hay bale", pl: "bela siana" },
  { en: "rotting flesh", pl: "gnijące mięso" },
  { en: "short iron pipe", pl: "krótka żelazna rura" },
  { en: "repair kit", pl: "zestaw naprawczy" },
  { en: "wood", pl: "drewno" },
  { en: "stone", pl: "kamień" },
  { en: "small stone", pl: "kamyk" },
  { en: "bone", pl: "kość" },
  { en: "cloth fragment", pl: "kawałek materiału" },
  { en: "iron bar", pl: "żelazny pręt" },
  { en: "dirt", pl: "ziemia" },
  { en: "burnt forest", pl: "spalony las" },
  { en: "desert", pl: "pustynia" },
  { en: "snow", pl: "śnieg" },
  { en: "wasteland", pl: "pustkowie" },
  { en: "pine forest", pl: "las sosnowy" },
  { en: "navezgane", pl: "Navezgane" },
  { en: "point of interest", pl: "punkt zainteresowania" },
  { en: "trader", pl: "handlarz" },
  { en: "electric fence post", pl: "słupek ogrodzenia elektrycznego" },
  { en: "armor rating", pl: "współczynnik pancerza" },
  { en: "explosion resistance", pl: "odporność na eksplozje" },
  { en: "crit resist", pl: "odp. na krytyczne" },
  { en: "cold resist", pl: "odp. na zimno" },
  { en: "heat resist", pl: "odp. na ciepło" },
  { en: "mobility", pl: "mobilność" },
  { en: "stamina regen", pl: "regeneracja kondycji" },
  { en: "noise", pl: "hałas" },
  { en: "durability", pl: "wytrzymałość" },
  { en: "set bonus", pl: "bonus zestawu" },
  { en: "lootstage", pl: "etap łupów" },
  { en: "crouch", pl: "kucać" },
  { en: "repair", pl: "naprawiać" },
  { en: "salvage", pl: "odzysk" },
  { en: "encumbrance", pl: "obciążenie" },
  { en: "lockpicking", pl: "otwieranie zamków" },
  { en: "bartering", pl: "handel wymienny" }
];
