var WORDS_XANTH = [
  { en: "perched", pl: "siedział na czymś" },
  { en: "metamorphosed", pl: "przeobraził się" },
  { en: "obnoxious", pl: "wstrętny" },
  { en: "mimic", pl: "naśladować" },
  { en: "genuine", pl: "prawdziwy" },
  { en: "ferocity", pl: "zaciekłość" },
  { en: "mirth", pl: "wesołość" },
  { en: "abated", pl: "osłabł, zmalał" },
  { en: "malice", pl: "złośliwość" },
  { en: "anguish", pl: "udręka" },
  { en: "convulsed", pl: "zadygotał" },
  { en: "limply", pl: "bezwładnie" },
  { en: "ascended", pl: "wzniósł się" },
  { en: "pretensions", pl: "pozory" },
  { en: "agency", pl: "sprawstwo, czynnik" },
  { en: "percolate", pl: "przenikać" },
  { en: "omen", pl: "wróżba, omen" },
  { en: "dire", pl: "złowrogi" },
  { en: "misinterpreted", pl: "źle zinterpretowany" },
  { en: "brutally", pl: "brutalnie" },
  { en: "enchantments", pl: "zaklęcia, uroki" },
  { en: "slanting", pl: "ukośny" },
  { en: "enhance", pl: "polepszyć, wzmocnić" },
  { en: "artificial", pl: "sztuczny" },
  { en: "lofty", pl: "wyniosły" },
  { en: "promontory", pl: "przylądek, cypl" },
  { en: "situational", pl: "sytuacyjny" },
  { en: "elevated", pl: "podwyższony" },
  { en: "deceptively", pl: "zwodniczo" },
  { en: "unruly", pl: "niesforny" },
  { en: "prattle", pl: "paplanina" },
  { en: "animate", pl: "ożywiony" },
  { en: "facilitated", pl: "ułatwione" },
  { en: "lichen", pl: "porost" },
  { en: "self-defeating", pl: "przeciwskuteczny" },
  { en: "stubbed", pl: "uderzył palcem u nogi" },
  { en: "fragment", pl: "odłamek" },
  { en: "fragmented", pl: "rozbity na kawałki" },
  { en: "philosophical", pl: "filozoficzny" },
  { en: "insatiable", pl: "nienasycony" },
  { en: "bedrock", pl: "podłoże skalne" },
  { en: "demurely", pl: "skromnie, nieśmiało" },
  { en: "exiled", pl: "wygnany" },
  { en: "embarrassment", pl: "zażenowanie" },
  { en: "blurted", pl: "wypalił bez zastanowienia" },
  { en: "blithely", pl: "beztrosko" },
  { en: "immense", pl: "ogromny" },
  { en: "courtesy", pl: "uprzejmość" },
  { en: "latent", pl: "ukryty, utajony" },
  { en: "inimical", pl: "wrogi" },
  { en: "cleaver", pl: "tasak" },
  { en: "tenacity", pl: "wytrwałość" },
  { en: "adversity", pl: "przeciwność losu" },
  { en: "bargain", pl: "korzystna umowa" },
  { en: "drear", pl: "ponury" },
  { en: "null", pl: "zerowy" },
  { en: "flurry", pl: "zamieszanie" },
  { en: "contemplation", pl: "rozmyślanie" },
  { en: "dissipate", pl: "rozproszyć się" },
  { en: "spherical", pl: "kulisty" },
  { en: "three-dimensional", pl: "trójwymiarowy" },
  { en: "wither", pl: "uschnąć, więdnąć" },
  { en: "disqualified", pl: "zdyskwalifikowany" },
  { en: "redeem", pl: "odkupić" },
  { en: "self-respect", pl: "szacunek do siebie" },
  { en: "pert", pl: "jędrny" },
  { en: "derriere", pl: "pośladki" },
  { en: "distorting", pl: "zniekształcając" },
  { en: "grotesquely", pl: "groteskowo" },
  { en: "posterior", pl: "tyłek" },
  { en: "cocky", pl: "zarozumiały" },
  { en: "providential", pl: "opatrznościowy" },
  { en: "complement", pl: "dopełnienie" },
  { en: "crass", pl: "niewychowany, prostacki" },
  { en: "impotent", pl: "bezsilny" },
  { en: "pranksters", pl: "psotnicy" },
  { en: "mischief", pl: "psoty, swawole" },
  { en: "rigors", pl: "trudy, surowość" },
  { en: "objective", pl: "obiektywny" },
  { en: "shuddered", pl: "wzdrygnął się" },
  { en: "dusk", pl: "zmierzch" },
  { en: "unique", pl: "unikalny" },
  { en: "sprouted", pl: "wybiegł, wykiełkował" },
  { en: "hue", pl: "odcień" },
  { en: "tanned", pl: "opalony" },
  { en: "awesome", pl: "budzący grozę" },
  { en: "preempt", pl: "przejąć, uprzedzić" },
  { en: "nuisances", pl: "utrapienia" },
  { en: "retained", pl: "zachował" },
  { en: "ventriloquism", pl: "brzuchomówstwo" },
  { en: "comprehensible", pl: "zrozumiały" },
  { en: "utterance", pl: "wypowiedź" },
  { en: "vocal cords", pl: "struny głosowe" },
  { en: "stately", pl: "okazały, dostojny" },
  { en: "veered", pl: "skręcił" },
  { en: "ruffians", pl: "łobuziaki" },
  { en: "lurking", pl: "czający się" },
  { en: "principle", pl: "zasada" },
  { en: "monument", pl: "pomnik" },
  { en: "summoned", pl: "przywołał, wezwał" },
  { en: "senile", pl: "starczy, zdzieciniały" },
  { en: "hurricane", pl: "huragan" },
  { en: "tornado", pl: "tornado" },
  { en: "spawning", pl: "tarło, rozród" },
  { en: "sheer", pl: "czysty, kompletny" },
  { en: "agony", pl: "agonia, ból" },
  { en: "erupted", pl: "wybuchł" },
  { en: "lark", pl: "figiel, wygłup" },
  { en: "insensitivity", pl: "bezduszność" },
  { en: "malicious", pl: "złośliwy" },
  { en: "scattered", pl: "rozproszył się" },
  { en: "squatted", pl: "przykucnął" },
  { en: "driblets", pl: "kropelki" },
  { en: "sap", pl: "sok drzewny" },
  { en: "compresses", pl: "okłady" },
  { en: "louts", pl: "prostacy, gburowie" },
  { en: "gruffly", pl: "szorstko" },
  { en: "vandalism", pl: "wandalizm" },
  { en: "intoxicated", pl: "odurzony" },
  { en: "ambush", pl: "zasadzka" },
  { en: "animating", pl: "ożywianie" },
  { en: "immune", pl: "odporny" },
  { en: "inhaled", pl: "wdychał" },
  { en: "enveloped", pl: "ogarnął, otoczył" },
  { en: "deviously", pl: "podstępnie" },
  { en: "indefinitely", pl: "bez końca" },
  { en: "piercingly", pl: "przeszywająco" },
  { en: "immobile", pl: "nieruchomy" },
  { en: "cradling", pl: "tuląc" },
  { en: "laughingstock", pl: "pośmiewisko" },
  { en: "interminable", pl: "niekończący się" },
  { en: "falsetto", pl: "piskliwy głos" },
  { en: "sniggered", pl: "chichotał" },
  { en: "husky", pl: "krzepko zbudowany" },
  { en: "contemptuously", pl: "pogardliwie" },
  { en: "stooped", pl: "schylił się" },
  { en: "absorbed", pl: "wchłonął" },
  { en: "mobile", pl: "ruchomy" },
  { en: "migrated", pl: "migrował" },
  { en: "heredity", pl: "dziedziczność" },
  { en: "environmental", pl: "środowiskowy" },
  { en: "hovering", pl: "unoszący się w powietrzu" },
  { en: "disquieting", pl: "niepokojący" },
  { en: "catalogued", pl: "skatalogowany" },
  { en: "hostile", pl: "wrogi" },
  { en: "specters", pl: "widma, upiory" },
  { en: "shades", pl: "cienie, zjawy" },
  { en: "ghastly", pl: "upiorny" },
  { en: "zombie", pl: "ożywiony trup" },
  { en: "repulsion", pl: "odstraszenie, wstręt" },
  { en: "supernatural", pl: "nadprzyrodzony" },
  { en: "timidity", pl: "bojaźliwość" },
  { en: "stray", pl: "zboczyć, zabłądzić" },
  { en: "swiftly", pl: "szybko" },
  { en: "adolescent", pl: "nastolatek" },
  { en: "savagely", pl: "dziko, zawzięcie" },
  { en: "slashing", pl: "tnąc, chłoszcząc" },
  { en: "excruciatingly", pl: "rozdzierająco" },
  { en: "defensive", pl: "obronny" },
  { en: "betrayed", pl: "zdradził" },
  { en: "bias", pl: "uprzedzenie" },
  { en: "nominally", pl: "nominalnie" },
  { en: "comprehend", pl: "pojmować" },
  { en: "unwittingly", pl: "nieświadomie" },
  { en: "phenomenally", pl: "fenomenalnie" },
  { en: "surfeited", pl: "przesycony" },
  { en: "ardor", pl: "zapał, żarliwość" },
  { en: "disgust", pl: "obrzydzenie" },
  { en: "shortcut", pl: "droga na skróty" },
  { en: "conservative", pl: "konserwatywny" },
  { en: "circumscribed", pl: "ograniczony" },
  { en: "circumspectly", pl: "oględnie" },
  { en: "eligible", pl: "odpowiedni kandydat" },
  { en: "prejudiced", pl: "uprzedzony" },
  { en: "viable", pl: "realny, wykonalny" },
  { en: "nonentity", pl: "nikt, zer" },
  { en: "abruptly", pl: "nagle" },
  { en: "balked", pl: "zawahał się" },
  { en: "dangling", pl: "zwisając" },
  { en: "realization", pl: "uświadomienie sobie" },
  { en: "twisted", pl: "pokręcony" },
  { en: "fated", pl: "skazany przez los" },
  { en: "sparkles", pl: "iskierki" },
  { en: "necessities", pl: "konieczności, potrzeby" },
  { en: "vegetable kingdom", pl: "królestwo roślin" },
  { en: "overpowered", pl: "obezwładniony" },
  { en: "casual inspection", pl: "pobieżna inspekcja" },
  { en: "cosmetics", pl: "kosmetyki" },
  { en: "padding", pl: "wypełnienie" },
  { en: "specialized spells", pl: "wyspecjalizowane zaklęcia" },
  { en: "multicolored", pl: "wielokolorowy" },
  { en: "ecological", pl: "ekologiczny" },
  { en: "mutual", pl: "wzajemny" },
  { en: "luring", pl: "wabiąc" },
  { en: "appetite", pl: "apetyt" },
  { en: "identity", pl: "tożsamość" },
  { en: "insisted", pl: "nalegał" },
  { en: "tissues", pl: "tkanki" },
  { en: "consumed", pl: "spożywał" },
  { en: "faith", pl: "wiara, zaufanie" },
  { en: "category", pl: "kategoria" },
  { en: "mutilation", pl: "okaleczenie" },
  { en: "restorative", pl: "odbudowujący, regenerujący" },
  { en: "rotted", pl: "zgniły" },
  { en: "replayed", pl: "odtworzone ponownie" },
  { en: "intensifying", pl: "intensyfikując się" },
  { en: "solidified", pl: "zestalił się" },
  { en: "lass", pl: "dziewczyna" },
  { en: "frills", pl: "falbanki" },
  { en: "perspective", pl: "perspektywa" },
  { en: "strictly speaking", pl: "ściśle mówiąc" },
  { en: "qualify", pl: "kwalifikować się" },
  { en: "whirled", pl: "obróciła się gwałtownie" },
  { en: "furiously", pl: "wściekle" },
  { en: "appealing", pl: "pociągający, atrakcyjny" },
  { en: "clenched", pl: "zaciśnięte" },
  { en: "strode", pl: "kroczył" },
  { en: "grinning", pl: "uśmiechający się szeroko" },
  { en: "struck", pl: "uderzył" },
  { en: "balance", pl: "równowaga" },
  { en: "invisible", pl: "niewidzialny" },
  { en: "headlong", pl: "na łeb na szyję" },
  { en: "temporary", pl: "tymczasowy" },
  { en: "dodge", pl: "uchylić się" },
  { en: "joker", pl: "żartowniś" },
  { en: "proposing", pl: "oświadczając się" },
  { en: "officially", pl: "oficjalnie" },
  { en: "objectively", pl: "obiektywnie" },
  { en: "economy", pl: "gospodarka" },
  { en: "footwear", pl: "obuwie" },
  { en: "genius", pl: "geniusz" },
  { en: "scenery", pl: "krajobraz, sceneria" },
  { en: "summon", pl: "wezwać, przywołać" },
  { en: "flanked", pl: "otoczony, flankowany" },
  { en: "indignation", pl: "oburzenie" },
  { en: "balk", pl: "opierać się" },
  { en: "nymph", pl: "nimfa" },
  { en: "abraded", pl: "obdarty" },
  { en: "jealous", pl: "zazdrosny" },
  { en: "confessing", pl: "przyznając się" },
  { en: "sensitized", pl: "uwrażliwiony" },
  { en: "notion", pl: "pojęcie" },
  { en: "captive", pl: "niewolnik, jeniec" },
  { en: "juvenile", pl: "młodzieńczy" },
];
