# Additional PoE vocabulary from keystones, currency, ascendancy, divination cards
extra_deck = [
    # Keystone Passives (very rich vocabulary)
    ("acrobatics", "akrobatyka"),
    ("ancestral", "przodków"),
    ("avatar", "awatar"),
    ("conduit", "przewód"),
    ("crimson", "karmazynowy"),
    ("divine", "boski"),
    ("eldritch", "przerażający"),
    ("equilibrium", "równowaga"),
    ("overload", "przeciążenie"),
    ("instability", "niestabilność"),
    ("necromantic", "nekromantyczny"),
    ("attunement", "dostrojenie"),
    ("agony", "agonia"),
    ("retaliation", "odwet"),
    ("imbalanced", "niezrównoważony"),
    ("reflexes", "odruch"),
    ("solipsism", "solipsyzm"),
    ("supreme", "najwyższy"),
    ("unwavering", "niezachwiany"),
    ("versatile", "wszechstronny"),
    ("combatant", "wojownik"),
    ("worship", "czcić"),
    ("fungal", "grzybowy"),
    ("resolute", "zdecydowany"),
    ("precise", "precyzyjny"),
    ("impaler", "przebijacz"),
    ("dancer", "tancerz"),
    ("wicked", "nikczemny"),
    ("zealot", "zelota"),
    ("oath", "przysięga"),
    ("acolyte", "akolita"),
    ("ascendancy", "wzniosłość"),
    ("ascendant", "wstępujący"),
    ("reliquarian", "relikwiarz"),
    ("hierophant", "hierofant"),
    ("inquisitor", "inkwizytor"),
    ("occultist", "okultysta"),
    ("elementalist", "żywiołak"),
    ("necromancer", "nekromanta"),
    ("gladiator", "gladiator"),
    ("slayer", "pogromca"),
    ("champion", "czempion"),
    ("beserker", "berserker"),
    ("juggernaut", "siłacz"),
    ("chieftain", "wódz"),
    ("raider", "najeźdźca"),
    ("deadeye", "strzelec wyborowy"),
    ("pathfinder", "tropiciel"),
    ("saboteur", "sabotażysta"),
    ("assassin", "skrytobójca"),
    ("trickster", "oszust"),
    ("warden", "strażnik"),
    ("guardian", "strażnik"),

    # Currency & Crafting
    ("alchemy", "alchemia"),
    ("transmutation", "transmutacja"),
    ("alteration", "zmiana"),
    ("augmentation", "wzmocnienie"),
    ("scouring", "czyszczenie"),
    ("regal", "królewski"),
    ("exalted", "wywyższony"),
    ("annulment", "anulowanie"),
    ("fracturing", "pękanie"),
    ("fusing", "łączenie"),
    ("jeweller", "jubiler"),
    ("chromatic", "chromatyczny"),
    ("enkindling", "rozpalanie"),
    ("instilling", "wpajanie"),
    ("reflecting", "odbijający"),
    ("conflict", "konflikt"),
    ("dominance", "dominacja"),
    ("intention", "intencja"),
    ("remembrance", "wspomnienie"),
    ("unravelling", "rozplątywanie"),
    ("proliferation", "proliferacja"),
    ("procurement", "zaopatrzenie"),
    ("scarabs", "skarabeusze"),
    ("essence", "esencja"),
    ("fossil", "skamielina"),
    ("resonator", "rezonator"),
    ("incubator", "inkubator"),
    ("embem", "emblemat"),
    ("anoint", "namaścić"),
    ("enchantment", "zaklęcie"),
    ("implicit", "domniemany"),
    ("explicit", "jawny"),
    ("modifier", "modyfikator"),
    ("prefix", "przedrostek"),
    ("suffix", "przyrostek"),
    ("socket", "gniazdo"),
    ("fracture", "pęknięcie"),
    ("synthesis", "synteza"),
    ("influence", "wpływ"),
    ("crusader", "krzyżowiec"),
    ("redeemer", "odkupiciel"),
    ("awakened", "przebudzony"),
    ("awakener", "przebudziciel"),
    ("shaper", "kształtujący"),
    ("maven", "znawczyni"),
    ("elder", "starszy"),
    ("warlord", "dyktator"),
    ("hunter", "łowca"),
    ("timeless", "bezczasowy"),
    ("grasping", "chwytający"),
    ("funal", "grzybowy"),
    ("runic", "runiczny"),
    ("astrolabe", "astrolabium"),
    ("enshrouded", "spowity"),
    ("nameless", "bezimienny"),
    ("voidstone", "kamień pustki"),
    ("horror", "groza"),
    ("reverence", "cześć"),
    ("dread", "strach"),
    ("neglect", "zaniedbanie"),
    ("loneliness", "samotność"),
    ("feared", "budzący grozę"),
    ("trialmaster", "mistrz prób"),
    ("conqueror", "zdobywca"),
    ("elderSlayer", "pogromca starszych"),
    ("cortex", "kora mózgowa"),
    ("simulacrum", "symulakrum"),
    ("splinter", "odłamek"),
    ("breachstone", "kamień wyrwy"),
    ("flawless", "nieskazitelny"),
    ("blessing", "błogosławieństwo"),
    ("beachhead", "przyczółek"),
    ("harbinger", "zwiastun"),
    ("domain", "domena"),
    ("temple", "świątynia"),
    ("omnitect", "wszechbudowniczy"),
    ("menagerie", "menażeria"),
    ("imbued", "przesycony"),
    ("inscribed", "wpisany"),
    ("ultimatum", "ultimatum"),
    ("catalyst", "katalizator"),
    ("expedition", "ekspedycja"),
    ("excavated", "wykopany"),
    ("tainted", "skażony"),
    ("mirage", "miraż"),
    ("desecration", "zbezczeszczenie"),
    ("restoration", "odnowienie"),
    ("corruption", "zepsucie"),
    ("wombgift", "dar łona"),
    ("lavish", "wystawny"),
    ("ornate", "ozdobny"),
    ("revelatory", "objawieniowy"),
    ("banded", "obręczowany"),
    ("signet", "sygnet"),
    ("foulborn", "zrodzony ze zgnilizny"),
    ("genesis", "geneza"),
    ("graft", "przeszczep"),
    ("keepr", "strażnik"),

    # Divination Card themes
    ("ambition", "ambicja"),
    ("arrogance", "arogancja"),
    ("avarice", "chciwość"),
    ("benevolence", "dobroczynność"),
    ("betrayal", "zdrada"),
    ("blasphemy", "bluźnierstwo"),
    ("bounty", "nagroda"),
    ("carrion", "padlina"),
    ("clemency", "łaska"),
    ("conviction", "przekonanie"),
    ("covenant", "przymierze"),
    ("decay", "rozkład"),
    ("delirium", "majaczenie"),
    ("despair", "rozpacz"),
    ("destiny", "przeznaczenie"),
    ("devotion", "poświęcenie"),
    ("discord", "niezgoda"),
    ("enlightenment", "oświecenie"),
    ("epiphany", "objawienie"),
    ("eternity", "wieczność"),
    ("famine", "głód"),
    ("fidelity", "wierność"),
    ("fortune", "fortuna"),
    ("gluttony", "obżarstwo"),
    ("greed", "chciwość"),
    ("harmony", "harmonia"),
    ("hatred", "nienawiść"),
    ("hoarder", "zbieracz"),
    ("hubris", "pycha"),
    ("humility", "pokora"),
    ("immortal", "nieśmiertelny"),
    ("incantation", "inkantacja"),
    ("insanity", "obłęd"),
    ("isolation", "izolacja"),
    ("lament", "lament"),
    ("legacy", "dziedzictwo"),
    ("lust", "pożądanie"),
    ("malevolence", "wrogość"),
    ("maw", "paszcza"),
    ("mercy", "łaska"),
    ("misery", "nędza"),
    ("mortality", "śmiertelność"),
    ("nemesis", "nemezis"),
    ("oblivion", "zapomnienie"),
    ("paranoia", "paranoja"),
    ("penance", "pokuta"),
    ("pestilence", "zaraza"),
    ("piety", "pobożność"),
    ("pride", "duma"),
    ("privilege", "przywilej"),
    ("prosperity", "dobrobyt"),
    ("providence", "opatrzność"),
    ("prudence", "roztropność"),
    ("purity", "czystość"),
    ("rebirth", "odrodzenie"),
    ("reckoning", "rozrachunek"),
    ("redemption", "odkupienie"),
    ("regret", "żal"),
    ("remorse", "skrucha"),
    ("resilience", "odporność"),
    ("retribution", "odwet"),
    ("revelation", "objawienie"),
    ("sacrifice", "ofiara"),
    ("salvation", "zbawienie"),
    ("savagery", "dzikość"),
    ("schism", "schizma"),
    ("scourge", "dopust"),
    ("serenity", "spokój"),
    ("sloth", "lenistwo"),
    ("solitude", "samotność"),
    ("sorrow", "smutek"),
    ("supremacy", "zwierzchnictwo"),
    ("surrender", "poddanie"),
    ("sustenance", "pożywienie"),
    ("temptation", "pokusa"),
    ("torment", "męka"),
    ("tranquility", "spokój"),
    ("treachery", "zdrada"),
    ("tribulation", "udręka"),
    ("triumph", "triumf"),
    ("tyranny", "tyrania"),
    ("unity", "jedność"),
    ("vanity", "próżność"),
    ("vengeance", "zemsta"),
    ("vigil", "czuwanie"),
    ("vindication", "potwierdzenie"),
    ("violence", "przemoc"),
    ("virtue", "cnota"),
    ("void", "pustka"),
    ("whisper", "szept"),
    ("wrath", "gniew"),
    ("zealotry", "fanatyzm"),
]

# Merge, deduplicate, and output
with open(r"C:\Users\R6X\opencode\poe_deck_output.txt", 'r', encoding='utf-8') as f:
    existing = f.read()

import re
existing_cards = set()
for m in re.finditer(r'{ en: "([^"]+)", pl: "([^"]+)" }', existing):
    existing_cards.add(m.group(1).lower())

new_cards = []
for en, pl in extra_deck:
    if en.lower() not in existing_cards:
        new_cards.append((en.lower(), pl))
        existing_cards.add(en.lower())

new_cards.sort(key=lambda x: x[0])

print(f"Existing cards: {len(re.findall(r'{ en:', existing))}")
print(f"New unique cards to add: {len(new_cards)}")

# Write updated deck
with open(r"C:\Users\R6X\opencode\poe_deck_output.txt", 'w', encoding='utf-8') as f:
    all_cards = re.findall(r'{ en: "([^"]+)", pl: "([^"]+)" }', existing)
    combined = [(en.lower(), pl) for en, pl in all_cards] + new_cards
    seen = set()
    unique = []
    for en, pl in combined:
        if en not in seen:
            seen.add(en)
            unique.append((en, pl))
    unique.sort(key=lambda x: x[0])
    
    f.write("const WORDS_POE = [\n")
    for en, pl in unique:
        f.write(f'  {{ en: "{en}", pl: "{pl}" }},\n')
    f.write("];\n")
    
print(f"Total combined cards: {len(unique)}")
