#!/usr/bin/env python3
"""Generate Once Human flashcard deck - 400+ difficult EN words with PL translations."""

once_human_deck = [
    # ===== LORE & STORY =====
    ("starfall", "gwiezdny upadek"),
    ("stardust", "gwiezdny pył"),
    ("metahuman", "meta-człowiek"),
    ("rosetta", "Rosetta (korporacja)"),
    ("deviant", "odmieniec"),
    ("deviation", "odchylenie"),
    ("monolith", "monolit"),
    ("eternaland", "wiecznoziemie"),
    ("scenario", "scenariusz"),
    ("mitsuko", "Mitsuko (pierwsza meta-człowiek)"),
    ("igna", "Igna (antagonista)"),
    ("chaosweaver", "tkacz chaosu"),
    ("mayfly", "jętka"),
    ("rift", "szczelina"),
    ("anchor", "kotwica"),
    ("stronghold", "twierdza"),
    ("silo", "silos"),
    ("column", "kolumna"),
    ("vulture", "sęp"),
    ("cleansing", "oczyszczanie"),
    ("purge", "czystka"),
    ("crusade", "krucjata"),
    ("outpost", "placówka"),
    ("settlement", "osada"),
    ("sanctuary", "sanktuarium"),
    ("refuge", "schronienie"),
    ("bastion", "bastion"),
    ("citadel", "cytadela"),
    ("comrade", "towarzysz"),
    ("alliance", "sojusz"),
    ("faction", "frakcja"),
    ("rebellion", "bunt"),
    ("uprising", "powstanie"),
    ("insurrection", "insurekcja"),
    ("resistance", "ruch oporu"),
    ("collaborator", "kolaborant"),
    ("defector", "dezerter"),
    ("refugee", "uchodźca"),
    ("exile", "wygnaniec"),
    ("fugitive", "zbieg"),
    ("renegade", "renegat"),
    ("pariah", "parias"),
    ("outcast", "wyrzutek"),
    ("vagabond", "włóczęga"),
    ("wanderer", "wędrowiec"),
    ("nomad", "nomada"),
    ("pilgrim", "pielgrzym"),
    ("wayfarer", "podróżnik"),

    # ===== CREATURES & MONSTERS =====
    ("aberration", "aberracja"),
    ("anomaly", "anomalia"),
    ("mutation", "mutacja"),
    ("mutant", "mutant"),
    ("abomination", "ohyda"),
    ("monstrosity", "potworność"),
    ("behemoth", "behemot"),
    ("leviathan", "lewiatan"),
    ("colossus", "kolos"),
    ("titan", "tytan"),
    ("juggernaut", "siłacz"),
    ("crawler", "pełzacz"),
    ("stalker", "prześladowca"),
    ("lurker", "czający się"),
    ("prowler", "podkradacz"),
    ("roamer", "łazik"),
    ("wanderer", "wędrowiec"),
    ("scavenger", "padlinożerca"),
    ("carrion", "padlina"),
    ("predator", "drapieżnik"),
    ("parasite", "pasożyt"),
    ("infestation", "plaga"),
    ("swarm", "rój"),
    ("horde", "horda"),
    ("brood", "lęg"),
    ("spawn", "pomiot"),
    ("hive", "ul"),
    ("nest", "gniazdo"),
    ("lair", "legowisko"),
    ("den", "nora"),
    ("burrow", "kryjówka"),

    # ===== SCI-FI & COSMIC HORROR =====
    ("apocalyptic", "apokaliptyczny"),
    ("postapocalyptic", "postapokaliptyczny"),
    ("dystopian", "dystopijny"),
    ("cataclysm", "kataklizm"),
    ("catastrophe", "katastrofa"),
    ("calamity", "klęska"),
    ("extinction", "wyginięcie"),
    ("annihilation", "zagłada"),
    ("obliteration", "unicestwienie"),
    ("devastation", "dewastacja"),
    ("desolation", "spustoszenie"),
    ("ruination", "ruina"),
    ("contamination", "skażenie"),
    ("pollution", "zanieczyszczenie"),
    ("toxicity", "toksyczność"),
    ("radiation", "promieniowanie"),
    ("fallout", "opad"),
    ("contagion", "zaraza"),
    ("pandemic", "pandemia"),
    ("quarantine", "kwarantanna"),
    ("containment", "powstrzymanie"),
    ("isolation", "izolacja"),
    ("lockdown", "blokada"),
    ("breach", "wyrwa"),
    ("incursion", "wtargnięcie"),
    ("invasion", "inwazja"),
    ("assimilation", "asymilacja"),
    ("transmutation", "transmutacja"),
    ("metamorphosis", "metamorfoza"),
    ("evolution", "ewolucja"),
    ("ascension", "wzniesienie"),
    ("transcendence", "transcendencja"),
    ("enlightenment", "oświecenie"),
    ("awakening", "przebudzenie"),
    ("reckoning", "rozrachunek"),
    ("harbinger", "zwiastun"),
    ("omen", "omen"),
    ("prophecy", "proroctwo"),
    ("revelation", "objawienie"),
    ("apocalypse", "apokalipsa"),
    ("armageddon", "armagedon"),
    ("rapture", "uniesienie"),
    ("damnation", "potępienie"),
    ("salvation", "zbawienie"),
    ("redemption", "odkupienie"),
    ("penance", "pokuta"),
    ("atonement", "zadośćuczynienie"),
    ("absolution", "rozgrzeszenie"),
    
    # ===== COSMIC / DIMENSIONAL =====
    ("dimensional", "wymiarowy"),
    ("interdimensional", "międzywymiarowy"),
    ("cosmic", "kosmiczny"),
    ("celestial", "niebiański"),
    ("eldritch", "przerażający"),
    ("arcane", "tajemny"),
    ("occult", "okultystyczny"),
    ("esoteric", "ezoteryczny"),
    ("mystical", "mistyczny"),
    ("supernatural", "nadprzyrodzony"),
    ("paranormal", "paranormalny"),
    ("preternatural", "nadnaturalny"),
    ("ethereal", "nieziemski"),
    ("spectral", "widmowy"),
    ("phantasmal", "fantazmatyczny"),
    ("incorporeal", "bezcielesny"),
    ("manifestation", "manifestacja"),
    ("apparition", "zjawa"),
    ("wraith", "zjawa"),
    ("spectre", "widmo"),
    ("phantom", "fantom"),
    ("shade", "cień"),
    ("poltergeist", "poltergeist"),
    ("haunting", "nawiedzanie"),
    ("possession", "opętanie"),
    ("exorcism", "egzorcyzm"),
    ("banishment", "wypędzenie"),
    ("seance", "seans"),
    ("medium", "medium"),
    ("oracle", "wyrocznia"),
    ("seer", "jasnowidz"),
    ("prophet", "prorok"),
    ("augury", "wróżba"),
    ("divination", "wróżbiarstwo"),
    ("clairvoyance", "jasnowidzenie"),
    ("precognition", "prekognicja"),
    ("telepathy", "telepatia"),
    ("telekinesis", "telekineza"),
    ("psychic", "psychiczny"),
    ("psionic", "psioniczny"),
    
    # ===== SURVIVAL MECHANICS =====
    ("sanity", "poczytalność"),
    ("insanity", "obłęd"),
    ("madness", "szaleństwo"),
    ("delirium", "majaczenie"),
    ("hallucination", "halucynacja"),
    ("paranoia", "paranoja"),
    ("hysteria", "histeria"),
    ("frenzy", "furia"),
    ("berserk", "berserk"),
    ("mania", "mania"),
    ("dementia", "demencja"),
    ("amnesia", "amnezja"),
    ("lunacy", "obłęd"),
    ("psychosis", "psychoza"),
    ("trauma", "trauma"),
    ("affliction", "dolegliwość"),
    ("malady", "choroba"),
    ("ailment", "dolegliwość"),
    ("infirmity", "niemoc"),
    ("atrophy", "atrofia"),
    ("decay", "rozkład"),
    ("decomposition", "dekompozycja"),
    ("putrefaction", "gnicie"),
    ("corruption", "zepsucie"),
    ("blight", "zaraza"),
    ("pestilence", "zaraza"),
    ("famine", "głód"),
    ("starvation", "głodowanie"),
    ("dehydration", "odwodnienie"),
    ("malnutrition", "niedożywienie"),
    ("exhaustion", "wyczerpanie"),
    ("fatigue", "zmęczenie"),
    ("deprivation", "deprywacja"),
    ("hardship", "trudności"),
    ("adversity", "przeciwności"),
    ("endurance", "wytrzymałość"),
    ("resilience", "odporność"),
    ("fortitude", "męstwo"),
    ("tenacity", "zaciętość"),
    ("perseverance", "wytrwałość"),
    ("survivalist", "surwiwalista"),
    ("scavenging", "szperanie"),
    ("foraging", "zbieractwo"),
    ("provisioning", "zaopatrywanie"),
    ("subsistence", "egzystencja"),
    ("sustenance", "pożywienie"),

    # ===== CRAFTING & BASE BUILDING =====
    ("territory", "terytorium"),
    ("blueprint", "schemat"),
    ("memetic", "memetyczny"),
    ("cipher", "szyfr"),
    ("calibration", "kalibracja"),
    ("refinement", "uszlachetnianie"),
    ("assembly", "montaż"),
    ("disassembly", "demontaż"),
    ("fabrication", "wytwarzanie"),
    ("manufacturing", "produkcja"),
    ("construction", "konstrukcja"),
    ("fortification", "fortyfikacja"),
    ("reinforcement", "wzmocnienie"),
    ("barricade", "barykada"),
    ("bulwark", "przedmurze"),
    ("rampart", "wał obronny"),
    ("palisade", "palisada"),
    ("stockade", "ostrokół"),
    ("garrison", "garnizon"),
    ("encampment", "obozowisko"),
    ("bivouac", "biwak"),
    ("shelter", "schron"),
    ("makeshift", "prowizoryczny"),
    ("improvised", "improwizowany"),
    ("rudimentary", "prymitywny"),
    ("primitive", "prymitywny"),
    ("crude", "surowy"),
    ("makeshift", "prowizoryczny"),
    ("juryrigged", "naprawiony na szybko"),
    ("salvage", "odzysk"),
    ("repurpose", "przeznaczyć ponownie"),
    ("upcycle", "przetworzyć"),
    ("reclamation", "odzyskiwanie"),
    ("scrap", "złom"),
    ("debris", "gruz"),
    ("rubble", "rumowisko"),
    ("wreckage", "wrak"),
    ("remnant", "pozostałość"),
    ("vestige", "ślad"),
    ("artifact", "artefakt"),
    ("relic", "relikwia"),

    # ===== WEAPONS & COMBAT =====
    ("ballistic", "balistyczny"),
    ("projectile", "pocisk"),
    ("munition", "amunicja"),
    ("ordinance", "uzbrojenie"),
    ("firearm", "broń palna"),
    ("caliber", "kaliber"),
    ("magazine", "magazynek"),
    ("cartridge", "nabój"),
    ("casing", "łuska"),
    ("barrel", "lufa"),
    ("muzzle", "wylot lufy"),
    ("stock", "kolba"),
    ("trigger", "spust"),
    ("scope", "celownik"),
    ("suppressor", "tłumik"),
    ("recoil", "odrzut"),
    ("crosshair", "celownik"),
    ("trajectory", "trajektoria"),
    ("ricochet", "rykoszet"),
    ("penetration", "penetracja"),
    ("stoppingpower", "siła obalająca"),
    ("lethality", "śmiertelność"),
    ("arsenal", "arsenał"),
    ("armory", "zbrojownia"),
    ("fortress", "twierdza"),
    ("holdout", "punkt oporu"),
    ("bulwark", "przedmurze"),
    ("salvo", "salwa"),
    ("barrage", "kanonada"),
    ("volley", "salwa"),
    ("broadside", "burta"),
    ("onslaught", "natarcie"),
    ("assault", "szturm"),
    ("offensive", "ofensywa"),
    ("counterattack", "kontratak"),
    ("retreat", "odwrót"),
    ("rout", "rozgromienie"),
    ("skirmish", "potyczka"),
    ("ambush", "zasadzka"),
    ("flanking", "oskrzydlanie"),
    ("pincer", "kleszcze"),
    ("encirclement", "okrążenie"),
    ("siege", "oblężenie"),
    ("blockade", "blokada"),
    ("sortie", "wypad"),
    ("infiltration", "infiltracja"),
    ("exfiltration", "eksfiltracja"),
    ("extraction", "ekstrakcja"),
    ("evacuation", "ewakuacja"),

    # ===== ENVIRONMENT & BIOMES =====
    ("wasteland", "pustkowie"),
    ("wilderness", "dzicz"),
    ("badlands", "nieużytki"),
    ("barren", "jałowy"),
    ("desolate", "opustoszały"),
    ("inhospitable", "niegościnny"),
    ("hinterland", "głębia lądu"),
    ("outback", "odludzie"),
    ("frontier", "pogranicze"),
    ("perimeter", "obwód"),
    ("vicinity", "okolica"),
    ("plateau", "płaskowyż"),
    ("ridge", "grzbiet"),
    ("gorge", "wąwóz"),
    ("ravine", "jar"),
    ("chasm", "przepaść"),
    ("abyss", "otchłań"),
    ("canyon", "kanion"),
    ("crag", "urwisko"),
    ("cliff", "klif"),
    ("precipice", "przepaść"),
    ("overhang", "nawis"),
    ("ledge", "półka skalna"),
    ("cave", "jaskinia"),
    ("cavern", "pieczara"),
    ("grotto", "grota"),
    ("tunnel", "tunel"),
    ("burrow", "kryjówka"),
    ("excavation", "wykopalisko"),
    ("trench", "okop"),
    ("foxhole", "okop"),
    ("bunker", "bunkier"),
    ("shelter", "schron"),
    ("dugout", "ziemianka"),
    ("stronghold", "forteca"),
    ("compound", "kompleks"),
    ("enclave", "enklawa"),
    ("outpost", "placówka"),
    ("watchtower", "wieża strażnicza"),
    ("lookout", "punkt obserwacyjny"),

    # ===== WEATHER & CLIMATE =====
    ("tempest", "wichura"),
    ("squall", "szkwał"),
    ("gale", "wichura"),
    ("blizzard", "zamieć"),
    ("whiteout", "biała ciemność"),
    ("snowstorm", "śnieżyca"),
    ("avalanche", "lawina"),
    ("frostbite", "odmrożenie"),
    ("hypothermia", "hipotermia"),
    ("permafrost", "wieczna zmarzlina"),
    ("drought", "susza"),
    ("arid", "suchy"),
    ("scorching", "palący"),
    ("heatstroke", "udar cieplny"),
    ("monsoon", "monsun"),
    ("deluge", "potop"),
    ("downpour", "ulewa"),
    ("torrent", "rwący potok"),
    ("flashflood", "powódź błyskawiczna"),
    ("inundation", "zalanie"),
    ("hurricane", "huragan"),
    ("typhoon", "tajfun"),
    ("cyclone", "cyklon"),
    ("tornado", "tornado"),
    ("whirlwind", "trąba powietrzna"),
    ("sandstorm", "burza piaskowa"),
    ("duststorm", "burza pyłowa"),
    ("hailstorm", "gradobicie"),
    ("thunderstorm", "burza"),
    ("lightning", "błyskawica"),
    ("thunderbolt", "grom"),
    
    # ===== CORPORATE / EXPERIMENT =====
    ("corporation", "korporacja"),
    ("syndicate", "syndykat"),
    ("conglomerate", "konglomerat"),
    ("enterprise", "przedsiębiorstwo"),
    ("subsidiary", "filia"),
    ("franchise", "franczyza"),
    ("monopoly", "monopol"),
    ("cartel", "kartel"),
    ("conspiracy", "spisek"),
    ("collusion", "zmowa"),
    ("coverup", "ukrywanie"),
    ("whistleblower", "demaskator"),
    ("classified", "utajnione"),
    ("confidential", "poufne"),
    ("redacted", "ocenzurowane"),
    ("scrutiny", "kontrola"),
    ("investigation", "dochodzenie"),
    ("inquiry", "śledztwo"),
    ("audit", "audyt"),
    ("protocol", "protokół"),
    ("breach", "naruszenie"),
    ("compliance", "zgodność"),
    ("liability", "odpowiedzialność"),
    ("negligence", "zaniedbanie"),
    ("malpractice", "błąd w sztuce"),
    ("experimentation", "eksperymentowanie"),
    ("vivisection", "wiwisekcja"),
    ("dissection", "sekcja"),
    ("autopsy", "autopsja"),
    ("necropsy", "nekropsja"),
    ("biopsy", "biopsja"),
    ("specimen", "okaz"),
    ("sample", "próbka"),
    ("culture", "hodowla"),
    ("incubation", "inkubacja"),
    ("cultivation", "kultywacja"),
    ("synthesis", "synteza"),
    ("replication", "replikacja"),
    ("duplication", "duplikacja"),
    ("cloning", "klonowanie"),
    ("genetic", "genetyczny"),
    ("genome", "genom"),
    ("chromosome", "chromosom"),
    ("mutation", "mutacja"),
    ("mutagen", "mutagen"),
    ("carcinogen", "karcynogen"),
    ("antidote", "odtrutka"),
    ("antitoxin", "antytoksyna"),
    ("vaccine", "szczepionka"),
    ("inoculation", "szczepienie"),
    ("immunization", "uodpornienie"),
    ("antibody", "przeciwciało"),
    ("pathogen", "patogen"),
    ("virus", "wirus"),
    ("bacterium", "bakteria"),
    ("fungus", "grzyb"),
    ("spore", "zarodnik"),
    ("mold", "pleśń"),
    ("mildew", "pleśń"),

    # ===== PSYCHOLOGICAL & EMOTIONAL =====
    ("consciousness", "świadomość"),
    ("subconscious", "podświadomość"),
    ("identity", "tożsamość"),
    ("ego", "ego"),
    ("psyche", "psychika"),
    ("cognition", "poznanie"),
    ("perception", "percepcja"),
    ("intuition", "intuicja"),
    ("instinct", "instynkt"),
    ("impulse", "impuls"),
    ("compulsion", "przymus"),
    ("obsession", "obsesja"),
    ("fixation", "fiksacja"),
    ("delusion", "urojenie"),
    ("illusion", "iluzja"),
    ("mirage", "miraż"),
    ("phantasm", "fantazmat"),
    ("nightmare", "koszmar"),
    ("terror", "terror"),
    ("dread", "strach"),
    ("anguish", "udręka"),
    ("torment", "męka"),
    ("agony", "agonia"),
    ("distress", "rozpacz"),
    ("despair", "beznadzieja"),
    ("grief", "żal"),
    ("sorrow", "smutek"),
    ("melancholy", "melancholia"),
    ("nostalgia", "nostalgia"),
    ("wistfulness", "tęsknota"),
    ("longing", "pragnienie"),
    ("yearning", "tęsknota"),
    ("craving", "pragnienie"),
    ("desire", "pożądanie"),
    ("temptation", "pokusa"),
    ("aversion", "awersja"),
    ("revulsion", "odraza"),
    ("disgust", "obrzydzenie"),
    ("loathing", "wstręt"),
    ("contempt", "pogarda"),
    ("scorn", "pogarda"),
    ("disdain", "lekceważenie"),
    ("resentment", "uraza"),
    ("grudge", "uraza"),
    ("vengeance", "zemsta"),
    ("vendetta", "wendeta"),
    ("retaliation", "odwet"),
    ("retribution", "zapłata"),
    ("reckoning", "rozrachunek"),
    ("justice", "sprawiedliwość"),
    ("judgment", "osąd"),
    ("verdict", "werdykt"),
    ("sentence", "wyrok"),
    ("execution", "egzekucja"),
    
    # ===== ATMOSPHERIC / DESCRIPTIVE =====
    ("desolate", "opustoszały"),
    ("forsaken", "opuszczony"),
    ("abandoned", "porzucony"),
    ("derelict", "opuszczony"),
    ("dilapidated", "zniszczony"),
    ("decrepit", "zrujnowany"),
    ("crumbling", "rozpadający się"),
    ("decayed", "zbutwiały"),
    ("rotting", "gnijący"),
    ("festering", "ropiejący"),
    ("gangrenous", "zgorzelinowy"),
    ("putrid", "cuchnący"),
    ("foul", "ohydny"),
    ("rank", "śmierdzący"),
    ("noxious", "trujący"),
    ("toxic", "toksyczny"),
    ("venomous", "jadowity"),
    ("virulent", "zjadliwy"),
    ("lethal", "śmiertelny"),
    ("deadly", "zabójczy"),
    ("perilous", "niebezpieczny"),
    ("treacherous", "zdradliwy"),
    ("precarious", "niepewny"),
    ("ominous", "złowrogi"),
    ("sinister", "złowieszczy"),
    ("malevolent", "wrogi"),
    ("malicious", "złośliwy"),
    ("nefarious", "nikczemny"),
    ("diabolical", "diabelski"),
    ("infernal", "piekielny"),
    ("demonic", "demoniczny"),
    ("hellish", "piekielny"),
    ("ghastly", "upiorny"),
    ("gruesome", "makabryczny"),
    ("macabre", "makabryczny"),
    ("morbid", "morbityczny"),
    ("grisly", "przerażający"),
    ("ghoulish", "upiorny"),
    ("grotesque", "groteskowy"),
    ("hideous", "ohydny"),
    ("monstrous", "potworny"),
    ("horrifying", "przerażający"),
    ("terrifying", "przerażający"),
    ("dreadful", "straszny"),
    ("horrendous", "straszliwy"),
    ("appalling", "przerażający"),
    ("atrocious", "okropny"),
    ("abysmal", "otchłanny"),
    ("wretched", "nędzny"),
    ("miserable", "nieszczęśliwy"),
    ("pitiful", "żałosny"),
    ("lamentable", "opłakany"),
    ("deplorable", "godny ubolewania"),
    ("dismal", "ponury"),
    ("bleak", "ponury"),
    ("grim", "złowieszczy"),
    ("somber", "ponury"),
    ("gloomy", "posępny"),
    ("dreary", "ponury"),
    ("harsh", "surowy"),
    ("brutal", "brutalny"),
    ("relentless", "nieubłagany"),
    ("merciless", "bezlitosny"),
    ("ruthless", "bezwzględny"),
    ("pitiless", "nielitościwy"),
    ("remorseless", "bez skruchy"),
    ("unforgiving", "bezlitosny"),
    ("savage", "dziki"),
    ("barbaric", "barbarzyński"),
    ("feral", "zdziczały"),
    ("untamed", "nieokiełznany"),
    ("primal", "pierwotny"),
    ("primordial", "pierwotny"),
    ("ancient", "starożytny"),
    ("prehistoric", "prehistoryczny"),
    ("antediluvian", "przedpotopowy"),
    
    # ===== MEDICAL & BIOLOGICAL =====
    ("anatomy", "anatomia"),
    ("physiology", "fizjologia"),
    ("morphology", "morfologia"),
    ("pathology", "patologia"),
    ("etiology", "etiologia"),
    ("symptom", "objaw"),
    ("syndrome", "syndrom"),
    ("diagnosis", "diagnoza"),
    ("prognosis", "rokowanie"),
    ("remission", "remisja"),
    ("relapse", "nawrót"),
    ("deterioration", "pogorszenie"),
    ("degeneration", "degeneracja"),
    ("regeneration", "regeneracja"),
    ("rehabilitation", "rehabilitacja"),
    ("convalescence", "rekonwalescencja"),
    ("resuscitation", "reanimacja"),
    ("amputation", "amputacja"),
    ("mutilation", "okaleczenie"),
    ("laceration", "rany szarpane"),
    ("incision", "nacięcie"),
    ("abrasion", "otarcie"),
    ("contusion", "stłuczenie"),
    ("concussion", "wstrząs mózgu"),
    ("hemorrhage", "krwotok"),
    ("coagulation", "krzepnięcie"),
    ("clotting", "krzepnięcie"),
    ("scarring", "bliznowacenie"),
    ("gangrene", "zgorzel"),
    ("necrosis", "martwica"),
    ("sepsis", "sepsa"),
    ("infection", "infekcja"),
    ("inflammation", "zapalenie"),
    ("suppuration", "ropienie"),
    ("abscess", "ropień"),
    ("ulcer", "wrzód"),
    ("lesion", "zmiana"),
    ("tumor", "guz"),
    ("malignancy", "złośliwość"),
    ("metastasis", "przerzut"),
    ("carcinoma", "rak"),
    ("melanoma", "czerniak"),
    ("lymphoma", "chłoniak"),
    ("sarcoma", "mięsak"),
    # Also basic survival terms
    ("expedition", "ekspedycja"),
    ("traverse", "przemierzać"),
    ("navigate", "nawigować"),
    ("orienteering", "orientacja"),
    ("cartography", "kartografia"),
    ("topography", "topografia"),
    ("coordinates", "współrzędne"),
    ("waypoint", "punkt orientacyjny"),
    ("landmark", "punkt orientacyjny"),
    ("beacon", "latarnia"),
    ("signal", "sygnał"),
    ("transmission", "transmisja"),
    ("frequency", "częstotliwość"),
    ("interference", "zakłócenia"),
    ("static", "zakłócenia"),
    ("distortion", "zniekształcenie"),
    ("anomaly", "anomalia"),
    ("fluctuation", "fluktuacja"),
    ("disruption", "zakłócenie"),
]

# Deduplicate
seen = set()
unique = []
for en, pl in once_human_deck:
    key = en.lower()
    if key not in seen:
        seen.add(key)
        unique.append((key, pl))

unique.sort(key=lambda x: x[0])

import os
out_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../js/decks/oncehuman.js"))
with open(out_path, 'w', encoding='utf-8') as f:
    f.write("const WORDS_ONCEHUMAN = [\n")
    for en, pl in unique:
        f.write(f'  {{ en: "{en}", pl: "{pl}" }},\n')
    f.write("];\n")

print(f"Total unique cards: {len(unique)}")
print(f"Written to {out_path}")
