#!/usr/bin/env python3
"""Generate Final Fantasy flashcard deck - 600+ difficult EN words with PL translations."""

deck = [
    # ===== MAGIC / SPELLS =====
    ("fire", "ogień"),
    ("fira", "fira (postać ognia)"),
    ("firaga", "firaga (potężny ogień)"),
    ("flame", "płomień"),
    ("inferno", "piekło"),
    ("conflagration", "pożoga"),
    ("blizzard", "zamieć"),
    ("blizzara", "blizzara (postać lodu)"),
    ("blizzaga", "blizzaga (potężny lód)"),
    ("frost", "mróz"),
    ("glacier", "lodowiec"),
    ("thunder", "grom"),
    ("thundara", "thundara (postać pioruna)"),
    ("thundaga", "thundaga (potężny piorun)"),
    ("lightning", "błyskawica"),
    ("bolt", "piorun"),
    ("water", "woda"),
    ("aqua", "akwa"),
    ("deluge", "potop"),
    ("flood", "powódź"),
    ("aero", "aero (wiatr)"),
    ("tornado", "tornado"),
    ("tempest", "wichura"),
    ("cyclone", "cyklon"),
    ("hurricane", "huragan"),
    ("quake", "trzęsienie"),
    ("stone", "kamień"),
    ("boulder", "głaz"),
    ("meteor", "meteor"),
    ("comet", "kometa"),
    ("ultima", "ultima (ostateczne zaklęcie)"),
    ("flare", "rozbłysk"),
    ("holy", "święty"),
    ("sacred", "święcony"),
    ("divine", "boski"),
    ("dark", "mrok"),
    ("shadow", "cień"),
    ("void", "pustka"),
    ("abyss", "otchłań"),
    ("necromancy", "nekromancja"),
    ("hex", "urok"),
    ("curse", "klątwa"),
    ("jinx", "zły urok"),
    ("poison", "trucizna"),
    ("venom", "jad"),
    ("toxin", "toksyna"),
    ("biolysis", "bioliza"),
    ("drain", "wysysanie"),
    ("osmosis", "osmoza"),
    ("absorb", "absorbować"),
    ("aspir", "aspir"),
    # healing
    ("cure", "leczenie"),
    ("cura", "cura (mocniejsze leczenie)"),
    ("curaga", "curaga (potężne leczenie)"),
    ("regen", "regeneracja"),
    ("heal", "uzdrowić"),
    ("restoration", "odnowienie"),
    ("renewal", "odnowa"),
    ("revive", "ożywić"),
    ("resurrection", "wskrzeszenie"),
    ("phoenix", "feniks"),
    ("esuna", "esuna (leczenie statusów)"),
    ("remedy", "lekarstwo"),
    ("panacea", "panaceum"),
    ("antidote", "odtrutka"),
    ("cleansing", "oczyszczanie"),
    ("purification", "oczyszczenie"),
    ("sanctuary", "sanktuarium"),
    ("benediction", "błogosławieństwo"),
    ("blessing", "błogosławieństwo"),
    # buffs
    ("haste", "przyspieszenie"),
    ("slow", "spowolnienie"),
    ("protect", "ochrona"),
    ("shell", "skorupa"),
    ("reflect", "odbicie"),
    ("barrier", "bariera"),
    ("shield", "tarcza"),
    ("ward", "osłona"),
    ("dispel", "rozproszenie"),
    ("mightyguard", "potężna straż"),
    ("invincibility", "nietykalność"),
    ("aura", "aura"),
    ("wall", "ściana"),
    ("rage", "szał"),
    ("fury", "furia"),
    ("berserk", "szał bojowy"),
    ("bravery", "odwaga"),
    ("faith", "wiara"),
    ("float", "lewitacja"),
    ("vanish", "zniknięcie"),
    ("invisibility", "niewidzialność"),
    ("silence", "cisza"),
    ("mute", "niemota"),
    ("sleep", "sen"),
    ("slumber", "drzemka"),
    ("blind", "oślepienie"),
    ("petrify", "skamienienie"),
    ("paralysis", "paraliż"),
    ("confusion", "dezorientacja"),
    ("berserk", "szał"),
    ("doom", "zagłada"),
    ("condemn", "potępienie"),
    ("gravity", "grawitacja"),
    ("dimensional", "wymiarowy"),
    # blue magic
    ("goblin punch", "cios goblina"),
    ("matra magic", "magia matra"),
    ("aqualung", "płuco wodne"),
    ("bad breath", "nieświeży oddech"),
    ("white wind", "biały wiatr"),
    ("mighthammer", "potężny młot"),
    ("limit break", "przełamanie limitu"),
    ("overdrive", "nadbieg"),

    # ===== SUMMONS / EIDOLONS / ESPERS =====
    ("ifrit", "ifrit (dżin ognia)"),
    ("shiva", "shiva (bogini lodu)"),
    ("ramuh", "ramuh (mędrzec gromu)"),
    ("leviathan", "lewiatan"),
    ("bahamut", "bahamut (król smoków)"),
    ("odin", "odyn (jeździec)"),
    ("titan", "tytan"),
    ("phoenix", "feniks"),
    ("alexander", "alexander (święta forteca)"),
    ("diabolos", "diabolos (władca snów)"),
    ("carbycle", "karbunkuł"),
    ("siren", "syrena"),
    ("fenrir", "fenrir"),
    ("gilgamesh", "gilgamesz"),
    ("enkidu", "enkidu"),
    ("valefor", "valefor"),
    ("ixion", "iksjon"),
    ("animus", "animus"),
    ("yojimbo", "yojimbo"),
    ("daigoro", "daigoro"),
    ("magus", "magus"),
    ("quetzalcoatl", "quetzalcoatl"),
    ("cerberus", "cerber"),
    ("doomtrain", "pociąg zagłady"),
    ("eden", "eden"),
    ("hades", "hades"),
    ("typhon", "tyfon"),
    ("kjata", "kjata"),
    ("bismarck", "bismarck"),
    ("ravana", "ravana"),
    ("susano", "susano"),
    ("lakshmi", "lakszmi"),
    ("garuda", "garuda"),
    ("ruby", "rubinowy"),
    ("emerald", "szmaragdowy"),
    ("sapphire", "szafirowy"),
    ("diamond", "diamentowy"),
    ("gold", "złoty"),
    ("silver", "srebrny"),
    ("crystal", "kryształ"),
    ("gem", "klejnot"),
    ("jewel", "klejnot"),
    ("esper", "esper"),
    ("eidolon", "eidolon"),
    ("aeon", "eon"),
    ("avatar", "awatar"),
    ("summoning", "przyzywanie"),
    ("conjuration", "czarowanie"),
    ("evocation", "ewokacja"),
    ("invocation", "inwokacja"),

    # ===== JOB CLASSES =====
    ("warrior", "wojownik"),
    ("monk", "mnich"),
    ("thief", "złodziej"),
    ("white mage", "biały mag"),
    ("black mage", "czarny mag"),
    ("red mage", "czerwony mag"),
    ("blue mage", "niebieski mag"),
    ("green mage", "zielony mag"),
    ("time mage", "mag czasu"),
    ("summoner", "przywoływacz"),
    ("dragoon", "dragun"),
    ("paladin", "paladyn"),
    ("dark knight", "mroczny rycerz"),
    ("knight", "rycerz"),
    ("samurai", "samuraj"),
    ("ninja", "ninja"),
    ("assassin", "skrytobójca"),
    ("ranger", "strażnik"),
    ("hunter", "łowca"),
    ("archer", "łucznik"),
    ("bard", "bard"),
    ("dancer", "tancerz"),
    ("geomancer", "geomanta"),
    ("beastmaster", "zaklinacz bestii"),
    ("berserker", "berserker"),
    ("mystic knight", "mistyczny rycerz"),
    ("sage", "mędrzec"),
    ("chemist", "chemik"),
    ("oracle", "wyrocznia"),
    ("calculator", "kalkulator"),
    ("mediator", "mediator"),
    ("mimic", "naśladowca"),
    ("freelancer", "wolny strzelec"),
    ("onion knight", "cebulowy rycerz"),
    ("sorceress", "czarodziejka"),
    ("gunbreaker", "łamacz broni"),
    ("dancer", "tancerz"),
    ("machinist", "mechanik"),
    ("astrologian", "astrolog"),
    ("reaper", "żniwiarz"),
    ("viper", "żmija"),
    ("pictomancer", "piktomanta"),
    ("soldier", "żołnierz"),
    ("spellblade", "mag-mieczownik"),
    ("alchemist", "alchemik"),
    ("illusionist", "iluzjonista"),
    ("puppetmaster", "lalkarz"),
    ("corsair", "korsarz"),
    ("scholar", "uczony"),
    ("druid", "druid"),
    ("shaman", "szaman"),
    ("cleric", "kleryk"),
    ("priest", "kapłan"),
    ("bishop", "biskup"),
    ("templar", "templariusz"),
    ("gladiator", "gladiator"),
    ("marauder", "maruder"),
    ("pugilist", "pięściarz"),
    ("rogue", "łotr"),
    ("lancer", "włócznik"),
    ("arcanist", "arkanista"),
    ("thaumaturge", "taumaturg"),
    ("conjurer", "czarodziej"),

    # ===== WEAPONS =====
    ("excalibur", "excalibur"),
    ("masamune", "masamune"),
    ("ultima weapon", "broń ultima"),
    ("buster sword", "miecz niszczyciel"),
    ("gunblade", "gunblade"),
    ("savethequeen", "ocal królową"),
    ("lionheart", "lwie serce"),
    ("brotherhood", "braterstwo"),
    ("revolver", "rewolwer"),
    ("caladbolg", "caladbolg"),
    ("nirvana", "nirwana"),
    ("worldchampion", "mistrz świata"),
    ("apocalypse", "apokalipsa"),
    ("ragnarok", "ragnarök"),
    ("zanketsuken", "zanketsuken"),
    ("murasame", "murasame"),
    ("katana", "katana"),
    ("nodachi", "nodachi"),
    ("rapier", "rapier"),
    ("sabre", "szabla"),
    ("scimitar", "sejmitar"),
    ("claymore", "claymore"),
    ("broadsword", "miecz szeroki"),
    ("longsword", "długi miecz"),
    ("greatsword", "wielki miecz"),
    ("dagger", "sztylet"),
    ("kunai", "kunai"),
    ("shuriken", "shuriken"),
    ("boomerang", "bumerang"),
    ("chakram", "czakram"),
    ("spear", "włócznia"),
    ("lance", "lanca"),
    ("javelin", "oszczep"),
    ("halberd", "halabarda"),
    ("glaive", "glewia"),
    ("trident", "trójząb"),
    ("axe", "topór"),
    ("battleaxe", "topór bojowy"),
    ("tomahawk", "tomahawk"),
    ("mace", "maczuga"),
    ("flail", "kiścień"),
    ("morning star", "gwiazda poranna"),
    ("warhammer", "młot bojowy"),
    ("sledgehammer", "młot oburęczny"),
    ("staff", "laska"),
    ("rod", "różdżka"),
    ("sceptre", "berło"),
    ("grimoire", "grimuar"),
    ("tome", "tom"),
    ("codex", "kodeks"),
    ("whip", "bicz"),
    ("chain", "łańcuch"),
    ("claw", "szpon"),
    ("knuckle", "kastet"),
    ("cestus", "cestus"),
    ("bow", "łuk"),
    ("longbow", "długi łuk"),
    ("crossbow", "kusza"),
    ("cannon", "armata"),
    ("blitzball", "blitzball"),

    # ===== CREATURES =====
    ("chocobo", "chocobo"),
    ("moogle", "moogle"),
    ("cactuar", "cactuar"),
    ("tonberry", "tonberry"),
    ("malboro", "malboro"),
    ("behemoth", "behemot"),
    ("coeurl", "coeurl"),
    ("bomb", "bomba"),
    ("ahriman", "ahriman"),
    ("flan", "flan"),
    ("pudding", "pudding"),
    ("jelly", "galareta"),
    ("slime", "szlam"),
    ("goblin", "goblin"),
    ("imp", "chochlik"),
    ("ogre", "ogr"),
    ("giant", "olbrzym"),
    ("troll", "troll"),
    ("golem", "golem"),
    ("mandragora", "mandragora"),
    ("cactoid", "kaktusowaty"),
    ("sahagin", "sahagin"),
    ("zu", "zu"),
    ("adamantoise", "adamantozaura"),
    ("basilisk", "bazyliszek"),
    ("cockatrice", "kokatris"),
    ("morbol", "morbol"),
    ("ochu", "ochu"),
    ("raging", "rozwścieczony"),
    ("wyrm", "żmij"),
    ("dragon", "smok"),
    ("drake", "smok"),
    ("wyvern", "wywerna"),
    ("hydra", "hydra"),
    ("chimera", "chimera"),
    ("manticore", "mantykora"),
    ("griffin", "gryf"),
    ("sphinx", "sfinks"),
    ("minotaur", "minotaur"),
    ("cyclops", "cyklop"),
    ("gargoyle", "gargulec"),
    ("demon", "demon"),
    ("devil", "diabeł"),
    ("fiend", "czart"),
    ("daemon", "demon"),
    ("archfiend", "arcydiabeł"),
    ("ghost", "duch"),
    ("wraith", "zjawa"),
    ("spectre", "widmo"),
    ("phantom", "fantom"),
    ("ghoul", "ghul"),
    ("zombie", "zombie"),
    ("skeleton", "szkielet"),
    ("lich", "lisz"),
    ("vampire", "wampir"),
    ("succubus", "sukub"),
    ("incubus", "inkub"),
    ("lamia", "lamia"),
    ("medusa", "meduza"),
    ("gorgon", "gorgona"),
    ("kraken", "kraken"),
    ("sea serpent", "wąż morski"),
    ("sahagin", "sahagin"),
    ("undine", "undyna"),
    ("salamander", "salamandra"),
    ("sylph", "sylfida"),
    ("gnome", "gnom"),
    ("elemental", "żywiołak"),
    ("spirit", "duch"),
    ("fairy", "wróżka"),
    ("pixie", "piks"),
    ("nymph", "nimfa"),
    ("dryad", "driada"),
    ("carbuncle", "karbunkuł"),
    ("cu chulainn", "cu chulainn"),
    ("cerberus", "cerber"),
    ("pegazus", "pegaz"),
    ("unicorn", "jednorożec"),
    ("kitsune", "kitsune"),
    ("nine tails", "dziewięć ogonów"),
    ("catoblepas", "katoblepas"),
    ("iron giant", "żelazny olbrzym"),
    ("warmech", "ciepłomech"),
    ("death machine", "maszyna śmierci"),
    ("guardian", "strażnik"),
    ("sentinel", "wartownik"),
    ("protector", "obrońca"),
    ("keeper", "opiekun"),

    # ===== ITEMS =====
    ("potion", "mikstura"),
    ("hipotion", "mocna mikstura"),
    ("xpotion", "super mikstura"),
    ("megalixir", "megaeliksir"),
    ("elixir", "eliksir"),
    ("ether", "eter"),
    ("turboether", "turboeter"),
    ("phoenix down", "pióro feniksa"),
    ("remedy", "lekarstwo"),
    ("eyedrops", "krople do oczu"),
    ("echoherb", "echo-zioło"),
    ("goldneedle", "złota igła"),
    ("maidens kiss", "pocałunek dziewicy"),
    ("cornucopia", "róg obfitości"),
    ("tent", "namiot"),
    ("cottage", "chata"),
    ("sleeping bag", "śpiwór"),
    ("grenade", "granat"),
    ("shrapnel", "szrapnel"),
    ("darkmatter", "ciemna materia"),
    ("gysahl greens", "gysahl greens"),
    ("sylkis greens", "sylkis greens"),
    ("mimmet greens", "mimmet greens"),
    ("pahsana greens", "pahsana greens"),
    ("tantal greens", "tantal greens"),
    ("reagan greens", "reagan greens"),
    ("ribbon", "wstążka"),
    ("celestriad", "celestriada"),
    ("genji glove", "rękawica genji"),
    ("economizer", "ekonomizer"),
    ("sprint shoes", "buty do sprintu"),
    ("exp egg", "jajko exp"),
    ("lunar harp", "księżycowa harfa"),
    ("memento ring", "pierścień pamiątkowy"),

    # ===== LORE CONCEPTS =====
    ("crystal", "kryształ"),
    ("warrior of light", "wojownik światła"),
    ("lifestream", "strumień życia"),
    ("mako", "mako"),
    ("jenova", "jenova"),
    ("ancients", "starożytni"),
    ("cetra", "cetra"),
    ("solider", "żołnierz"),
    ("sephiroth", "sephiroth"),
    ("materia", "materia"),
    ("weapon", "broń/monstrum"),
    ("shinra", "shinra"),
    ("avalanche", "lawina/avalanche"),
    ("seed", "nasiono/seed"),
    ("guardian force", "siła opiekuńcza"),
    ("sorceress", "czarodziejka"),
    ("junction", "połączenie"),
    ("draw", "pobieranie"),
    ("sphere grid", "siatka sfer"),
    ("pyreflies", "ogniste muchy"),
    ("farplane", "daleka płaszczyzna"),
    ("spira", "spira"),
    ("zanarkand", "zanarkand"),
    ("pilgrimage", "pielgrzymka"),
    ("summoner", "przywoływacz"),
    ("guardian", "strażnik"),
    ("sin", "grzech/sin"),
    ("unsent", "nieposłani"),
    ("hym of the fayth", "hymn wiernych"),
    ("ivalice", "ivalice"),
    ("lcie", "l'cie"),
    ("falcie", "fal'cie"),
    ("crystallis", "crystallis"),
    ("pulse", "puls"),
    ("cocoon", "kokon"),
    ("etros", "etros"),
    ("linzei", "linzei"),
    ("bunevelze", "bunevelze"),
    ("aetheryte", "eteryt"),
    ("primal", "pierwotny"),
    ("ascian", "ascianin"),
    ("hydaelyn", "hydaelyn"),
    ("zodiark", "zodiark"),
    ("scion", "scion"),
    ("grandcompany", "wielka kompania"),
    ("echo", "echo"),
    ("blessing of light", "błogosławieństwo światła"),
    ("darkness", "ciemność"),
    ("umbral", "umbralny"),
    ("astral", "astralny"),
    ("calamity", "klęska"),
    ("rejoining", "ponowne łączenie"),
    ("reflection", "odbicie/refleksja"),
    ("shard", "odłamek"),
    ("dawn of souls", "świt dusz"),
    ("palamecia", "palamecia"),
    ("rebel army", "armia rebeliantów"),
    ("gestahl", "gestahl"),
    ("magitek", "magitek"),
    ("espionage", "szpiegostwo"),
    ("resistance", "ruch oporu"),
    ("returners", "powracający"),
    ("espionage", "szpiegostwo"),
    ("terra", "ziemia"),
    ("branford", "branford"),
    ("figaro", "figaro"),
    ("doman", "doman"),
    ("dalmasca", "dalmasca"),
    ("archadia", "archadia"),
    ("rozarria", "rozarria"),
    ("nabradia", "nabradia"),
    ("nethicite", "netycyt"),
    ("mist", "mgła/mgiełka"),

    # ===== LOCATIONS =====
    ("midgar", "midgar"),
    ("nibelheim", "nibelheim"),
    ("gold saucer", "złoty spodek"),
    ("wutai", "wutai"),
    ("cosmo canyon", "kanion cosmo"),
    ("ancient forest", "starożytny las"),
    ("northern cave", "północna jaskinia"),
    ("rocket town", "miasto rakietowe"),
    ("balamb", "balamb"),
    ("galbadia", "galbadia"),
    ("esthar", "esthar"),
    ("fisherman horizon", "horyzont rybaka"),
    ("deling", "deling"),
    ("timber kingdom", "królestwo timber"),
    ("alexandria", "aleksandria"),
    ("lindblum", "lindblum"),
    ("burmecia", "burmecia"),
    ("cleyra", "cleyra"),
    ("treno", "treno"),
    ("daguerreo", "daguerreo"),
    ("madainsari", "madainsari"),
    ("conde petie", "conde petie"),
    ("besaid", "besaid"),
    ("kilika", "kilika"),
    ("luca", "luca"),
    ("mihen", "mihen"),
    ("djose", "djose"),
    ("guadosalam", "guadosalam"),
    ("thunder plains", "równiny gromu"),
    ("macalania", "makalania"),
    ("bikanel", "bikanel"),
    ("bevelle", "bevelle"),
    ("calm lands", "spokojne ziemie"),
    ("gagazet", "gagazet"),
    ("omega ruins", "ruiny omega"),
    ("rabanastre", "rabanastre"),
    ("bhujerba", "bhujerba"),
    ("phoncoast", "wybrzeże fon"),
    ("eruyt", "eruyt"),
    ("jahara", "jahara"),
    ("golmore", "golmore"),
    ("paramina", "paramina"),
    ("ozmone", "ozmone"),
    ("ridorana", "ridorana"),
    ("nalbina", "nalbina"),
    ("baltheir", "baltheir"),
    ("fran", "fran"),
    ("gridania", "gridania"),
    ("limsalominsa", "limsa lominsa"),
    ("uldah", "uldah"),
    ("ishgard", "ishgard"),
    ("ala mhigo", "ala mhigo"),
    ("dravania", "dravania"),
    ("thanalan", "thanalan"),
    ("mor dhona", "mor dhona"),
    ("eorzea", "eorzea"),
    ("norvrandt", "norvrandt"),
    ("garlemald", "garlemald"),
    ("insomnia", "insomnia"),
    ("lucis", "lucis"),
    ("tenebrae", "tenebrae"),
    ("accordion", "akordeon"),
    ("altissia", "altissia"),
    ("niflheim", "niflheim"),
    ("lestallum", "lestallum"),
    ("hammerhead", "hammerhead"),
    ("rosaria", "rosaria"),
    ("sanbreque", "sanbreque"),
    ("walood", "walood"),
    ("dhalmek", "dhalmek"),
    ("iron kingdom", "żelazne królestwo"),
    ("crystaline dominion", "kryształowe dominium"),
    ("cornelia", "cornelia"),
    ("altair", "altair"),
    ("fynn", "fynn"),
    ("mysidia", "mysidia"),
    ("troia", "troia"),
    ("baron", "baron"),
    ("damcyan", "damcyan"),
    ("fabul", "fabul"),
    ("eblan", "eblan"),
    ("kaipo", "kaipo"),
    ("agart", "agart"),
    ("sylx", "sylx"),
    ("cleyra", "cleyra"),
    ("dali", "dali"),
    ("memoria", "memoria"),

    # ===== ATMOSPHERIC / THEMATIC =====
    ("destiny", "przeznaczenie"),
    ("fate", "los"),
    ("prophecy", "proroctwo"),
    ("oracle", "wyrocznia"),
    ("vision", "wizja"),
    ("premonition", "przeczucie"),
    ("omen", "omen"),
    ("augury", "wróżba"),
    ("divination", "wróżbiarstwo"),
    ("pilgrimage", "pielgrzymka"),
    ("quest", "wyprawa"),
    ("journey", "podróż"),
    ("expedition", "ekspedycja"),
    ("odyssey", "odyseja"),
    ("adventure", "przygoda"),
    ("exploration", "eksploracja"),
    ("discovery", "odkrycie"),
    ("treasure", "skarb"),
    ("relic", "relikwia"),
    ("artifact", "artefakt"),
    ("heirloom", "pamiątka rodowa"),
    ("legacy", "dziedzictwo"),
    ("heritage", "spuścizna"),
    ("lineage", "ród"),
    ("dynasty", "dynastia"),
    ("sovereign", "władca"),
    ("monarch", "monarcha"),
    ("emperor", "cesarz"),
    ("empire", "imperium"),
    ("kingdom", "królestwo"),
    ("dominion", "dominium"),
    ("realm", "królestwo"),
    ("throne", "tron"),
    ("crown", "korona"),
    ("royalty", "rodzina królewska"),
    ("nobility", "szlachta"),
    ("aristocracy", "arystokracja"),
    ("regent", "regent"),
    ("succession", "sukcesja"),
    ("ascension", "wzniesienie"),
    ("coronation", "koronacja"),
    ("rebellion", "bunt"),
    ("revolution", "rewolucja"),
    ("uprising", "powstanie"),
    ("insurrection", "insurekcja"),
    ("coupdetat", "zamach stanu"),
    ("conquest", "podbój"),
    ("subjugation", "ujarzmienie"),
    ("liberation", "wyzwolenie"),
    ("emancipation", "emancypacja"),
    ("independence", "niepodległość"),
    ("oppression", "ucisk"),
    ("tyranny", "tyrania"),
    ("despotism", "despotyzm"),
    ("dictatorship", "dyktatura"),
    ("resistance", "ruch oporu"),
    ("underground", "podziemie"),
    ("conspiracy", "spisek"),
    ("betrayal", "zdrada"),
    ("treason", "zdrada"),
    ("allegiance", "wierność"),
    ("loyalty", "lojalność"),
    ("devotion", "poświęcenie"),
    ("sacrifice", "ofiara"),
    ("redemption", "odkupienie"),
    ("atonement", "zadośćuczynienie"),
    ("forgiveness", "przebaczenie"),
    ("reconciliation", "pojednanie"),
    ("harmony", "harmonia"),
    ("balance", "równowaga"),
    ("equilibrium", "równowaga"),
    ("chaos", "chaos"),
    ("order", "porządek"),
    ("cosmos", "kosmos"),
    ("creation", "stworzenie"),
    ("destruction", "zniszczenie"),
    ("obliteration", "unicestwienie"),
    ("genesis", "geneza"),
    ("apocalypse", "apokalipsa"),
    ("cataclysm", "kataklizm"),
    ("calamity", "klęska"),
    ("deluge", "potop"),
    ("catastrophe", "katastrofa"),
    ("extinction", "wyginięcie"),
    ("rebirth", "odrodzenie"),
    ("renewal", "odnowa"),
    ("restoration", "przywrócenie"),
    ("revival", "ożywienie"),
    ("reincarnation", "reinkarnacja"),
    ("transcendence", "transcendencja"),
    ("transformation", "transformacja"),
    ("metamorphosis", "metamorfoza"),
    ("evolution", "ewolucja"),
    ("enlightenment", "oświecenie"),
    ("awakening", "przebudzenie"),
    ("revelation", "objawienie"),
    ("epiphany", "epifania"),
    ("manifestation", "manifestacja"),
    ("incarnation", "wcielenie"),
    ("embodiment", "ucieleśnienie"),
    ("vessel", "naczynie"),
    ("avatar", "awatar"),
    ("eternity", "wieczność"),
    ("infinity", "nieskończoność"),
    ("immortality", "nieśmiertelność"),
    ("mortality", "śmiertelność"),
    ("transience", "przemijalność"),
    ("ephemeral", "ulotny"),
    ("fleeting", "przelotny"),
    ("permanence", "trwałość"),
    ("legacy", "dziedzictwo"),
    ("memory", "wspomnienie"),
    ("remembrance", "pamięć"),
    ("oblivion", "zapomnienie"),
    ("anamnesis", "anamneza"),
    ("nostalgia", "nostalgia"),
    ("melancholy", "melancholia"),
    ("sorrow", "smutek"),
    ("grief", "żal"),
    ("despair", "rozpacz"),
    ("hope", "nadzieja"),
    ("courage", "odwaga"),
    ("bravery", "męstwo"),
    ("heroism", "bohaterstwo"),
    ("valor", "waleczność"),
    ("gallantry", "rycerskość"),
    ("chivalry", "rycerskość"),
    ("honor", "honor"),
    ("duty", "obowiązek"),
    ("vow", "ślub"),
    ("oath", "przysięga"),
    ("pledge", "przyrzeczenie"),
    ("promise", "obietnica"),
    ("covenant", "przymierze"),
    ("pact", "pakt"),
    ("alliance", "sojusz"),
    ("camaraderie", "koleżeństwo"),
    ("fellowship", "wspólnota"),
    ("brotherhood", "braterstwo"),
    ("unity", "jedność"),
    ("solidarity", "solidarność"),
]

# Deduplicate
seen = set()
unique = []
for en, pl in deck:
    key = en.lower().replace(" ", "").replace("-", "").replace("'", "")
    if key not in seen:
        seen.add(key)
        unique.append((en, pl))

unique.sort(key=lambda x: x[0])

import os
out_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../js/decks/finalfantasy.js"))
with open(out_path, 'w', encoding='utf-8') as f:
    f.write("const WORDS_FINALFANTASY = [\n")
    for en, pl in unique:
        f.write(f'  {{ en: "{en}", pl: "{pl}" }},\n')
    f.write("];\n")

print(f"Total unique cards: {len(unique)}")
print(f"Written to {out_path}")
