#!/usr/bin/env python3
"""Generate 7 Days to Die flashcard deck - 500+ difficult EN words with PL translations."""

deck = [
    # ===== ZOMBIES & ENEMIES =====
    ("zombie", "zombie"),
    ("undead", "nieumarły"),
    ("feral", "zdziczały"),
    ("radiated", "napromieniowany"),
    ("charged", "naładowany"),
    ("infernal", "piekielny"),
    ("bloated", "rozdęty"),
    ("spitter", "plwacz"),
    ("screamer", "krzykacz"),
    ("demoliser", "burzyciel"),
    ("hazmat", "gazoszczelny"),
    ("wight", "widmo"),
    ("biker", "motocyklista"),
    ("lumberjack", "drwal"),
    ("stripper", "obdzieracz"),
    ("cheerleader", "cheerleaderka"),
    ("crawler", "pełzacz"),
    ("parasite", "pasożyt"),
    ("mutant", "mutant"),
    ("aberration", "aberracja"),
    ("abomination", "ohyda"),
    ("behemoth", "behemot"),
    ("colossus", "kolos"),
    ("brute", "brutal"),
    ("marauder", "maruder"),
    ("raider", "najeźdźca"),
    ("bandit", "bandyta"),
    ("outlaw", "banita"),
    ("renegade", "renegat"),
    ("scavenger", "padlinożerca"),
    ("cadaver", "zwłoki"),
    ("carcass", "ścierwo"),
    ("corpse", "ciało"),
    ("necrosis", "martwica"),
    ("decomposition", "rozkład"),
    ("putrefaction", "gnicie"),
    ("infestation", "plaga"),
    ("swarm", "rój"),
    ("horde", "horda"),
    ("brood", "lęg"),
    ("spawn", "pomiot"),
    ("carrion", "padlina"),
    ("rotting", "gnijący"),
    ("festering", "ropiejący"),
    ("diseased", "chory"),
    ("infected", "zainfekowany"),
    ("contagious", "zaraźliwy"),
    ("virulent", "zjadliwy"),
    ("pestilent", "zarazowy"),
    ("plague", "dżuma"),
    ("pathogen", "patogen"),
    ("virus", "wirus"),
    ("epidemic", "epidemia"),
    ("pandemic", "pandemia"),
    ("outbreak", "wybuch epidemii"),
    ("quarantine", "kwarantanna"),
    ("containment", "powstrzymanie"),
    ("isolation", "izolacja"),

    # ===== SURVIVAL MECHANICS =====
    ("survival", "przetrwanie"),
    ("survivor", "ocalały"),
    ("dysentery", "czerwonka"),
    ("dehydration", "odwodnienie"),
    ("starvation", "głodowanie"),
    ("malnutrition", "niedożywienie"),
    ("hypothermia", "hipotermia"),
    ("frostbite", "odmrożenie"),
    ("heatstroke", "udar cieplny"),
    ("hyperthermia", "przegrzanie"),
    ("exhaustion", "wyczerpanie"),
    ("fatigue", "zmęczenie"),
    ("stamina", "wytrzymałość"),
    ("wellness", "kondycja"),
    ("vitality", "witalność"),
    ("endurance", "wytrzymałość"),
    ("fortitude", "męstwo"),
    ("resilience", "odporność"),
    ("tenacity", "zaciętość"),
    ("perseverance", "wytrwałość"),
    ("deprivation", "deprywacja"),
    ("insomnia", "bezsenność"),
    ("hallucination", "halucynacja"),
    ("delirium", "majaczenie"),
    ("concussion", "wstrząs"),
    ("hemorrhage", "krwotok"),
    ("dressing", "opatrunek"),
    ("splint", "szyna"),
    ("cast", "gips"),
    ("tourniquet", "opaska uciskowa"),
    ("bandage", "bandaż"),
    ("gauze", "gaza"),
    ("suture", "szew"),
    ("stitch", "ścig"),
    ("antiseptic", "środek odkażający"),
    ("disinfectant", "dezynfektor"),
    ("antibiotic", "antybiotyk"),
    ("painkiller", "środek przeciwbólowy"),
    ("analgesic", "analgetyk"),
    ("sedative", "środek uspokajający"),
    ("stimulant", "stymulant"),
    ("narcotic", "narkotyk"),
    ("morphine", "morfina"),
    ("adrenaline", "adrenalina"),
    ("epinephrine", "epinefryna"),
    ("antidote", "odtrutka"),
    ("antivenom", "antytoksyna"),
    ("serum", "surowica"),
    ("vaccine", "szczepionka"),
    ("inoculation", "szczepienie"),
    ("immunity", "odporność"),
    ("affliction", "dolegliwość"),
    ("ailment", "dolegliwość"),
    ("malady", "choroba"),
    ("infirmity", "niemoc"),
    ("debilitation", "osłabienie"),

    # ===== CRAFTING & BUILDING =====
    ("crafting", "rzemiosło"),
    ("forge", "kuźnia"),
    ("workbench", "stół warsztatowy"),
    ("crucible", "tygiel"),
    ("cement", "cement"),
    ("concrete", "beton"),
    ("cobblestone", "bruk"),
    ("mortar", "zaprawa"),
    ("rebar", "pręt zbrojeniowy"),
    ("scaffold", "rusztowanie"),
    ("frame", "rama"),
    ("keystone", "zwornik"),
    ("pillar", "filar"),
    ("truss", "kratownica"),
    ("girder", "dźwigar"),
    ("beam", "belka"),
    ("rafter", "krokiew"),
    ("joist", "legar"),
    ("stud", "słupek"),
    ("drywall", "płyta gipsowa"),
    ("paneling", "boazeria"),
    ("siding", "siding"),
    ("masonry", "murarstwo"),
    ("brickwork", "ceglarstwo"),
    ("fortification", "fortyfikacja"),
    ("reinforcement", "wzmocnienie"),
    ("barricade", "barykada"),
    ("bulwark", "przedmurze"),
    ("rampart", "wał obronny"),
    ("palisade", "palisada"),
    ("stockade", "ostrokół"),
    ("trench", "okop"),
    ("foxhole", "okop"),
    ("dugout", "ziemianka"),
    ("bunker", "bunkier"),
    ("pillbox", "schron bojowy"),
    ("parapet", "parapet"),
    ("loophole", "strzelnica"),
    ("embrasure", "otwór strzelniczy"),
    ("drawbridge", "most zwodzony"),
    ("portcullis", "krata"),
    ("gatehouse", "budynek bramny"),
    ("bastion", "bastion"),
    ("citadel", "cytadela"),
    ("fortress", "twierdza"),
    ("stronghold", "stronghold"),
    ("compound", "kompleks"),
    ("enclave", "enklawa"),
    ("outpost", "placówka"),
    ("garrison", "garnizon"),
    ("encampment", "obozowisko"),
    ("shelter", "schronienie"),
    ("makeshift", "prowizoryczny"),
    ("improvised", "improwizowany"),
    ("juryrigged", "sklecony"),
    ("rudimentary", "prymitywny"),
    ("scavenged", "wyszukany"),
    ("salvage", "odzysk"),
    ("repurpose", "zmienić przeznaczenie"),
    ("upcycle", "przetworzyć"),
    ("reclamation", "odzyskiwanie"),
    ("deconstruction", "dekonstrukcja"),
    ("demolition", "demolka"),
    ("wreckage", "wrak"),
    ("debris", "gruz"),
    ("rubble", "rumowisko"),

    # ===== WEAPONS & COMBAT =====
    ("blunderbuss", "garłacz"),
    ("sledgehammer", "młot oburęczny"),
    ("machete", "maczeta"),
    ("crossbow", "kusza"),
    ("marksman", "strzelec wyborowy"),
    ("magnum", "magnum"),
    ("shotgun", "strzelba"),
    ("carbine", "karabinek"),
    ("pistol", "pistolet"),
    ("revolver", "rewolwer"),
    ("rifle", "karabin"),
    ("sniper", "snajper"),
    ("machinegun", "karabin maszynowy"),
    ("submachinegun", "pistolet maszynowy"),
    ("flamethrower", "miotacz ognia"),
    ("grenade", "granat"),
    ("molotov", "koktajl Mołotowa"),
    ("dynamite", "dynamit"),
    ("explosive", "materiał wybuchowy"),
    ("detonator", "detonator"),
    ("payload", "ładunek"),
    ("warhead", "głowica"),
    ("ballistic", "balistyczny"),
    ("projectile", "pocisk"),
    ("munition", "amunicja"),
    ("ordinance", "uzbrojenie"),
    ("firearm", "broń palna"),
    ("caliber", "kaliber"),
    ("magazine", "magazynek"),
    ("cartridge", "nabój"),
    ("casing", "łuska"),
    ("barrel", "lufa"),
    ("muzzle", "wylot lufy"),
    ("breech", "zamek"),
    ("bolt", "zamek"),
    ("chamber", "komora"),
    ("trigger", "spust"),
    ("grip", "chwyt"),
    ("stock", "kolba"),
    ("buttstock", "kolba"),
    ("foregrip", "chwyt przedni"),
    ("bipod", "dwójnóg"),
    ("tripod", "trójnóg"),
    ("scope", "celownik"),
    ("suppressor", "tłumik"),
    ("silencer", "tłumik"),
    ("compensator", "kompensator"),
    ("muzzlebrake", "hamulec wylotowy"),
    ("recoil", "odrzut"),
    ("crosshair", "celownik"),
    ("trajectory", "trajektoria"),
    ("ricochet", "rykoszet"),
    ("penetration", "penetracja"),
    ("lethality", "śmiertelność"),
    ("arsenal", "arsenał"),
    ("armory", "zbrojownia"),
    ("cache", "skrytka"),
    ("stash", "składzik"),
    ("hoard", "zapas"),
    ("stockpile", "zapas"),
    ("ammunition", "amunicja"),

    # ===== TRAPS & DEFENSE =====
    ("trap", "pułapka"),
    ("snare", "sidła"),
    ("ambush", "zasadzka"),
    ("boobytrap", "pułapka minowa"),
    ("landmine", "mina lądowa"),
    ("tripwire", "linka potykowa"),
    ("barbedwire", "drut kolczasty"),
    ("razorwire", "drut żyletkowy"),
    ("concertina", "concertina"),
    ("spike", "kolec"),
    ("caltrop", "kalka"),
    ("barricade", "barykada"),
    ("turret", "wieżyczka"),
    ("sentry", "wartownik"),
    ("lookout", "punkt obserwacyjny"),
    ("watchtower", "wieża strażnicza"),
    ("searchlight", "reflektor"),
    ("floodlight", "światło rozproszone"),
    ("motionsensor", "czujnik ruchu"),
    ("proximity", "zbliżeniowy"),
    ("infrared", "podczerwień"),
    ("thermal", "termiczny"),
    ("surveillance", "nadzór"),
    ("reconnaissance", "rozpoznanie"),
    ("scouting", "zwiad"),
    ("patrol", "patrol"),
    ("perimeter", "obwód"),
    ("defensive", "obronny"),
    ("fortified", "ufortyfikowany"),
    ("entrenched", "okopany"),
    ("besieged", "oblężony"),
    ("garrisoned", "obsadzony"),
    ("manned", "obsadzony"),
    ("automated", "zautomatyzowany"),

    # ===== VEHICLES =====
    ("vehicle", "pojazd"),
    ("bicycle", "rower"),
    ("minibike", "minimotocykl"),
    ("motorcycle", "motocykl"),
    ("gyrocopter", "żyrokopter"),
    ("chassis", "podwozie"),
    ("handlebar", "kierownica"),
    ("carburetor", "gaźnik"),
    ("accelerator", "przyspiesznik"),
    ("accumulator", "akumulator"),
    ("battery", "bateria"),
    ("engine", "silnik"),
    ("suspension", "zawieszenie"),
    ("axle", "oś"),
    ("wheel", "koło"),
    ("tire", "opona"),
    ("inner tube", "dętka"),
    ("luggage", "bagażnik"),
    ("cargo", "ładunek"),
    ("transport", "transport"),
    ("convoy", "konwój"),
    ("caravan", "karawana"),
    ("haul", "przewóz"),
    ("tow", "holować"),
    ("winch", "wyciągarka"),
    ("crane", "dźwig"),
    ("forklift", "wózek widłowy"),
    ("excavator", "koparka"),
    ("bulldozer", "buldożer"),
    ("tractor", "traktor"),

    # ===== BIOMES & ENVIRONMENT =====
    ("biome", "biom"),
    ("wasteland", "pustkowie"),
    ("wilderness", "dzicz"),
    ("badlands", "nieużytki"),
    ("desert", "pustynia"),
    ("pine forest", "las sosnowy"),
    ("temperate", "umiarkowany"),
    ("grassland", "łąka"),
    ("prairie", "preria"),
    ("savanna", "sawanna"),
    ("tundra", "tundra"),
    ("taiga", "tajga"),
    ("swamp", "bagno"),
    ("marsh", "mokradło"),
    ("bog", "torfowisko"),
    ("wetland", "teren podmokły"),
    ("floodplain", "równina zalewowa"),
    ("plateau", "płaskowyż"),
    ("ridge", "grzbiet"),
    ("gorge", "wąwóz"),
    ("ravine", "jar"),
    ("canyon", "kanion"),
    ("mesa", "mesa"),
    ("butte", "ostańiec"),
    ("chasm", "przepaść"),
    ("abyss", "otchłań"),
    ("crag", "urwisko"),
    ("cliff", "klif"),
    ("precipice", "przepaść"),
    ("overhang", "nawis"),
    ("ledge", "półka skalna"),
    ("cavern", "pieczara"),
    ("grotto", "grota"),
    ("fissure", "szczelina"),
    ("crevasse", "rozpadlina"),
    ("hinterland", "głębia lądu"),
    ("frontier", "pogranicze"),
    ("scorched", "wypalony"),
    ("irradiated", "napromieniowany"),
    ("contaminated", "skażony"),
    ("polluted", "zanieczyszczony"),
    ("barren", "jałowy"),
    ("desolate", "opustoszały"),
    ("inhospitable", "niegościnny"),
    ("arid", "suchy"),
    ("torrid", "gorący"),
    ("frigid", "lodowaty"),

    # ===== RESOURCES & MATERIALS =====
    ("resource", "surowiec"),
    ("material", "materiał"),
    ("raw", "surowy"),
    ("refined", "rafinowany"),
    ("processed", "przetworzony"),
    ("ore", "ruda"),
    ("ingot", "sztabka"),
    ("sheet metal", "blacha"),
    ("scrap", "złom"),
    ("scrap iron", "żelastwo"),
    ("coal", "węgiel"),
    ("nitrate", "azotan"),
    ("shale", "łupek"),
    ("polymer", "polimer"),
    ("plastic", "plastik"),
    ("rubber", "guma"),
    ("silicone", "silikon"),
    ("resin", "żywica"),
    ("epoxy", "epoksyd"),
    ("adhesive", "klej"),
    ("solder", "lut"),
    ("flux", "topnik"),
    ("duct tape", "taśma klejąca"),
    ("mechanical parts", "części mechaniczne"),
    ("electrical parts", "części elektryczne"),
    ("electronic", "elektroniczny"),
    ("circuit board", "płytka drukowana"),
    ("capacitor", "kondensator"),
    ("resistor", "rezystor"),
    ("transistor", "tranzystor"),
    ("diode", "dioda"),
    ("relay", "przekaźnik"),
    ("connector", "złącze"),
    ("terminal", "zacisk"),
    ("insulator", "izolator"),
    ("conductor", "przewodnik"),
    ("semiconductor", "półprzewodnik"),
    ("magnet", "magnes"),
    ("alloy", "stop"),
    ("composite", "kompozyt"),
    ("fiberglass", "włókno szklane"),
    ("kevlar", "kevlar"),
    ("carbon fiber", "włókno węglowe"),
    ("titanium", "tytan"),
    ("tungsten", "wolfram"),
    ("chromium", "chrom"),
    ("aluminum", "aluminium"),
    ("bronze", "brąz"),
    ("cast iron", "żeliwo"),
    ("galvanized", "ocynkowany"),

    # ===== ELECTRICITY & POWER =====
    ("electricity", "elektryczność"),
    ("generator", "generator"),
    ("solar panel", "panel słoneczny"),
    ("battery bank", "bank baterii"),
    ("power source", "źródło zasilania"),
    ("wattage", "moc"),
    ("voltage", "napięcie"),
    ("amperage", "natężenie"),
    ("circuit", "obwód"),
    ("wiring", "okablowanie"),
    ("cable", "kabel"),
    ("switch", "przełącznik"),
    ("relay", "przekaźnik"),
    ("fuse", "bezpiecznik"),
    ("breaker", "wyłącznik"),
    ("transformer", "transformator"),
    ("inverter", "falownik"),
    ("rectifier", "prostownik"),
    ("converter", "przetwornik"),
    ("regulator", "regulator"),
    ("electrode", "elektroda"),
    ("anode", "anoda"),
    ("cathode", "katoda"),
    ("grounding", "uziemienie"),
    ("short circuit", "zwarcie"),
    ("overload", "przeciążenie"),
    ("surge", "przepięcie"),

    # ===== LORE & STORY =====
    ("apocalypse", "apokalipsa"),
    ("apocalyptic", "apokaliptyczny"),
    ("postapocalyptic", "post-apokaliptyczny"),
    ("cataclysm", "kataklizm"),
    ("catastrophe", "katastrofa"),
    ("calamity", "klęska"),
    ("doomsday", "dzień sądu"),
    ("armageddon", "armagedon"),
    ("extinction", "wyginięcie"),
    ("annihilation", "zagłada"),
    ("devastation", "dewastacja"),
    ("desolation", "spustoszenie"),
    ("ruination", "ruina"),
    ("dystopian", "dystopijny"),
    ("navezgane", "Navezgane"),
    ("septdiurnal", "septdiurnalny"),
    ("cassadore", "Cassadore"),
    ("duke", "książę"),
    ("warlord", "dyktator"),
    ("tyrant", "tyran"),
    ("antagonist", "antagonista"),
    ("nuclear", "atomowy"),
    ("fallout", "opad promieniotwórczy"),
    ("shelter", "schron"),
    ("vault", "krypta"),
    ("blood moon", "krwawy księżyc"),
    ("horde night", "noc hordy"),
    ("onslaught", "natarcie"),
    ("siege", "oblężenie"),
    ("resistance", "ruch oporu"),
    ("militia", "milicja"),
    ("squad", "oddział"),
    ("platoon", "pluton"),
    ("brigade", "brygada"),
    ("regiment", "pułk"),
    ("battalion", "batalion"),
    ("division", "dywizja"),

    # ===== SKILLS & PERKS =====
    ("perception", "percepcja"),
    ("fortitude", "męstwo"),
    ("agility", "zwinność"),
    ("intellect", "intelekt"),
    ("strength", "siła"),
    ("dexterity", "zręczność"),
    ("constitution", "kondycja"),
    ("attribute", "atrybut"),
    ("perk", "perk"),
    ("mastery", "mistrzostwo"),
    ("scavenging", "szperanie"),
    ("mining", "górnictwo"),
    ("harvesting", "zbieractwo"),
    ("salvage", "odzysk"),
    ("pummel", "okładanie"),
    ("boomstick", "strzelba"),
    ("penetrator", "przebijacz"),
    ("skullcrusher", "miażdżyciel czaszek"),
    ("decimator", "dziesiątkarz"),
    ("executioner", "kat"),
    ("reaper", "żniwiarz"),
    ("brawler", "awanturnik"),
    ("infiltrator", "infiltrator"),
    ("demolitionist", "specjalista od burzenia"),
    ("engineer", "inżynier"),
    ("architect", "architekt"),
    ("builder", "budowniczy"),
    ("mechanic", "mechanik"),
    ("gunslinger", "rewolwerowiec"),
    ("sharpshooter", "strzelec wyborowy"),
    ("marksman", "strzelec"),
    ("ranger", "strażnik"),
    ("tracker", "tropiciel"),
    ("hunter", "łowca"),
    ("stalker", "prześladowca"),
    ("assassin", "skrytobójca"),
    ("medic", "medyk"),
    ("surgeon", "chirurg"),
    ("physician", "lekarz"),
    ("farmer", "rolnik"),
    ("rancher", "ranczer"),
    ("butcher", "rzeźnik"),
    ("tanner", "garbarz"),
    ("blacksmith", "kowal"),
    ("armorer", "płatnerz"),
    ("gunsmith", "rusznikarz"),
    ("tinkerer", "majsterkowicz"),

    # ===== ATMOSPHERIC / DESCRIPTIVE =====
    ("derelict", "opuszczony"),
    ("decrepit", "zrujnowany"),
    ("dilapidated", "zniszczony"),
    ("crumbling", "rozpadający się"),
    ("decayed", "zbutwiały"),
    ("forsaken", "opuszczony"),
    ("abandoned", "porzucony"),
    ("deserted", "wyludniony"),
    ("barricaded", "zabarykadowany"),
    ("boarded up", "zabity deskami"),
    ("condemned", "przeznaczony do rozbiórki"),
    ("uninhabitable", "niezdatny do mieszkania"),
    ("squatted", "zajęty przez squattersów"),
    ("looted", "splądrowany"),
    ("ransacked", "ograbiony"),
    ("plundered", "złupiony"),
    ("ravaged", "spustoszony"),
    ("scorched", "wypalony"),
    ("charred", "zwęglony"),
    ("ashen", "popielaty"),
    ("smoldering", "tlący się"),
    ("smoking", "dymiący"),
    ("reeking", "cuchnący"),
    ("stench", "smród"),
    ("putrid", "zgniły"),
    ("foul", "ohydny"),
    ("noxious", "trujący"),
    ("ominous", "złowrogi"),
    ("sinister", "złowieszczy"),
    ("foreboding", "złowróżbny"),
    ("menacing", "groźny"),
    ("portentous", "złowieszczy"),
    ("eerie", "niesamowity"),
    ("uncanny", "niepokojący"),
    ("haunting", "prześladujący"),
    ("macabre", "makabryczny"),
    ("gruesome", "makabryczny"),
    ("ghastly", "upiorny"),
    ("ghoulish", "upiorny"),
    ("grotesque", "groteskowy"),
    ("hideous", "ohydny"),
    ("monstrous", "potworny"),
    ("horrendous", "straszliwy"),
    ("dreadful", "straszny"),
    ("grim", "ponury"),
    ("bleak", "posępny"),
    ("dreary", "ponury"),
    ("somber", "ponury"),
    ("dismal", "ponury"),
    ("harrowing", "wstrząsający"),
    ("grueling", "wyczerpujący"),
    ("brutal", "brutalny"),
    ("relentless", "nieubłagany"),
    ("merciless", "bezlitosny"),
    ("ruthless", "bezwzględny"),
    ("pitiless", "nielitościwy"),
    ("unforgiving", "bezlitosny"),
    ("savage", "dziki"),
    ("barbaric", "barbarzyński"),

    # ===== BUILDING / STRUCTURAL =====
    ("structural", "strukturalny"),
    ("integrity", "integralność"),
    ("collapse", "zawalenie"),
    ("foundation", "fundament"),
    ("footing", "ława"),
    ("loadbearing", "nośny"),
    ("cantilever", "wspornik"),
    ("buttress", "przypora"),
    ("retaining wall", "mur oporowy"),
    ("embankment", "nasyp"),
    ("excavation", "wykop"),
    ("backfill", "zasypka"),
    ("compaction", "zagęszczenie"),
    ("grouting", "fugowanie"),
    ("caulking", "uszczelnianie"),
    ("insulation", "izolacja"),
    ("waterproof", "wodoodporny"),
    ("sealant", "uszczelniacz"),
    ("ventilation", "wentylacja"),
    ("ductwork", "kanały wentylacyjne"),
    ("plumbing", "hydraulika"),
    ("piping", "rurociąg"),
    ("valve", "zawór"),
    ("faucet", "kran"),
    ("drainage", "odwodnienie"),
    ("sewer", "kanalizacja"),
    ("cesspool", "szambo"),
    ("septic", "septyczny"),
    ("filtration", "filtracja"),
    ("purification", "oczyszczanie"),
    ("distillation", "destylacja"),
    ("desalination", "odsalanie"),
    ("sterilization", "sterylizacja"),

    # ===== AGRICULTURE / FARMING =====
    ("agriculture", "rolnictwo"),
    ("cultivation", "uprawa"),
    ("sowing", "siew"),
    ("reaping", "żniwa"),
    ("harvest", "żniwa"),
    ("yield", "plon"),
    ("crop", "uprawa"),
    ("fertilizer", "nawóz"),
    ("compost", "kompost"),
    ("mulch", "ściółka"),
    ("irrigation", "nawadnianie"),
    ("sprinkler", "zraszacz"),
    ("greenhouse", "szklarnia"),
    ("hothouse", "cieplarnia"),
    ("orchard", "sad"),
    ("grove", "gaj"),
    ("vineyard", "winnica"),
    ("pasture", "pastwisko"),
    ("barn", "stodoła"),
    ("silo", "silos"),
    ("granary", "spichlerz"),
    ("coop", "kurnik"),
    ("pen", "zagroda"),
    ("stable", "stajnia"),
    ("corral", "zagroda"),
    ("livestock", "inwentarz"),
    ("poultry", "drób"),
    ("venison", "dziczyzna"),
    ("carcass", "tusza"),
    ("butchering", "rozbiór tuszy"),
    ("skinning", "skórowanie"),
    ("tanning", "garbowanie"),
    ("leatherworking", "kaletnictwo"),
    ("taxidermy", "taksydermia"),

    # ===== MILITARY / TACTICAL =====
    ("tactical", "taktyczny"),
    ("strategic", "strategiczny"),
    ("maneuver", "manewr"),
    ("flanking", "oskrzydlanie"),
    ("pincer", "kleszcze"),
    ("encirclement", "okrążenie"),
    ("breach", "wyrwa"),
    ("incursion", "wtargnięcie"),
    ("infiltration", "infiltracja"),
    ("exfiltration", "eksfiltracja"),
    ("extraction", "ewakuacja"),
    ("evacuation", "ewakuacja"),
    ("rendezvous", "punkt spotkania"),
    ("drop zone", "strefa zrzutu"),
    ("landing zone", "strefa lądowania"),
    ("forward base", "wysunięta baza"),
    ("staging area", "rejon wyjściowy"),
    ("rally point", "punkt zbiórki"),
    ("safehouse", "kryjówka"),
    ("redoubt", "reduta"),
    ("salient", "występ"),
    ("no mans land", "ziemia niczyja"),
    ("crossfire", "ogień krzyżowy"),
    ("overwatch", "ubezpieczenie"),
    ("suppressing fire", "ogień zaporowy"),
    ("covering fire", "ogień osłaniający"),
    ("salvo", "salwa"),
    ("barrage", "kanonada"),
    ("volley", "salwa"),
    ("broadside", "burta"),
    ("cannonade", "kanonada"),
    ("skirmish", "potyczka"),
    ("sortie", "wypad"),
]

# Deduplicate
seen = set()
unique = []
for en, pl in deck:
    key = en.lower().replace(" ", "")
    if key not in seen:
        seen.add(key)
        unique.append((en, pl))

unique.sort(key=lambda x: x[0])

import os
out_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../js/decks/sevendays.js"))
with open(out_path, 'w', encoding='utf-8') as f:
    f.write("const WORDS_7DAYS = [\n")
    for en, pl in unique:
        f.write(f'  {{ en: "{en}", pl: "{pl}" }},\n')
    f.write("];\n")

print(f"Total unique cards: {len(unique)}")
print(f"Written to {out_path}")
