# Generate the final PoE flashcard deck with Polish translations
# This takes the extracted words and pairs them with translations

poe_deck = [
    # Combat & Mechanics
    ("ailment", "dolegliwość"),
    ("ignite", "podpalić"),
    ("chill", "schłodzić"),
    ("shock", "porazić"),
    ("poison", "zatruć"),
    ("bleeding", "krwawienie"),
    ("onslaught", "natarcie"),
    ("fortify", "ufortyfikować"),
    ("leech", "wysysać"),
    ("culling", "zabójczy cios"),
    ("pierce", "przebijać"),
    ("fork", "rozwidlać"),
    ("chain", "łańcuch"),
    ("maim", "okaleczyć"),
    ("hinder", "spowalniać"),
    ("exposure", "ekspozycja"),
    ("warcry", "okrzyk bojowy"),
    ("rage", "szał"),
    ("endurance", "wytrzymałość"),
    ("frenzy", "furia"),
    ("crush", "zmiażdżyć"),
    ("aftershock", "wstrząs wtórny"),
    ("shatter", "rozdrobnić"),
    ("detonator", "detonator"),
    ("shapeshift", "zmiennokształtność"),
    ("remnant", "pozostałość"),

    # Defensive
    ("armour", "pancerz"),
    ("evasion", "unik"),
    ("penetration", "penetracja"),
    ("regeneration", "regeneracja"),
    ("bulwark", "przedmurze"),
    ("bastion", "bastion"),
    ("fortress", "twierdza"),
    ("rampart", "wał obronny"),
    ("garrison", "garnizon"),
    ("aegis", "egida"),
    ("guardian", "strażnik"),
    ("protector", "obrońca"),
    ("sentinel", "wartownik"),
    ("warden", "strażnik"),
    ("keeper", "opiekun"),
    ("vigil", "czuwanie"),

    # Damage & Elements
    ("physical", "fizyczny"),
    ("elemental", "żywiołowy"),
    ("chaos", "chaos"),
    ("overkill", "nadmiar obrażeń"),
    ("reflection", "odbicie"),
    ("maelstrom", "wir"),
    ("vortex", "wir"),
    ("inferno", "piekło"),
    ("scorch", "przypiec"),
    ("blaze", "płomień"),
    ("ember", "żar"),
    ("glacier", "lodowiec"),
    ("avalanche", "lawina"),
    ("blizzard", "zamieć"),
    ("frost", "mróz"),
    ("hoarfrost", "szron"),
    ("tempest", "wichura"),
    ("hurricane", "huragan"),
    ("typhoon", "tajfun"),
    ("lightning", "błyskawica"),
    ("thunder", "grom"),
    ("cascade", "kaskada"),
    ("surge", "przypływ"),
    ("zenith", "zenit"),
    ("volcano", "wulkan"),
    ("magma", "magma"),
    ("cinder", "żużel"),

    # League Mechanics
    ("breach", "wyrwa"),
    ("abyss", "otchłań"),
    ("blight", "zaraza"),
    ("scourge", "dopust"),
    ("crucible", "tygiel"),
    ("harvest", "żniwa"),
    ("heist", "skok"),
    ("delve", "kopalnia"),
    ("incursion", "wtargnięcie"),
    ("sanctum", "sanktuarium"),
    ("ultimatum", "ultimatum"),
    ("divination", "wróżba"),
    ("prophecy", "proroctwo"),
    ("omen", "omen"),
    ("essence", "esencja"),
    ("fragment", "fragment"),
    ("splinter", "odłamek"),
    ("catalyst", "katalizator"),
    ("relic", "relikwia"),
    ("talisman", "talizman"),

    # Lore & Story
    ("cataclysm", "kataklizm"),
    ("corruption", "zepsucie"),
    ("blasphemy", "bluźnierstwo"),
    ("heresy", "herezja"),
    ("heretic", "heretyk"),
    ("penance", "pokuta"),
    ("consecrate", "poświęcać"),
    ("desecrate", "bezcześcić"),
    ("redemption", "odkupienie"),
    ("salvation", "zbawienie"),
    ("atonement", "pokuta"),
    ("communion", "komunia"),
    ("covenant", "przymierze"),
    ("sacrifice", "ofiara"),
    ("offering", "ofiarowanie"),
    ("tribute", "danina"),
    ("pact", "pakt"),
    ("legacy", "dziedzictwo"),
    ("lineage", "ród"),
    ("dynasty", "dynastia"),
    ("ancestry", "pochodzenie"),
    ("heritage", "dziedzictwo"),
    ("dominion", "dominium"),
    ("sovereign", "władca"),
    ("realm", "królestwo"),
    ("empire", "imperium"),
    ("citadel", "cytadela"),
    ("throne", "tron"),
    ("crown", "korona"),
    ("sceptre", "berło"),
    ("mantle", "płaszcz"),
    ("regalia", "regalia"),
    ("temple", "świątynia"),
    ("cathedral", "katedra"),
    ("shrine", "kapliczka"),
    ("monastery", "klasztor"),
    ("abbey", "opactwo"),
    ("crypt", "krypta"),
    ("tomb", "grobowiec"),
    ("catacomb", "katakumby"),
    ("mausoleum", "mauzoleum"),
    ("labyrinth", "labirynt"),
    ("chasm", "przepaść"),
    ("void", "pustka"),
    ("oblivion", "zapomnienie"),
    ("annihilation", "zagłada"),
    ("apocalypse", "apokalipsa"),
    ("armageddon", "armagedon"),
    ("famine", "głód"),
    ("pestilence", "zaraza"),
    ("plague", "plaga"),
    ("decay", "rozkład"),
    ("depravity", "deprawacja"),

    # Character Classes & Archetypes
    ("juggernaut", "siłacz"),
    ("berserker", "berserker"),
    ("chieftain", "wódz"),
    ("raider", "najeźdźca"),
    ("deadeye", "strzelec wyborowy"),
    ("pathfinder", "tropiciel"),
    ("saboteur", "sabotażysta"),
    ("assassin", "skrytobójca"),
    ("trickster", "oszust"),
    ("occultist", "okultysta"),
    ("elementalist", "żywiołak"),
    ("necromancer", "nekromanta"),
    ("inquisitor", "inkwizytor"),
    ("hierophant", "hierofant"),
    ("champion", "czempion"),
    ("gladiator", "gladiator"),
    ("slayer", "pogromca"),
    ("executioner", "kat"),
    ("reaper", "żniwiarz"),
    ("zealot", "zelota"),
    ("disciple", "uczeń"),
    ("acolyte", "akolita"),
    ("templar", "templariusz"),
    ("crusader", "krzyżowiec"),
    ("paladin", "paladyn"),
    ("outcast", "wyrzutek"),
    ("pariah", "parias"),
    ("exile", "wygnaniec"),
    ("nomad", "nomada"),
    ("outlaw", "banita"),
    ("bandit", "bandyta"),
    ("brigand", "rozbójnik"),
    ("marauder", "maruder"),
    ("savage", "dzikus"),
    ("barbarian", "barbarzyńca"),

    # Creatures & Monsters
    ("spectre", "widmo"),
    ("wraith", "zjawa"),
    ("phantom", "fantom"),
    ("apparition", "zjawa"),
    ("revenant", "powracający"),
    ("golem", "golem"),
    ("wyrm", "żmij"),
    ("dragon", "smok"),
    ("phoenix", "feniks"),
    ("chimera", "chimera"),
    ("basilisk", "bazyliszek"),
    ("gorgon", "gorgona"),
    ("serpent", "wąż"),
    ("viper", "żmija"),
    ("hydra", "hydra"),
    ("lich", "lisz"),

    # Materials & Gems
    ("obsidian", "obsydian"),
    ("onyx", "onyks"),
    ("ebony", "heban"),
    ("emerald", "szmaragd"),
    ("sapphire", "szafir"),
    ("ruby", "rubin"),
    ("topaz", "topaz"),
    ("amber", "bursztyn"),
    ("jade", "jadeit"),
    ("diamond", "diament"),
    ("ivory", "słoniowa kość"),
    ("alabaster", "alabaster"),
    ("marble", "marmur"),
    ("porcelain", "porcelana"),
    ("brass", "mosiądz"),
    ("bronze", "brąz"),
    ("alloy", "stop"),
    ("runic", "runiczny"),
    ("rune", "runa"),

    # Descriptive / Atmospheric
    ("ethereal", "nieziemski"),
    ("celestial", "niebiański"),
    ("infernal", "piekielny"),
    ("abyssal", "otchłanny"),
    ("arcane", "tajemny"),
    ("eldritch", "przerażający"),
    ("occult", "okultystyczny"),
    ("profane", "bezbożny"),
    ("sanguine", "krwisty"),
    ("crimson", "karmazynowy"),
    ("azure", "lazurowy"),
    ("cobalt", "kobaltowy"),
    ("verdant", "zielony"),
    ("viridian", "wirydiański"),
    ("gilded", "pozłacany"),
    ("wretched", "nędzny"),
    ("forsaken", "opuszczony"),
    ("accursed", "przeklęty"),
    ("condemned", "potępiony"),
    ("torment", "męka"),
    ("agony", "agonia"),
    ("despair", "rozpacz"),
    ("anguish", "udręka"),
    ("suffering", "cierpienie"),
    ("misery", "niedola"),
    ("carnage", "rzeź"),
    ("slaughter", "masakra"),
    ("atrocity", "okrucieństwo"),
    ("vengeance", "zemsta"),
    ("retribution", "odwet"),
    ("vendetta", "wendeta"),
    ("treachery", "zdrada"),
    ("treason", "zdrada"),
    ("betrayal", "zdrada"),
    ("deceit", "oszustwo"),
    ("malice", "złośliwość"),
    ("malevolence", "wrogość"),
    ("benevolence", "dobroczynność"),
    ("clemency", "łaska"),
    ("serenity", "spokój"),
    ("tranquility", "cisza"),
    ("harmony", "harmonia"),
    ("providence", "opatrzność"),
    ("prudence", "roztropność"),
    ("piety", "pobożność"),
    ("vanity", "próżność"),
    ("hubris", "pycha"),
    ("avarice", "chciwość"),
    ("greed", "chciwość"),
    ("gluttony", "obżarstwo"),
    ("sloth", "lenistwo"),
    ("envy", "zazdrość"),
    ("wrath", "gniew"),
    ("pride", "duma"),
    ("lust", "pożądanie"),
]

# Sort alphabetically by English
poe_deck.sort(key=lambda x: x[0])

print(f"Total cards: {len(poe_deck)}")

# Write to file instead of stdout to avoid encoding issues
import os
out_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../js/decks/poe.js"))
with open(out_path, 'w', encoding='utf-8') as f:
    f.write("const WORDS_POE = [\n")
    for en, pl in poe_deck:
        f.write(f'  {{ en: "{en}", pl: "{pl}" }},\n')
    f.write("];\n")
print(f"Written to {out_path}")
