#!/usr/bin/env python3
"""Generate Cyberpunk 2077 EN-PL flashcard deck with extensive lore terminology."""

deck = [
    # ===== CHARACTERS =====
    ("mercenary", "najemnik"),
    ("narrator", "narrator"),
    ("rockstar", "gwiazda rocka"),
    ("terrorist", "terrorysta"),
    ("netrunner", "sieciobiegacz"),
    ("ripperdoc", "ripperdoc"),
    ("fixer", "załatwiacz"),
    ("edgerunner", "edgerunner"),
    ("solo", "solo"),
    ("techie", "technik"),
    ("medtech", "medtech"),
    ("rockerboy", "rockerboy"),
    ("nomad", "nomada"),
    ("corpo", "korp"),
    ("lawman", "stróż prawa"),
    ("media", "dziennikarz"),
    ("executive", "dyrektor"),
    ("bodyguard", "ochroniarz"),
    ("assassin", "skrytobójca"),
    ("cyberpsycho", "cyberpsychopata"),
    ("proxy", "pełnomocnik"),
    ("joytoy", "zabawka erotyczna"),
    ("doll", "lalka"),
    ("braindance", "braindance"),
    ("technomancer", "technomanta"),
    ("straightedge", "prostolinijny"),
    ("outlaw", "banita"),
    ("bounty hunter", "łowca nagród"),
    ("informant", "informator"),
    ("barghest", "barghest"),

    # ===== FACTIONS & GANGS =====
    ("maelstrom", "maelstrom"),
    ("valentinos", "valentinos"),
    ("tyger claws", "tygrysie pazury"),
    ("voodoo boys", "voodoo boys"),
    ("animals", "zwierzęta"),
    ("scavengers", "padlinożercy"),
    ("scavs", "scavs"),
    ("mox", "mox"),
    ("wraiths", "widma"),
    ("aldecaldos", "aldecaldos"),
    ("sixth street", "szósta ulica"),
    ("tino", "tino"),
    ("claws", "pazury"),
    ("raffen shiv", "raffen shiv"),
    ("baker clan", "klan bakera"),
    ("the mox", "the mox"),

    # ===== CORPORATIONS =====
    ("corporation", "korporacja"),
    ("megacorporation", "megakorporacja"),
    ("arasaka", "arasaka"),
    ("militech", "militech"),
    ("kang tao", "kang tao"),
    ("biotechnica", "biotechnica"),
    ("trauma team", "trauma team"),
    ("maxtac", "maxtac"),
    ("netwatch", "netwatch"),
    ("zyntec", "zyntec"),
    ("petrochem", "petrochem"),
    ("orbital air", "orbital air"),
    ("night corp", "night corp"),
    ("kendachi", "kendachi"),
    ("securicine", "securicine"),
    ("danger gal", "danger gal"),
    ("world news service", "światowe serwisy informacyjne"),
    ("network news", "network news"),

    # ===== LOCATIONS =====
    ("night city", "night city"),
    ("dogtown", "dogtown"),
    ("badlands", "nieużytki"),
    ("heywood", "heywood"),
    ("watson", "watson"),
    ("westbrook", "westbrook"),
    ("pacifica", "pacifica"),
    ("santo domingo", "santo domingo"),
    ("city center", "centrum miasta"),
    ("corpo plaza", "corpo plaza"),
    ("japantown", "japantown"),
    ("kabuki", "kabuki"),
    ("north oak", "north oak"),
    ("charter hill", "charter hill"),
    ("glen", "glen"),
    ("wellsprings", "wellsprings"),
    ("arroyo", "arroyo"),
    ("rancho coronado", "rancho coronado"),
    ("the afterlife", "afterlife"),
    ("konpeki plaza", "konpeki plaza"),
    ("arasaka tower", "wieża arasaka"),
    ("mikoshi", "mikoshi"),
    ("laguna bend", "laguna bend"),
    ("megabuilding", "megabudowla"),
    ("the stacks", "stosy"),
    ("oil fields", "pola naftowe"),
    ("biotechnica flats", "biotechnica flats"),
    ("sunset motel", "motel sunset"),
    ("no-tell motel", "motel no-tell"),
    ("totentanz", "totentanz"),
    ("lizzies", "lizzies"),
    ("dark matter", "ciemna materia"),
    ("empathetic", "empatyczny"),
    ("rioter", "uczestnik zamieszek"),

    # ===== CYBERWARE & IMPLANTS =====
    ("cyberware", "cyberware"),
    ("implant", "implant"),
    ("augmentation", "augmentacja"),
    ("chrome", "chrom"),
    ("wetware", "wetware"),
    ("sandevistan", "sandevistan"),
    ("kerenzikov", "kerenzikov"),
    ("berserk", "berserk"),
    ("mantis blades", "ostrza modliszki"),
    ("gorilla arms", "goryle ramiona"),
    ("monowire", "monodrut"),
    ("projectile launch", "wyrzutnia pocisków"),
    ("optics", "optyka"),
    ("kiroshi", "kiroshi"),
    ("smart link", "smart link"),
    ("ballistic coprocessor", "koprocesor balistyczny"),
    ("synthlungs", "syntetyczne płuca"),
    ("subdermal armor", "pancerz podskórny"),
    ("pain editor", "edytor bólu"),
    ("biomonitor", "biomonitor"),
    ("kerenzikov boost", "kerenzikov boost"),
    ("second heart", "drugie serce"),
    ("blood pump", "pompa krwi"),
    ("tyrosine injector", "wstrzykiwacz tyrozyny"),
    ("camouflage", "kamuflaż"),
    ("synaptic accelerator", "akcelerator synaptyczny"),
    ("microgenerator", "mikrogenerator"),
    ("shock absorber", "absorbator wstrząsów"),
    ("mechatronic core", "rdzeń mechatroniczny"),
    ("adrenaline converter", "konwerter adrenaliny"),
    ("phantom", "fantom"),
    ("limbic system", "układ limbiczny"),
    ("neural", "neuronowy"),
    ("biochip", "biochip"),
    ("relic", "relikt"),
    ("cyberdeck", "cyberdeck"),
    ("interface plugs", "wtyczki interfejsu"),
    ("cranial", "czaszkowy"),
    ("prosthetic", "protetyczny"),

    # ===== WEAPONS =====
    ("malorian arms", "malorian arms"),
    ("satori", "satori"),
    ("fenrir", "fenrir"),
    ("skippy", "skippy"),
    ("lizzie", "lizzie"),
    ("overwatch", "overwatch"),
    ("comrades hammer", "młot towarzysza"),
    ("apparition", "zjawa"),
    ("problem solver", "rozwiązywacz problemów"),
    ("knife", "nóż"),
    ("katana", "katana"),
    ("thermal katana", "termiczna katana"),
    ("crowbar", "łom"),
    ("wrench", "klucz francuski"),
    ("hammer", "młot"),
    ("gorilla arms", "goryle ramiona"),
    ("mantis blades", "ostrza modliszki"),
    ("monowire", "monodrut"),
    ("wire", "drut"),
    ("shotgun", "strzelba"),
    ("pistol", "pistolet"),
    ("assault rifle", "karabin szturmowy"),
    ("sniper rifle", "karabin snajperski"),
    ("precision rifle", "karabin precyzyjny"),
    ("submachine gun", "pistolet maszynowy"),
    ("light machine gun", "lekki karabin maszynowy"),
    ("revolver", "rewolwer"),
    ("melee", "walka wręcz"),
    ("ranged", "dystansowy"),
    ("ricochet", "rykoszet"),
    ("projectile", "pocisk"),
    ("ballistic", "balistyczny"),
    ("smart", "inteligentny"),
    ("tech", "techniczny"),
    ("power", "kinetyczny"),
    ("thermal", "termiczny"),
    ("electric", "elektryczny"),
    ("toxic", "toksyczny"),
    ("chemical", "chemiczny"),
    ("incendiary", "zapalający"),

    # ===== SLANG & TERMINOLOGY =====
    ("choom", "kumpel"),
    ("gonk", "idiota"),
    ("nova", "zajebisty"),
    ("preem", "zacny"),
    ("scop", "szajs"),
    ("flatline", "zgon"),
    ("delta", "spadać"),
    ("input", "partnerka"),
    ("output", "partner"),
    ("iron", "broń"),
    ("eddies", "eurodolary"),
    ("eurodollar", "eurodolar"),
    ("techhair", "techwłosy"),
    ("bodysculpt", "rzeźbienie ciała"),
    ("faceplate", "płyta twarzowa"),
    ("biochip", "biochip"),
    ("engram", "engram"),
    ("soulkiller", "soulkiller"),
    ("blackwall", "czarna ściana"),
    ("construct", "konstrukt"),
    ("digitize", "digitalizować"),
    ("consciousness", "świadomość"),
    ("personality", "osobowość"),
    ("overwrite", "nadpisać"),
    ("posergang", "gang pozerów"),
    ("boostergang", "gang wspomagaczy"),
    ("cyberpsychosis", "cyberpsychoza"),
    ("humanity cost", "koszt człowieczeństwa"),
    ("chromer", "chromer"),
    ("metalhead", "metalhead"),
    ("razorgirl", "laserowa dziewczyna"),
    ("razorboi", "laserowy chłopak"),
    ("deadeye", "martwe oko"),
    ("jack in", "podłączyć się"),
    ("jack out", "odłączyć się"),
    ("trace", "namierzenie"),
    ("ice", "ICE"),
    ("black ice", "czarny lód"),
    ("daemon", "demon"),
    ("firewall", "zapora"),
    ("breach", "włamanie"),
    ("encryption", "szyfrowanie"),
    ("decryption", "deszyfrowanie"),
    ("cyberdeck", "cyberdeck"),
    ("deckhead", "mózgowiec"),
    ("datamine", "kopalnia danych"),
    ("datapool", "zasób danych"),
    ("matrix", "matryca"),
    ("cyberspace", "cyberprzestrzeń"),
    ("blackwall", "czarna ściana"),
    ("rogue ai", "zbuntowane ai"),
    ("alt", "alt"),

    # ===== LORE CONCEPTS =====
    ("dystopia", "dystopia"),
    ("utopia", "utopia"),
    ("transhumanist", "transhumanista"),
    ("posthuman", "postczłowiek"),
    ("cyberization", "cyberryzacja"),
    ("bioengineering", "bioinżynieria"),
    ("nanotech", "nanotechnologia"),
    ("nanorobotics", "nanorobotyka"),
    ("clone", "klon"),
    ("synthetic", "syntetyczny"),
    ("prosthetic", "protetyczny"),
    ("neural interface", "interfejs neuronowy"),
    ("brain-computer", "mózg-komputer"),
    ("neural link", "łącze neuronowe"),
    ("virtual reality", "rzeczywistość wirtualna"),
    ("augmented reality", "rzeczywistość rozszerzona"),
    ("hologram", "hologram"),
    ("simulation", "symulacja"),
    ("emotion", "emocja"),
    ("empathy", "empatia"),
    ("dehumanize", "odczłowieczyć"),
    ("depersonalize", "depersonalizować"),
    ("consciousness", "świadomość"),
    ("sentience", "samoświadomość"),
    ("sapience", "rozumność"),
    ("autonomous", "autonomiczny"),
    ("android", "android"),
    ("bioroid", "bioroid"),
    ("full-conversion", "pełna konwersja"),
    ("commodification", "utowarowienie"),
    ("exploitation", "eksploatacja"),
    ("surveillance", "nadzór"),
    ("panopticon", "panoptikon"),
    ("megastructure", "megastruktura"),
    ("arcology", "arkologia"),
    ("urban", "miejski"),
    ("sprawl", "rozlewisko miejskie"),
    ("undercity", "podziemne miasto"),
    ("combat zone", "strefa walk"),
    ("wasteland", "pustkowie"),
    ("hinterland", "głębia lądu"),
    ("beaverville", "bobrowo"),
    ("free state", "wolny stan"),
    ("nightwatch", "nightwatch"),
    ("cyberlimb", "cyberkończyna"),
    ("surgical", "chirurgiczny"),
    ("anarchy", "anarchia"),
    ("totalitarian", "totalitarny"),
    ("corporate", "korporacyjny"),
    ("megalopolis", "megalopolis"),
    ("interlock", "interlock"),
    ("fuzion", "fuzion"),
    ("retcon", "retcon"),

    # ===== GAMEPLAY MECHANICS =====
    ("attribute", "atrybut"),
    ("perk", "perk"),
    ("skill", "umiejętność"),
    ("street cred", "kredyt uliczny"),
    ("experience", "doświadczenie"),
    ("leveling", "poziomowanie"),
    ("lifepath", "ścieżka życia"),
    ("shard", "shard"),
    ("gig", "fucha"),
    ("quest", "zadanie"),
    ("side job", "zadanie poboczne"),
    ("main job", "zadanie główne"),
    ("cyberpsycho", "cyberpsychopata"),
    ("sighting", "zgłoszenie"),
    ("fast travel", "szybka podróż"),
    ("delamain", "delamain"),
    ("autofixer", "autozałatwiacz"),
    ("ncart", "ncart"),
    ("ncpd", "ncpd"),
    ("ncpd scanner", "skaner ncpd"),
    ("quickhack", "quickhack"),
    ("breach protocol", "protokół włamania"),
    ("ram", "ram"),
    ("buffer", "bufor"),
    ("cyberdeck", "cyberdeck"),
    ("operating system", "system operacyjny"),
    ("sandevistan", "sandevistan"),
    ("berserk", "berserk"),
    ("circulatory", "krwionośny"),
    ("immune system", "układ odpornościowy"),
    ("nervous system", "układ nerwowy"),
    ("integumentary", "powłokowy"),
    ("skeleton", "szkielet"),
    ("hand", "dłoń"),
    ("arm", "ramię"),
    ("leg", "noga"),
    ("face", "twarz"),
    ("frontal cortex", "kora czołowa"),
    ("ocular", "oczny"),
    ("inventory", "ekwipunek"),
    ("backpack", "plecak"),
    ("wardrobe", "garderoba"),

    # ===== LORE-SPECIFIC CHARACTERS =====
    ("johnny silverhand", "johnny silverhand"),
    ("jackie welles", "jackie welles"),
    ("panam palmer", "panam palmer"),
    ("judy alvarez", "judy alvarez"),
    ("evelyn parker", "evelyn parker"),
    ("rogue amendiares", "rogue amendiares"),
    ("dex deshawn", "dex deshawn"),
    ("goro takemura", "goro takemura"),
    ("viktor vector", "viktor vector"),
    ("saburo arasaka", "saburo arasaka"),
    ("yorinobu arasaka", "yorinobu arasaka"),
    ("hanako arasaka", "hanako arasaka"),
    ("adam smasher", "adam smasher"),
    ("alt cunningham", "alt cunningham"),
    ("kerry eurodyne", "kerry eurodyne"),
    ("mitch anderson", "mitch anderson"),
    ("river ward", "river ward"),
    ("claire russell", "claire russell"),
    ("placide", "placide"),
    ("brigitte", "brigitte"),
    ("rhino", "rhino"),
    ("ozob bozo", "ozob bozo"),
    ("kurt hansen", "kurt hansen"),
    ("songbird", "songbird"),
    ("solomon reed", "solomon reed"),
    ("rosalind myers", "rosalind myers"),
    ("lizzy wizzy", "lizzy wizzy"),
    ("fingers", "fingers"),
    ("woodman", "woodman"),
    ("royce", "royce"),
    ("dum dum", "dum dum"),
    ("brick", "brick"),
    ("sasquatch", "sasquatch"),
    ("mr hands", "mr hands"),
    ("wakako okada", "wakako okada"),
    ("regina jones", "regina jones"),
    ("el capitan", "el capitan"),
    ("dino", "dino"),
    ("badlands", "nieużytki"),

    # ===== ITEMS & CONSUMABLES =====
    ("maxdoc", "maxdoc"),
    ("bounce back", "bounce back"),
    ("health booster", "wzmacniacz zdrowia"),
    ("stamina booster", "wzmacniacz kondycji"),
    ("ram jolt", "ram jolt"),
    ("synthblood", "syntetyczna krew"),
    ("neuron", "neuron"),
    ("battery", "bateria"),
    ("component", "komponent"),
    ("quickhack", "quickhack"),
    ("databank", "bank danych"),
    ("access token", "token dostępu"),
    ("keycard", "karta dostępu"),
    ("junk", "złom"),
    ("loot", "łup"),
    ("scavenge", "szperanie"),
    ("looting", "grabienie"),
    ("vendor", "sprzedawca"),
    ("drug dealer", "handlarz narkotykami"),
    ("ripperdoc", "ripperdoc"),
    ("pharmaceutical", "farmaceutyczny"),

    # ===== ENVIRONMENT & AESTHETICS =====
    ("neon", "neon"),
    ("neonlights", "neonowe światła"),
    ("dystopian", "dystopijny"),
    ("megabuilding", "megabudowla"),
    ("overpass", "wiadukt"),
    ("underground", "podziemie"),
    ("skyline", "linia horyzontu"),
    ("megacity", "megamiasto"),
    ("industrial", "przemysłowy"),
    ("abandoned", "opuszczony"),
    ("derelict", "opuszczony"),
    ("dilapidated", "zniszczony"),
    ("kitsch", "kicz"),
    ("militarism", "militaryzm"),
    ("entropism", "entropizm"),
    ("neokitsch", "neokitsch"),
    ("high-tech", "zaawansowana technologia"),
    ("low-life", "nędzne życie"),
    ("verticality", "pionowość"),
    ("multilevel", "wielopoziomowy"),
    ("freeway", "autostrada"),
    ("aerial", "powietrzny"),
    ("av", "av"),
    ("aerodyne", "aerodyna"),
    ("trauma team", "trauma team"),
    ("hovertank", "czołg powietrzny"),
    ("hovercraft", "poduszkowiec"),

    # ===== ADDITIONAL LORE TERMS =====
    ("kriegmesser", "kriegmesser"),
    ("bakaneko", "bakaneko"),
    ("cybersnake", "cybersnake"),
    ("scratchers", "drapacze"),
    ("vampyres", "vampyres"),
    ("slice-dice", "krój kraj"),
    ("rush revolution", "rush revolution"),
    ("synthcoke", "synthcoke"),
    ("glitter", "glitter"),
    ("smash", "smash"),
    ("debt chip", "debt chip"),
    ("city database", "baza danych miasta"),
    ("dataterm", "dataterm"),
    ("net architecture", "architektura sieci"),
    ("agent", "agent"),
    ("bioagent", "bioagent"),
    ("bioplague", "bioplaga"),
    ("tectonic", "tektoniczny"),
    ("seismic", "sejsmiczny"),
    ("quarantine", "kwarantanna"),
    ("outbreak", "wybuch epidemii"),
    ("contamination", "skażenie"),
    ("fallout", "opad radioaktywny"),
    ("radiation", "promieniowanie"),
    ("irradiated", "napromieniowany"),
    ("mutagen", "mutagen"),
    ("mutation", "mutacja"),
    ("plasmid", "plazmid"),
    ("exoskeleton", "egzoszkielet"),
    ("power armor", "pancerz wspomagany"),
    ("linear frame", "rama liniowa"),
    ("reconstruction", "rekonstrukcja"),
    ("override", "nadpisanie"),
    ("reboot optics", "restart optyki"),
    ("synapse burnout", "wypalenie synaps"),
    ("contagion", "zaraza"),
    ("overheat", "przegrzanie"),
    ("short circuit", "zwarcie"),
    ("system reset", "reset systemu"),
    ("suicide", "samobójstwo"),
    ("detonate grenade", "detonacja granatu"),
    ("cripple movement", "spowolnienie ruchu"),
    ("weapon glitch", "usterka broni"),
    ("cyberware malfunction", "awaria cyberware"),
    ("memory wipe", "wyczyszczenie pamięci"),
    ("sonic shock", "szok dźwiękowy"),
    ("ping", "ping"),
    ("whistle", "gwizdek"),
    ("bait", "przynęta"),
    ("request backup", "wezwanie wsparcia"),

    # ===== PHANTOM LIBERTY =====
    ("phantom liberty", "phantom liberty"),
    ("dogtown", "dogtown"),
    ("barghest", "barghest"),
    ("kurt hansen", "kurt hansen"),
    ("songbird", "songbird"),
    ("solomon reed", "solomon reed"),
    ("rosalind myers", "rosalind myers"),
    ("militech canto", "militech canto"),
    ("blackwall protocol", "protokół czarnej ściany"),
    ("erebus", "erebus"),
    ("faceplate", "płyta twarzowa"),
    ("nusa", "nusa"),
    ("new united states", "nowe stany zjednoczone"),
    ("combine", "kombajn"),
    ("president", "prezydent"),
    ("space force", "siły kosmiczne"),
    ("orbital station", "stacja orbitalna"),
    ("night city airport", "lotnisko night city"),
    ("vesta", "vesta"),
]

# Deduplicate
seen = set()
unique = []
for en, pl in deck:
    key = en.lower().replace(" ", "").replace("-", "")
    if key not in seen:
        seen.add(key)
        unique.append((en, pl))

unique.sort(key=lambda x: x[0])

import os
out_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "../js/decks"))
os.makedirs(out_dir, exist_ok=True)
out_path = os.path.join(out_dir, "cyberpunk.js")

with open(out_path, 'w', encoding='utf-8') as f:
    f.write("var WORDS_CYBERPUNK = [\n")
    for en, pl in unique:
        f.write(f'  {{ en: "{en}", pl: "{pl}" }},\n')
    f.write("];\n")

print(f"Total unique cards: {len(unique)}")
print(f"Written to {out_path}")
