#!/usr/bin/env python3
"""FINAL massive translation pass for Baldur's Gate deck."""
import re

with open("C:/Users/R6X/opencode/klepanka/js/decks/baldursgate.js", "r", encoding="utf-8") as f:
    content = f.read()

# HUGE EN->PL dictionary (~3500 entries in compact format)
T = {}
# We'll build the dict from a compact data string to save space
DATA = """
abated:osłabł;abdomen:brzuch;abject:podły;abominations:ohydy;abounded:obfitował;
absentmindedly:z roztargnieniem;accented:zaakcentowany;accoutrements:rynsztunek;
aching:obolały;acidic:kwasowy;acids:kwasy;acknowledgment:uznanie;
acknowledgments:podziękowania;acolytes:akolici;acquain:zapoznać;acrid:gryzący;
across:przez;addle:zmącić;adoration:uwielbienie;advances:postępy;afar:z daleka;
affairs:sprawy;affecting:wpływający;afoul:w konflikcie;afraid:przestraszony;
afternoon:popołudnie;afternoons:popołudnia;agents:agenci;ages:wieki;aging:starzenie;
ago:temu;agreed:zgodził się;aimed:wycelowany;airplanes:samoloty;ake:ból;
alarming:alarmujący;alaundo:alaundo;albaier:albaier;alchemical:alchemiczny;
ale:piwo;alerted:zaalarmowany;alerting:alarmujący;algae:glony;alienness:obcość;
aligned:wyrównany;alive:żywy;allay:uśmierzyć;alley:zaułek;alleys:zaułki;
allies:sojusznicy;allotted:przydzielony;allowed:dozwolony;allowing:pozwalając;
aloft:w górze;alone:sam;along:wzdłuż;alongside:obok;aloud:na głos;alter:zmienić;
alternate:alternatywny;amazement:zdumienie;ambushed:zaskoczony;among:wśród;
amongst:pośród;amount:ilość;amounts:ilości;amulets:amulety;amusing:zabawny;
ancestors:przodkowie;anchored:zakotwiczony;angered:rozgniewany;angrily:gniewnie;
angular:kątowy;ankle:kostka;announcement:ogłoszenie;annoyance:irytacja;
anonymous:anonimowy;anvil:kowadło;anxiously:niespokojnie;anybody:ktokolwiek;
anyone:ktoś;anyt:cokolwiek;apart:osobno;appear:pojawić się;appeared:pojawił się;
approached:zbliżył się;approaches:zbliża się;approval:aprobata;apt:trafny;
aquatic:wodny;arches:łuki;archway:arkada;argued:kłócił się;arguments:argumenty;
armies:armie;armored:opancerzony;armory:zbrojownia;armpit:pacha;aromatic:aromatyczny;
arose:powstał;arranged:zaaranżowany;arrangements:ustalenia;arrest:aresztować;
arrested:aresztowany;arrow:strzała;arrows:strzały;arteries:tętnice;artifacts:artefakty;
aside:na bok;asking:pytając;asleep:śpiący;aspect:aspekt;ass:tyłek;assault:szturm;
assured:zapewniony;atmosphere:atmosfera;atop:na szczycie;attached:przywiązany;
attendants:służący;attract:przyciągać;audience:publiczność;authority:autorytet;
available:dostępny;avenge:pomścić;avoid:unikać;avoided:uniknęty;avoiding:unikając;
awakening:przebudzenie;aware:świadomy;awareness:świadomość;awhile:chwilę;
babe:dziecko;backed:wsparty;backing:cofając;backs:plecy;bade:kazał;
bafflement:zakłopotanie;bait:przynęta;baiting:prowokując;baker:piekarz;
ball:piłka;ballady:ballady;bandages:bandaże;bandits:bandyci;baneful:zgubny;
bang:huk;barbarian:barbarzyńca;barbaric:barbarzyński;bare:goły;barely:ledwo;
bargaining:targowanie;barn:stodoła;baron:baron;barrel:beczka;barrels:beczki;
barricaded:zabarykadowany;barrier:bariera;base:baza;basement:piwnica;bashed:walnął;
bat:nietoperz;bats:nietoperze;battered:poobijany;bauble:błyskotka;bearer:nosiciel;
bears:niedźwiedzie;beaten:pobity;beating:bicie;became:stał się;becomes:staje się;
beds:łóżka;began:zaczął;begging:żebrząc;beguiling:uwodzicielski;behave:zachowywać się;
beheaded:ścięty;believe:wierzyć;bellowed:ryknął;belly:brzuch;bend:zakręt;
bereavement:żałoba;beside:obok;betrayal:zdrada;bewilderment:oszołomienie;
birds:ptaki;bite:ugryzienie;biting:kąsający;bitter:gorzki;black:czarny;
blame:winić;blank:pusty;blanket:koc;blasted:wysadzony;blasting:wysadzający;
blaze:płomień;bleached:wybielony;bleak:ponury;bled:krwawił;bleeding:krwawiący;
bless:błogosławić;blessed:błogosławiony;blinding:oślepiający;blinking:mrugający;
block:blok;blocked:zablokowany;blonde:blond;blossom:kwitnąć;blow:cios;blown:wysadzony;
board:deska;boards:deski;boast:chluba;boasting:przechwalanie;bodies:ciała;
bold:odważny;bolstered:wzmocniony;bolt:rygiel;bonds:więzy;bone:kość;bonus:premia;
bore:nudziarz;borne:niesiony;borrowed:pożyczony;both:oboje;bother:przeszkadzać;
bottles:butelki;bound:związany;boundaries:granice;boundary:granica;bounty:nagroda;
bowed:ukłonił się;bowels:wnętrzności;box:pudełko;boyhood:chłopięctwo;
brainless:bezmyślny;brass:mosiądz;bravery:odwaga;brawl:bójka;brazier:koksownik;
break:przerwa;breaking:łamanie;breaks:przerwy;breast:pierś;breastplate:napierśnik;
breathe:oddychać;breathed:oddychał;breathing:oddychanie;breed:rasa;breeze:bryza;
brethren:bracia;bride:panna młoda;brief:krótki;bright:jasny;brilliance:blask;
brim:krawędź;bring:przynieść;briskly:żwawo;bristling:jeżący się;broad:szeroki;
broadened:poszerzony;broke:złamał;brooch:broszka;brook:strumyk;brought:przyniósł;
brow:brew;brown:brązowy;bruises:siniaki;brush:szczotka;brutal:brutalny;
bubbling:bulgoczący;bucket:wiadro;buckles:sprzączki;buddies:kumple;buffalo:bawół;
bugbears:straszydła;bugs:robaki;build:budować;bulk:masa;bull:byk;bullied:tyranizowany;
bump:guz;bunches:kiście;bundle:pakunek;bunk:koja;burden:ciężar;burglars:włamywacze;
burn:palić;burnt:spalony;burrow:nora;bursting:pękający;bushes:krzaki;bust:popiersie;
busy:zajęty;butcher:rzeźnik;buzzing:brzęczący;
cabinet:szafka;cackled:zarechotał;cackling:rechoczący;cages:klatki;
calling:wołanie;calmly:spokojnie;came:przyszedł;canine:psi;cannons:armaty;
canopy:baldachim;capable:zdolny;capacity:pojemność;cape:peleryna;careful:ostrożny;
carefully:ostrożnie;caring:troskliwy;carnage:rzeź;carpet:dywan;carriages:powozy;
carried:niesiony;carrot:marchewka;carve:rzeźbić;carved:rzeźbiony;casket:trumna;
cast:rzucić;casting:rzucanie;catacombs:katakumby;catalog:katalog;catapults:katapulty;
catching:łapiąc;cathedral:katedra;cattle:bydło;cauldron:kocioł;caught:złapany;
cautious:ostrożny;cautiously:ostrożnie;cease:zaprzestać;celebration:świętowanie;
cellar:piwnica;central:centralny;centuries:stulecia;century:wiek;ceremony:ceremonia;
certainly:z pewnością;certainty:pewność;chain:łańcuch;chains:łańcuchy;chairs:krzesła;
chalice:kielich;challenge:wyzwanie;chamber:komnata;chambers:komnaty;champion:mistrz;
channel:kanał;chants:pieśni;chapel:kaplica;charge:szarża;charged:naładowany;
charity:dobroczynność;charm:urok;charming:uroczy;chase:pościg;chasm:przepaść;
chatter:paplanina;cheat:oszukiwać;check:sprawdzić;cheeks:policzki;cheer:wiwat;
cheese:ser;chewed:przeżuty;chief:wódz;childish:dziecinny;chimney:komin;chin:broda;
chipped:odłupany;chittered:świergotał;choked:zakrztusił się;choking:duszący się;
choosing:wybierając;chop:siekać;chopped:posiekany;chosen:wybrany;chuckle:chichot;
chuckled:zachichotał;chuckling:chichoczący;church:kościół;cipher:szyfr;
circumstances:okoliczności;citizen:obywatel;civilization:cywilizacja;claim:roszczenie;
claimed:twierdził;clambering:wspinając się;clan:klan;clans:klany;clapped:klasnął;
clashing:zderzający się;clasp:zapięcie;clatter:stukot;clawed:pazurowaty;
clawing:drapiący;cleaned:wyczyszczony;cleanse:oczyścić;clear:jasny;clearly:wyraźnie;
clenched:zaciśnięty;cleric:kleryk;clerk:urzędnik;clever:sprytny;cliff:klif;
cliffs:klify;climb:wspinaczka;climbed:wspiął się;climbing:wspinaczka;cling:lgnąć;
cloak:płaszcz;cloaks:płaszcze;closest:najbliższy;cloth:materiał;clothes:ubrania;
clouds:chmury;clue:wskazówka;clues:wskazówki;clumsily:niezdarnie;clung:przylgnął;
cluster:skupisko;clutch:chwyt;coach:powóz;coal:węgiel;code:kod;coils:zwoje;
coldly:chłodno;colleague:kolega;collected:zebrany;collection:kolekcja;colony:kolonia;
combatants:walczący;combined:połączony;comely:urodziwy;comfort:komfort;
comfortable:wygodny;comical:komiczny;commanded:rozkazał;commander:dowódca;
commands:rozkazy;comment:komentarz;committing:popełniając;communicate:komunikować;
companion:towarzysz;companionship:towarzystwo;compare:porównać;compared:porównany;
compass:kompas;compelling:przekonujący;competition:konkurencja;complain:narzekać;
complete:kompletny;completing:kończąc;complex:złożony;comprehend:pojąć;conceal:ukryć;
concentrate:skupić;concept:koncepcja;concern:troska;conclusion:wniosek;confess:wyznać;
confidence:pewność;confined:ograniczony;confirm:potwierdzić;conflict:konflikt;
confused:zdezorientowany;confusing:mylący;congratulations:gratulacje;connected:połączony;
conqueror:zdobywca;conscious:świadomy;consequences:konsekwencje;considerable:znaczny;
consist:składać się;constantly:stale;constitution:konstytucja;contact:kontakt;
contain:zawierać;container:pojemnik;contempt:pogarda;content:zawartość;context:kontekst;
continue:kontynuować;continuing:kontynuując;control:kontrola;controlled:kontrolowany;
convenient:wygodny;convinced:przekonany;cook:gotować;cooking:gotowanie;cool:chłodny;
cooperate:współpracować;cope:radzić sobie;copper:miedź;copy:kopia;cordial:serdeczny;
core:rdzeń;cork:korek;corpses:zwłoki;correct:poprawny;corridor:korytarz;
corridors:korytarze;cost:koszt;costly:kosztowny;costume:kostium;cottage:chata;
count:liczyć;countless:niezliczony;courageous:odważny;courteous:uprzejmy;
courtesy:uprzejmość;cousin:kuzyn;cover:przykryć;coward:tchórz;cowardly:tchórzliwy;
crack:pęknięcie;cracked:pęknięty;cracking:trzaskający;crackling:trzeszczący;
crafty:przebiegły;crash:zderzenie;crashed:rozbity;crater:krater;crawl:pełzać;
crawling:pełzający;crazy:szalony;creaking:skrzypiący;creek:strumyk;crept:pełzał;
crescent:półksiężyc;crest:grzebień;crevice:szczelina;crevices:szczeliny;
crime:przestępstwo;crisp:chrupiący;croak:rechot;cronies:kumple;crooked:krzywy;
crossbow:kusza;crossbows:kusze;crow:wrona;crucial:kluczowy;cruel:okrutny;
cruelly:okrutnie;crumb:okruch;crumbs:okruchy;crumbled:rozpadł się;crunched:chrupał;
crushing:miażdżący;crying:płacz;crypt:krypta;crystal:kryształ;cult:kult;
cunning:przebiegłość;cup:kubek;cups:kubki;cure:lekarstwo;curiosity:ciekawość;
curious:ciekawy;curled:zakręcony;current:obecny;cursed:przeklęty;curtain:zasłona;
curve:krzywa;custom:zwyczaj;customers:klienci;cutting:cięcie;cycle:cykl;
cylinder:walec;
dagger:sztylet;daily:codziennie;damaged:uszkodzony;damnation:potępienie;
damned:przeklęty;damp:wilgotny;dance:taniec;dancing:taniec;dangle:zwisać;
dangling:wiszący;dare:odważyć się;darker:ciemniejszy;darkly:mrocznie;
darted:rzucił się;dash:myślnik;dashing:pędzący;dated:datowany;dawn:świt;
daylight:światło dnia;daze:oszołomienie;dazed:oszołomiony;deadly:śmiertelny;
deaf:głuchy;dealing:handlując;dear:drogi;debate:debata;debris:gruz;debt:dług;
debts:długi;decade:dekada;decades:dekady;deceased:zmarły;decide:decydować;
decision:decyzja;declared:oświadczył;decline:spadek;declined:odmówił;
decorations:dekoracje;deed:czyn;deeds:czyny;deepened:pogłębiony;deeply:głęboko;
defeat:porażka;defeated:pokonany;definitely:zdecydowanie;defined:zdefiniowany;
definition:definicja;delicate:delikatny;delight:zachwyt;delighted:zachwycony;
deliver:dostarczyć;delusion:złudzenie;demanded:zażądał;demonstrations:demonstracje;
den:nora;depart:odejść;departed:odszedł;departure:odjazd;depended:zależał;
depths:głębiny;descent:zejście;describe:opisać;descriptions:opisy;desert:pustynia;
deserved:zasłużony;desk:biurko;desperate:zdesperowany;desperation:desperacja;
despicable:nikczemny;destroy:zniszczyć;destroying:niszcząc;destruction:zniszczenie;
detailed:szczegółowy;detect:wykryć;determination:determinacja;determine:określić;
devastation:dewastacja;develop:rozwijać;device:urządzenie;devil:diabeł;devoted:oddany;
dialogue:dialog;diamond:diament;diamonds:diamenty;dictates:dyktuje;died:umarł;
difficult:trudny;difficulty:trudność;digging:kopanie;dim:przyćmiony;dining:jadalnia;
dire:straszny;direction:kierunek;dirt:brud;dirty:brudny;disagree:nie zgadzać się;
disappear:zniknąć;disappeared:zniknął;disappointment:rozczarowanie;disaster:katastrofa;
disc:dysk;disciples:uczniowie;discontent:niezadowolenie;discord:niezgoda;
discovered:odkryty;discuss:dyskutować;discussion:dyskusja;disdain:pogarda;
disease:choroba;disgrace:hańba;disgust:obrzydzenie;dish:danie;dismissed:odprawiony;
disorder:nieporządek;disorganized:zdezorganizowany;dispel:rozproszyć;displeasure:niezadowolenie;
disposition:usposobienie;dispute:spór;dissolved:rozpuszczony;distinction:wyróżnienie;
distracted:rozproszony;disturb:niepokoić;disturbance:zakłócenie;dive:nurkować;
divide:dzielić;divine:boski;document:dokument;dog:pies;dome:kopuła;dominate:dominować;
donkey:osioł;donned:nałożył;doomed:skazany;doorframe:futryna;doorway:przejście;
dose:dawka;dot:kropka;double:podwójny;doubled:podwojony;doubts:wątpliwości;
downhill:w dół;downstairs:na dole;downtrodden:uciśniony;downward:w dół;dozen:tuzin;
draft:szkic;drag:ciągnąć;dragged:wleczony;drain:odpływ;draperies:draperie;
drat:cholera;draw:rysować;drawer:szuflada;drawl:przeciągać;drawn:narysowany;
dread:strach;dreadful:straszny;dress:sukienka;drift:dryf;drifted:dryfował;
drifting:dryfujący;drill:wiertło;drinks:napoje;dripping:kapiący;driven:napędzany;
driver:kierowca;drool:ślinić się;droplets:kropelki;drops:krople;drove:prowadził;
drown:utopić;drowned:utopiony;drowsy:senny;drunk:pijany;drunken:pijacki;dry:suchy;
drying:suszący;duck:kaczka;due:z powodu;dues:opłaty;duke:książę;dull:nudny;
dumb:głupi;dungeon:loch;dungeons:lochy;dusk:zmierzch;dusty:zakurzony;
dwelling:mieszkanie;dwindle:zmniejszać;dyed:farbowany;
eager:chętny;eagerly:chętnie;eagle:orzeł;earliest:najwcześniejszy;earned:zarobiony;
earnest:poważny;ears:uszy;ease:łatwość;easily:łatwo;eating:jedzenie;ebb:odpływ;
echo:echo;edge:krawędź;edged:krawędziasty;edict:edykt;edition:edycja;effect:efekt;
effective:skuteczny;efficient:wydajny;egg:jajko;eggs:jajka;elation:uniesienie;
elderly:starszy;elders:starsi;eldritch:upiorny;elect:wybierać;elegant:elegancki;
elements:elementy;elevation:wzniesienie;elfin:elficki;elves:elfy;embrace:objęcie;
embraced:objął;emerge:wyłonić się;emerged:wyłonił się;emphasis:nacisk;empire:imperium;
emptied:opróżniony;emptiness:pustka;empty:pusty;enable:umożliwić;enchant:zaczarować;
enchantment:zaklęcie;enchantments:zaklęcia;encounter:spotkanie;encourage:zachęcać;
encrusted:inkrustowany;endeavors:wysiłki;endless:nieskończony;endure:znosić;
endured:zniesiony;enforce:egzekwować;engage:angażować;engine:silnik;engraving:grawerunek;
enhance:wzmocnić;enjoy:cieszyć się;enormous:ogromny;enraged:rozwścieczony;
enslaved:zniewolony;ensure:zapewnić;entered:wszedł;enterprise:przedsięwzięcie;
entities:byty;entire:cały;entirely:całkowicie;entrails:wnętrzności;entreat:błagać;
entry:wejście;enveloped:otoczony;envoy:wysłannik;equipment:sprzęt;errand:sprawunek;
erratic:nieregularny;essence:esencja;establish:ustanowić;estate:posiadłość;
etching:rycina;eternal:wieczny;eternity:wieczność;ether:eter;evaluate:oceniać;
evenly:równomiernie;eventually:ostatecznie;events:wydarzenia;evidence:dowód;
exactly:dokładnie;exaggerated:przesadzony;examine:badać;excavation:wykopalisko;
excellence:doskonałość;excess:nadmiar;excessive:nadmierny;excited:podekscytowany;
excitement:ekscytacja;excluded:wykluczony;excuse:przeprosiny;execute:wykonać;
execution:egzekucja;exhausted:wyczerpany;exile:wygnanie;exit:wyjście;expand:rozszerzyć;
expedition:ekspedycja;expenses:wydatki;experienced:doświadczony;expert:ekspert;
explain:wyjaśnić;explained:wyjaśnił;exploration:eksploracja;exploring:eksplorowanie;
explosive:wybuchowy;extended:przedłużony;extension:przedłużenie;extent:zakres;
extra:dodatkowy;extract:wyciąg;extraordinary:nadzwyczajny;extreme:skrajny;
extremely:niezwykle;eyes:oczy;
fable:bajka;facade:fasada;faces:twarze;facility:obiekt;facing:zwrócony;factor:czynnik;
fade:blaknąć;faded:wyblakły;fading:blednący;fail:zawieść;faint:słaby;faintly:słabo;
fair:sprawiedliwy;fairly:dość;faithful:wierny;fake:fałszywy;falcon:sokół;
fallen:upadły;false:fałszywy;falter:zachwiać się;fame:sława;familiar:znajomy;
famous:sławny;fanatic:fanatyk;fancied:upragniony;fang:kieł;fangs:kły;faraway:daleki;
farewell:pożegnanie;farther:dalej;fascinating:fascynujący;fashion:moda;faster:szybciej;
fault:wina;favor:przysługa;favored:faworyzowany;favorite:ulubiony;feared:obawiał się;
fearsome:straszliwy;feast:uczta;feather:pióro;feathers:pióra;fee:opłata;
feeble:watły;feed:karmić;feigned:udawany;fell:upadł;fellow:kolega;fellows:koledzy;
felt:czuł;fence:płot;fencing:szermierka;fervor:żarliwość;fetch:przynieść;
fetid:cuchnący;fever:gorączka;fief:lenno;fiends:demony;fierce:zaciekły;
fifth:piąty;fig:figa;fight:walka;fighting:walcząc;figure:postać;figured:domyślił się;
fill:wypełnić;filthy:brudny;financial:finansowy;finding:znajdując;fine:w porządku;
fingertips:opuszki;finished:skończony;fired:wystrzelił;firm:twardy;firmly:mocno;
fish:ryba;fist:pięść;fit:pasować;fitting:odpowiedni;fix:naprawić;fixed:naprawiony;
fixture:element stały;flag:flaga;flagged:oznaczony;flags:flagi;flailing:machający;
flaming:płonący;flash:błysk;flattened:spłaszczony;flavor:smak;flaw:wada;fleas:pchły;
fled:uciekł;flesh:ciało;fleshless:bezcielesny;fleshy:mięsisty;flew:poleciał;
flicker:migotanie;flickered:zamigotał;flies:muchy;flipping:przerzucający;
floated:unosił się;floating:unoszący;flock:stado;flood:powódź;flowing:płynący;
flurry:zamęt;flush:rumieniec;flute:flet;flutter:trzepot;fly:lecieć;foam:piana;
foe:wróg;fold:składać;folk:lud;follow:śledzić;follower:naśladowca;followers:zwolennicy;
folly:głupota;foolish:głupi;foot:stopa;footing:podstawa;footprints:ślady stóp;
foray:wyprawa;forbidding:zakazujący;forced:zmuszony;ford:bród;foreboding:złowróżbny;
forehead:czoło;foreign:obcy;foretold:przepowiedział;forgotten:zapomniany;fork:widelec;
formally:formalnie;formation:formacja;formed:uformowany;former:były;formula:formuła;
forth:naprzód;fortress:twierdza;fortunately:na szczęście;fortune:fortuna;
forward:naprzód;foul:ohydny;foundation:fundament;fountain:fontanna;fragment:fragment;
frame:rama;framework:szkielet;frantically:gorączkowo;fraud:oszustwo;fray:strzęp;
freckled:piegowaty;freedom:wolność;freeing:uwalniając;freely:swobodnie;freeze:zamrażać;
freight:ładunek;frenzied:oszalały;frequently:często;fresh:świeży;freshly:świeżo;
fretting:zamartwiając się;friendship:przyjaźń;fright:strach;frightened:przestraszony;
fringe:skraj;fro:tam i z powrotem;front:przód;frontier:pogranicze;frost:mróz;
froze:zamarł;frozen:zamrożony;fruit:owoc;frying:smażenie;fuel:paliwo;
fulfilling:spełniający;fumble:gmerać;funeral:pogrzeb;fungus:grzyb;fur:futro;
furiously:wściekle;furnishings:umeblowanie;furry:futrzasty;further:dalej;
fuse:bezpiecznik;futile:daremny;
gained:zyskany;gaining:zyskując;gale:wichura;gall:czelność;gallant:dzielny;
gallery:galeria;gallows:szubienica;gamble:hazard;gang:gang;gangplank:trap;
gape:gapić się;gaping:ziejący;garb:strój;gargle:płukać gardło;garrison:garnizon;
gas:gaz;gasp:westchnienie;gasped:wysapał;gasping:dyszący;gates:bramy;
gathering:zgromadzenie;gave:dał;gaze:wpatrywanie;gazed:wpatrywał się;gazing:wpatrujący;
gear:sprzęt;gelatinous:galaretowaty;gem:klejnot;gems:klejnoty;generations:pokolenia;
generous:hojny;genius:geniusz;gentle:łagodny;gentleman:dżentelmen;genuine:prawdziwy;
gesture:gest;ghastly:upiorny;ghosts:duchy;gibbet:szubienica;gift:prezent;
gigantic:gigantyczny;gilded:pozłacany;gills:skrzela;gingerly:ostrożnie;girder:dźwigar;
girdle:pas;glacier:lodowiec;glad:zadowolony;gladly:chętnie;glamour:urok;
glance:spojrzenie;glare:blask;glared:spojrzał gniewnie;glassy:szklisty;glaze:glazura;
gleam:połysk;gleaming:lśniący;glide:szybować;glimmer:przebłysk;glimpsed:dostrzegł;
glint:błysk;glistening:lśniący;glitter:blask;gloom:mrok;glory:chwała;gloss:połysk;
gloved:w rękawiczce;gloves:rękawice;glow:poświata;glowing:świecący;glum:ponury;
gnarled:sękaty;gnash:zgrzytać;gnolls:gnolle;gnome:gnom;gnomes:gnomy;goal:cel;
goat:koza;goblet:kielich;gods:bogowie;goddess:bogini;gone:zniknął;goodly:spory;
goods:towary;goose:gęś;gore:posoka;gorge:wąwóz;gorgeous:wspaniały;gotten:dostał;
gourd:tykwa;government:rząd;gowns:suknie;grace:łaska;gracious:łaskawy;
gradually:stopniowo;grain:ziarno;grand:wielki;grant:przyznać;granted:przyznany;
granular:ziarnisty;grapple:zmagać się;grasp:uchwyt;grasped:chwycił;grate:krata;
grateful:wdzięczny;gratitude:wdzięczność;grave:grób;gravel:żwir;graveyard:cmentarz;
gray:szary;grease:smar;greatest:największy;greatly:znacznie;greed:chciwość;
green:zielony;greet:powitać;greeted:powitany;greeting:powitanie;grew:rósł;
grief:smutek;grieved:opłakiwał;grievously:ciężko;grim:ponury;grimaced:skrzywił się;
grimly:ponuro;grind:mielić;grinding:zgrzytający;grip:chwyt;gripped:chwycił;
grisly:makabryczny;groan:jęk;groaned:jęknął;groaning:jęczący;grooming:pielęgnacja;
grooves:rowki;grotto:grota;ground:ziemia;grow:rosnąć;growing:rosnący;grown:dorosły;
grudge:uraza;gruffly:szorstko;grumble:marudzenie;grunt:chrząknięcie;guardian:opiekun;
guessed:zgadł;guidance:wskazówki;guild:gildia;guise:postać;gullet:gardziel;
gully:wąwóz;gurgle:bulgot;gush:wytrysk;guts:wnętrzności;
habit:nawyk;hacked:pocięty;hacking:rąbanie;haggard:wynędzniały;haggle:targować;
hail:grad;halberd:halabarda;halfway:w połowie;hallucination:halucynacja;
hammered:wbity młotkiem;handed:wręczony;handful:garść;handle:uchwyt;handled:obsłużony;
hang:wisieć;hanging:wiszący;happen:zdarzyć się;happened:zdarzyło się;
happening:dziejący się;happier:szczęśliwszy;happily:szczęśliwie;harbor:port;
harden:utwardzić;hardly:ledwo;harm:krzywda;harmless:nieszkodliwy;harsh:surowy;
harvest:żniwa;hast:pośpiech;hasten:przyspieszyć;hastily:pośpiesznie;hasty:pośpieszny;
hatched:wykluty;hate:nienawiść;hatred:nienawiść;haul:ciągnąć;haunches:kucając;
haunt:nawiedzać;haunted:nawiedzony;haven:przystań;hawk:jastrząb;hay:siano;
haze:mgiełka;heading:nagłówek;headquarters:kwatera główna;heads:głowy;heal:leczyć;
healer:uzdrowiciel;health:zdrowie;heap:sterta;hearts:serca;heated:podgrzany;
heave:dźwigać;heavily:ciężko;hedge:żywopłot;heed:zważać;heel:pięta;heft:ciężar;
height:wysokość;heir:dziedzic;helm:hełm;helmet:hełm;hence:stąd;herbs:zioła;
herd:stado;hermit:pustelnik;heroic:bohaterski;hesitation:wahanie;hidden:ukryty;
hide:ukryć;highness:wysokość;highway:autostrada;hilt:rękojeść;hinges:zawiasy;
hint:wskazówka;hire:wynająć;hiss:syk;hit:uderzenie;hither:tutaj;hive:ul;
hoard:skarbiec;hoarse:ochrypły;hobble:kuleć;holding:trzymając;hollow:wydrążony;
honest:szczery;honestly:szczerze;honey:miód;honored:zaszczycony;hook:hak;
hooked:zakrzywiony;hoot:pohukiwanie;hopeless:beznadziejny;horde:horda;horn:róg;
horrible:okropny;horror:przerażenie;hostile:wrogi;hotly:gorąco;hound:ogar;
household:gospodarstwo;hover:unosić się;howl:wycie;howled:zawył;howling:wyjący;
huddled:skulony;hue:odcień;huff:fuknąć;huge:ogromny;hull:kadłub;hum:bzyczenie;
humanity:ludzkość;humble:pokorny;humidity:wilgotność;humorous:hmmorystyczny;
hunch:przeczucie;hunk:kawał;hurl:ciskać;hurried:pośpieszny;hurriedly:pośpiesznie;
hurry:pośpiech;hurt:zraniony;hush:cisza;husk:łuska;hut:chata;hygiene:higiena;
idiot:idiota;idle:bezczynny;ignorance:ignorancja;ignorant:ignorant;illness:choroba;
illustrate:ilustrować;imaginable:wyobrażalny;imagination:wyobraźnia;imagine:wyobrażać;
immeasurable:niezmierzony;immediate:natychmiastowy;immense:ogromny;immortal:nieśmiertelny;
immortality:nieśmiertelność;impact:wpływ;impale:nadziać;impaled:nadziany;
impatience:niecierpliwość;impending:nadciągający;imperfect:niedoskonały;implement:wdrożyć;
implied:sugerowany;importance:ważność;important:ważny;imposing:imponujący;
impressive:imponujący;imprisoned:uwięziony;impulse:impuls;incentive:zachęta;
inch:cal;inches:cale;incident:incydent;inclination:skłonność;included:włączony;
income:dochód;inconvenience:niedogodność;increase:zwiększyć;incredible:niesamowity;
incredulous:niedowierzający;indeed:rzeczywiście;indicate:wskazywać;indifference:obojętność;
individual:jednostka;infant:niemowlę;infection:infekcja;inflict:zadawać;influence:wpływ;
inhabitants:mieszkańcy;inheritance:dziedzictwo;injury:obrażenie;injustice:niesprawiedliwość;
ink:atrament;innards:wnętrzności;inner:wewnętrzny;innocent:niewinny;inquiry:zapytanie;
insane:szalony;insanity:szaleństwo;inscription:inskrypcja;insect:owad;inspection:inspekcja;
inspired:zainspirowany;instance:przypadek;instead:zamiast;instinct:instynkt;
instrument:instrument;insult:obraza;insulting:obraźliwy;intact:nienaruszony;
intellect:intelekt;intelligent:inteligentny;intended:zamierzony;intense:intensywny;
intent:zamiar;intently:uważnie;interfere:przeszkadzać;interference:ingerencja;
interior:wnętrze;interrupt:przerwać;interrupted:przerwany;intersection:skrzyżowanie;
intolerable:nie do zniesienia;intricate:zawiły;intrude:wtargnąć;invade:najeżdżać;
invaders:najeźdźcy;invasion:inwazja;invent:wynaleźć;investigate:badać;
invincible:niezwyciężony;invisible:niewidzialny;invitation:zaproszenie;invite:zaprosić;
invoke:przywołać;inward:do wewnątrz;iron:żelazo;ironic:ironiczny;irregular:nieregularny;
irritably:poirytowany;isolated:odizolowany;issue:kwestia;itch:swędzenie;item:przedmiot;
jagged:postrzępiony;jail:więzienie;jam:dżem;jar:słoik;jaws:szczęki;jealous:zazdrosny;
jeer:szydzić;jest:żart;jewel:klejnot;job:praca;join:dołączyć;joint:staw;
joints:stawy;joke:żart;journey:podróż;joy:radość;joyful:radosny;judge:sędzia;
jug:dzban;juicy:soczysty;jump:skok;jumped:skoczył;jumps:skacze;junction:skrzyżowanie;
junior:młodszy;jury:ława przysięgłych;justice:sprawiedliwość;justified:uzasadniony;
keen:bystry;keg:beczułka;kerchief:chustka;kick:kopnięcie;kicked:kopnął;kicking:kopiący;
kid:dzieciak;kidding:żartujący;kidnapper:porywacz;killers:zabójcy;kiln:piec;kin:krewni;
kindly:uprzejmie;kindness:życzliwość;kingdom:królestwo;kiss:pocałunek;kit:zestaw;
kitten:kotek;kneel:klękać;knees:kolana;knelt:ukląkł;knights:rycerze;knob:gałka;
knocked:zapukał;knot:węzeł;knots:węzły;knuckles:knykcie;knucklewraps:owijki na pięści;
lack:brak;lacked:brakowało;ladder:drabina;ladle:chochla;lagoon:laguna;lair:kryjówka;
lamb:jagnię;lambs:jagnięta;lament:lament;lamp:lampa;lamps:lampy;lance:lanca;
landlord:właściciel;landscape:krajobraz;lane:pas;lantern:latarnia;lap:kolana;
lard:smalec;largely:w dużej mierze;latch:zasuwka;latest:najnowszy;lather:piana;
latter:ten drugi;lauded:chwalony;launch:wystrzelić;laurels:laury;lava:lawa;
lawful:praworządny;layer:warstwa;layers:warstwy;layout:układ;lazy:leniwy;
leading:prowadzący;league:liga;leak:wyciek;lean:chudy;leaned:oparł się;
leaning:pochylony;leap:skok;leaped:skoczył;leaping:skaczący;learn:uczyć się;
learned:nauczony;lease:dzierżawa;leather:skóra;lecture:wykład;legends:legendy;
leisurely:spokojnie;lend:pożyczyć;length:długość;lens:soczewka;lesser:mniejszy;
lesson:lekcja;lessons:lekcje;lest:aby nie;lethal:śmiertelny;lethargic:ospały;
letting:pozwalając;lever:dźwignia;levity:lekkość;liar:kłamca;liberation:wyzwolenie;
liberty:wolność;lick:lizać;licked:polizał;lid:pokrywka;lie:kłamstwo;
lifeblood:siła życiowa;lifeless:martwy;lifetime:życie;lift:podnosić;liked:lubiany;
likelihood:prawdopodobieństwo;likeness:podobieństwo;liking:upodobanie;limb:kończyna;
lime:limonka;limestone:wapień;limited:ograniczony;limp:utykać;link:łącze;
linked:połączony;liquor:alkohol;list:lista;lit:oświetlony;litter:śmieci;lived:żył;
lively:żywy;liver:wątroba;living:żyjący;lizard:jaszczurka;load:ładunek;
loaded:załadowany;loan:pożyczka;loathe:nienawidzić;loathsome:wstrętny;located:zlokalizowany;
location:lokalizacja;lock:zamek;locked:zamknięty;locking:blokujący;lodge:chata;
lodgings:kwatera;loft:strych;logically:logicznie;logs:kłody;lonely:samotny;
longer:dłuższy;longing:tęsknota;lookout:czujka;loop:pętla;loose:luźny;
loosened:poluzowany;loot:łup;lord:pan;lore:wiedza;loss:strata;loud:głośny;
loudly:głośno;lounging:wylegując się;lousy:parszywy;lovely:śliczny;lovers:kochankowie;
loving:kochający;lower:niższy;lowest:najniższy;loyal:lojalny;loyalty:lojalność;
lust:pożądanie;luxury:luksus;
mace:buława;madly:szaleńczo;magical:magiczny;magically:magicznie;magnificent:wspaniały;
maid:służąca;maintain:utrzymywać;majestic:majestatyczny;majesty:majestat;maker:twórca;
malice:złośliwość;manage:zarządzać;manor:dwór;mansion:rezydencja;mantle:płaszcz;
manufactured:wyprodukowany;manuscript:manuskrypt;march:marsz;marching:maszerujący;
mare:klacz;marrow:szpik;mass:masa;massive:masywny;masterpiece:arcydzieło;
masters:mistrzowie;matching:pasujący;mate:kumpel;material:materiał;matter:sprawa;
matters:sprawy;mature:dojrzały;mayhap:być może;maze:labirynt;meager:skromny;
meal:posiłek;meaning:znaczenie;measure:miara;mechanism:mechanizm;meddle:wtrącać się;
meddler:wścibski;mediator:mediator;medicine:medycyna;medieval:średniowieczny;
mediocre:przeciętny;meek:łagodny;melody:melodia;melt:topić;melted:stopiony;
memoir:pamiętnik;memorable:niezapomniany;mend:naprawiać;mention:wspomnieć;
mercenaries:najemnicy;merciful:miłosierny;mercy:łaska;merely:jedynie;merriment:wesołość;
merry:wesoły;mesh:siatka;message:wiadomość;messenger:posłaniec;metal:metal;meter:metr;
mightily:potężnie;mighty:potężny;mild:łagodny;miles:mile;military:wojskowy;milk:mleko;
million:milion;miner:górnik;mingled:zmieszany;minimum:minimum;minister:minister;
minor:drobny;miraculous:cudowny;mirth:wesołość;miscellaneous:różny;mischief:psota;
miserable:nędzny;misery:niedola;misfortune:nieszczęście;missing:brakujący;mist:mgła;
mistress:kochanka;mix:mieszać;mixture:mieszanka;mock:kpić;model:model;moderate:umiarkowany;
mold:pleśń;moldy:spleśniały;monarchy:monarchia;monk:mnich;monks:mnisi;mood:nastrój;
morbid:chorobliwy;mortal:śmiertelnik;mortals:śmiertelnicy;mortar:moździerz;
mostly:głównie;motion:ruch;motioned:wskazał gestem;mound:kopiec;mourn:opłakiwać;
mouse:mysz;muck:błoto;mud:błoto;muffled:stłumiony;multiplication:mnożenie;
mumble:mamrotanie;municipal:miejski;murder:morderstwo;murdered:zamordowany;
murderer:morderca;murmured:wymamrotał;muscle:mięsień;mushroom:grzyb;musical:muzyczny;
muster:zebrać;mute:niemy;mutter:mruczenie;muttered:wymruczał;mutual:wzajemny;
mysterious:tajemniczy;mystic:mistyczny;
nail:gwóźdź;nails:gwoździe;naked:nagi;narrow:wąski;narrowed:zwężony;nasty:paskudny;
national:narodowy;natural:naturalny;naught:nic;navel:pępek;nearby:w pobliżu;
nearest:najbliższy;nearly:prawie;nears:zbliża się;neat:schludny;necessity:konieczność;
needle:igła;neglect:zaniedbanie;negotiate:negocjować;neighbors:sąsiedzi;nerve:nerw;
nerves:nerwy;nervously:nerwowo;nervousness:nerwowość;nest:gniazdo;nestled:przytulony;
net:sieć;nettle:pokrzywa;network:sieć;neutral:neutralny;niche:nisza;niece:bratanica;
noble:szlachetny;nobles:szlachta;nobody:nikt;nod:kiwnięcie;noddle:makaron;
nonetheless:niemniej;nor:ani;normal:normalny;normally:normalnie;northward:na północ;
notches:nacięcia;notebook:notatnik;notice:zauważyć;noticed:zauważył;noticing:zauważając;
notion:pojęcie;notorious:notoryczny;novice:nowicjusz;nudge:szturchnięcie;numb:zdrętwiały;
nursery:żłobek;nut:orzech;nutshell:w skrócie;
oak:dąb;oaken:dębowy;obedience:posłuszeństwo;obey:słuchać;obligated:zobowiązany;
oblivion:zapomnienie;observant:spostrzegawczy;observation:obserwacja;observe:obserwować;
obsession:obsesja;obstacle:przeszkoda;obtain:zdobyć;obvious:oczywisty;obviously:oczywiście;
occasion:okazja;occupants:mieszkańcy;occurred:wydarzyło się;odd:dziwny;odors:zapachy;
offal:podroby;offend:obrazić;offended:obrażony;official:oficjalny;offs:wyłącza;
oft:często;ofttimes:czasami;oiled:naoliwiony;omen:omen;once:raz;onion:cebula;
onions:cebule;opened:otwarty;opening:otwarcie;operation:operacja;oppress:uciskać;
option:opcja;oracle:wyrocznia;oral:ustny;orbs:kule;orbit:orbita;ordeal:próba;
ordinary:zwykły;ore:ruda;organ:organ;organization:organizacja;orient:wschód;
origin:pochodzenie;original:oryginalny;ornament:ozdoba;orphan:sierota;
otherwise:w przeciwnym razie;outer:zewnętrzny;outlandish:dziwaczny;outlook:perspektywa;
outright:wprost;outskirts:peryferie;outward:na zewnątrz;oven:piekarnik;overall:ogólny;
overcame:przezwyciężył;overcome:przezwyciężyć;overgrown:zarośnięty;overlook:przeoczyć;
overly:nadmiernie;overpowering:przytłaczający;owe:być winnym;owed:winien;owing:z powodu;
owning:posiadający;
pacing:chodzący tam i z powrotem;packed:zapakowany;padded:wyściełany;page:strona;
paid:zapłacony;pail:wiadro;pains:bole;painting:malowidło;pair:para;pale:blady;
pang:ukłucie;pants:spodnie;parchment:pergamin;pardon:przebaczenie;parlor:salon;
partial:częściowy;particular:szczególny;parting:rozstanie;passion:pasja;passionate:namiętny;
passive:bierny;patch:łata;patches:łaty;patrol:patrol;pause:pauza;paused:zatrzymał się;
paved:brukowany;payment:zapłata;peak:szczyt;peasant:chłop;peasantry:chłopstwo;
peculiar:osobliwy;pedestal:cokół;peer:rówieśnik;peered:zajrzał;peering:zaglądający;
pegs:kołki;pelt:futro;penalty:kara;pennant:proporzec;perceived:postrzegany;
perception:postrzeganie;perch:grzęda;perched:usadowiony;perfect:idealny;
perfectly:idealnie;performance:występ;perfume:perfumy;perhaps:być może;peril:niebezpieczeństwo;
perils:niebezpieczeństwa;period:okres;perish:zginąć;permanent:stały;permission:pozwolenie;
permit:zezwolić;permitted:dozwolony;perpetual:wieczny;person:osoba;personal:osobisty;
persuade:przekonać;pet:zwierzak;phantom:fantom;phew:uff;philosophy:filozofia;phrase:fraza;
pickpocket:kieszonkowiec;piece:kawałek;pieces:kawałki;pier:molo;pile:stos;
piled:ułożony w stos;pilgrim:pielgrzym;pillage:plądrowanie;pillar:filar;pillars:filary;
pin:szpilka;pinch:szczypta;pine:sosna;pipes:rury;pit:dół;pitch:smoła;pittance:grosze;
pity:litość;plague:plaga;plain:zwykły;plank:deska;planks:deski;plant:roślina;
plaster:tynk;plate:talerz;plates:talerze;platform:platforma;platoon:pluton;
plaything:zabawka;plea:błaganie;plead:błagać;pleasant:przyjemny;pleased:zadowolony;
pleasing:przyjemny;pledge:przysięga;plenty:mnóstwo;plight:trudna sytuacja;plod:człapać;
plot:spisek;plucked:wyrwany;plug:wtyczka;plumage:upierzenie;plume:pióropusz;
plummet:runąć w dół;plunder:grabież;plunge:nurkować;plunged:zanurzył się;
pockets:kieszenie;poetry:poezja;poke:szturchać;poked:szturchnął;polar:polarny;
pole:słup;polished:wypolerowany;polite:uprzejmy;pompous:pompatyczny;pony:kucyk;
poor:biedny;popular:popularny;port:port;portion:porcja;portrayed:przedstawiony;
pose:poza;position:pozycja;positive:pozytywny;possess:posiadać;possessed:opętany;
possession:posiadanie;possessions:dobytek;possibly:możliwie;post:słupek;posture:postawa;
pot:garnek;potion:mikstura;pounce:rzucić się;pound:funt;pour:nalewać;poured:wylany;
pout:dąsy;powder:proszek;powerful:potężny;practically:praktycznie;praise:pochwała;
prank:psikus;prattle:paplać;pray:modlić się;precarious:niepewny;precaution:środek ostrożności;
precious:cenny;precipice:przepaść;precise:precyzyjny;precisely:dokładnie;predator:drapieżnik;
predict:przewidzieć;prefer:preferować;preoccupied:zaabsorbowany;preparations:przygotowania;
prepared:przygotowany;presence:obecność;present:teraźniejszość;preserve:zachować;
press:naciskać;pressed:przyciśnięty;prestige:prestiż;presume:zakładać;pretend:udawać;
previously:poprzednio;prey:ofiara;prick:ukłucie;prickly:kłujący;pride:duma;
priestess:kapłanka;primitive:prymitywny;principal:główny;private:prywatny;
privately:prywatnie;privy:wtajemniczony;probable:prawdopodobny;probably:prawdopodobnie;
probe:sonda;problem:problem;procedure:procedura;process:proces;procession:procesja;
proclamation:proklamacja;product:produkt;profitable:zyskowny;profound:głęboki;
program:program;progress:postęp;project:projekt;promise:obietnica;promised:obiecał;
prompt:szybki;promptly:szybko;prone:podatny;proper:właściwy;properly:właściwie;
property:własność;prophecy:proroctwo;prophetic:proroczy;proportion:proporcja;
proposal:propozycja;propose:proponować;prospect:perspektywa;protect:chronić;
protection:ochrona;proudly:dumnie;prove:udowodnić;proved:udowodnił;proverb:przysłowie;
provide:dostarczyć;provided:pod warunkiem;province:prowincja;prowess:sprawność;
prowl:grasować;pry:podważać;public:publiczny;puddles:kałuże;puff:dmuchnięcie;
pull:ciągnąć;pulley:kołowrót;pulse:puls;punish:karać;punishment:kara;puppet:marionetka;
purchase:zakup;pure:czysty;purely:czysto;purple:fioletowy;pursue:ścigać;pursuit:pościg;
pushed:pchnięty;pylon:pylon;
quaint:uroczy;qualms:skrupuły;quarter:ćwierć;quarters:kwatera;queen:królowa;
quench:ugasić;query:zapytanie;quests:zadania;quickly:szybko;quietly:cicho;
quill:pióro;quirk:dziwactwo;quiver:drżenie;quota:limit;
rabbit:królik;rabble:motłoch;radial:promieniowy;radiant:promienny;raft:tratwa;
rag:szmata;rags:łachmany;raid:najazd;raiders:najeźdźcy;railing:poręcz;rain:deszcz;
rake:grabie;rally:zgromadzenie;ramble:wałęsać się;ramp:rampa;ramparts:mury obronne;
random:losowy;rank:ranga;ranging:wahający się;ransom:okup;rap:stuknięcie;rapid:szybki;
rapidly:szybko;rapport:porozumienie;rare:rzadki;rarely:rzadko;rat:szczur;rate:tempo;
rather:raczej;ration:racja żywnościowa;rations:racje;rats:szczury;rattle:grzechot;
rattled:zagrzechotał;ravage:pustoszyć;rave:zachwycać się;raving:oszołomiony;
raw:surowy;reach:sięgać;reaches:sięga;react:reagować;readily:chętnie;ready:gotowy;
realization:uświadomienie;realize:zdać sobie sprawę;realized:zdał sobie sprawę;
realm:królestwo;reap:zbierać plony;rear:tył;reasoning:rozumowanie;reassure:uspokoić;
rebuild:odbudować;receipt:paragon;recently:ostatnio;reception:recepcja;recess:wnęka;
recipe:przepis;recite:recytować;reckless:lekkomyślny;reckon:sądzić;reckoning:rozrachunek;
recollect:przypomnieć sobie;recommend:polecić;record:zapis;recover:odzyskać;rectify:naprawić;
red:czerwony;redolent:pachnący;reduce:zmniejszyć;reek:smród;reeked:cuchnął;
reevaluated:przewartościowany;refer:odnosić się;reflection:odbicie;refresh:odświeżyć;
refuse:odmówić;regain:odzyskać;regard:wzgląd;regarding:dotyczący;regardless:niezależnie;
regime:reżim;register:rejestrować;reign:panowanie;reinforce:wzmocnić;
reinforcements:posiłki;reject:odrzucić;relate:odnosić się;relatives:krewni;
release:uwolnić;reliable:niezawodny;relief:ulga;relieve:ulżyć;rely:polegać;
remain:pozostać;remaining:pozostały;remains:pozostałości;remarkable:niezwykły;
remedy:lekarstwo;remind:przypomnieć;remnants:pozostałości;remorse:wyrzuty sumienia;
remote:odległy;remove:usunąć;rend:rozdzierać;renew:odnowić;repair:naprawa;repeat:powtórzyć;
repent:żałować;replace:zastąpić;replaced:zastąpiony;replacement:zamiennik;reply:odpowiedź;
reptile:gad;repulsive:odrażający;reputation:reputacja;required:wymagany;requirement:wymóg;
resemble:przypominać;reserve:rezerwa;reserved:zarezerwowany;residence:rezydencja;
resignation:rezygnacja;resistance:opór;resolution:postanowienie;resort:ośrodek;
resource:zasób;resources:zasoby;responded:odpowiedział;restless:niespokojny;
restore:przywrócić;restrain:powstrzymać;resulted:skutkował;retain:zachować;
retaliate:odwetować;retire:przejść na emeryturę;retort:riposta;retribution:kara;
retrieve:odzyskać;reveal:ujawnić;revenge:zemsta;revere:czcić;reverse:odwrócić;
revert:powrócić;revolting:obrzydliwy;rewards:nagrody;rhyme:rym;ribbon:wstążka;
rice:ryż;rich:bogaty;riches:bogactwa;ride:jechać;riders:jeźdźcy;ridge:grzbiet;
ridiculous:śmieszny;rift:szczelina;rig:osprzęt;rill:strumyk;rim:krawędź;ripe:dojrzały;
rise:wzrost;rival:rywal;roam:wędrować;roar:ryk;roared:ryknął;roaring:ryczący;
rob:okraść;robbery:rabunek;robe:szata;robes:szaty;rocked:kołysany;rocky:skalisty;
rod:pręt;rogues:łotry;role:rola;roll:toczyć;rolled:toczony;rolling:toczący się;
roofs:dachy;rooted:zakorzeniony;rose:róża;rot:gnicie;rotten:zgniły;rotting:gnijący;
rough:szorstki;rout:pogrom;route:trasa;row:rząd;rub:pocierać;rubbed:potarty;
rubbish:śmieci;rubble:gruz;rude:niegrzeczny;ruin:ruina;ruins:ruiny;ruled:rządzony;
rulers:władcy;rumbling:dudniący;runes:runy;runner:biegacz;running:biegnący;
rupture:rozerwanie;rush:pośpiech;rust:rdza;rustle:szelest;rusty:zardzewiały;
ruthless:bezwzględny;rye:żyto;
sack:worek;sacred:świety;sacrifice:ofiara;sad:smutny;sadly:niestety;sadness:smutek;
safe:bezpieczny;safer:bezpieczniejszy;safest:najbezpieczniejszy;safety:bezpieczeństwo;
sage:mędrzec;sail:żagiel;sailor:marynarz;sake:wzgląd;salary:pensja;sale:sprzedaż;
salt:sól;salty:słony;salute:salutować;salvage:odzysk;sample:próbka;sanction:sankcja;
sanctuary:sanktuarium;sand:piasek;sandy:piaszczysty;sarcasm:sarkazm;sarcastic:sarkastyczny;
satisfaction:satysfakcja;satisfied:zadowolony;savage:dziki;save:ocalić;savior:zbawiciel;
saw:piła;scale:skala;scales:łuski;scalp:skóra głowy;scan:skanować;scar:blizna;
scare:straszyć;scared:przestraszony;scarred:pokryty bliznami;scatter:rozrzucać;
scattered:rozrzucony;scene:scena;scent:zapach;schedule:harmonogram;scheme:schemat;
scholar:uczony;school:szkoła;scoop:szufelka;scooped:nabrany;score:wynik;scorn:pogarda;
scout:zwiadowca;scramble:gramolić się;scrap:złom;scrape:skrobać;scratched:podrapany;
scrawled:nabazgrany;scream:krzyk;screamed:krzyknął;screaming:krzyczący;screech:pisk;
screen:ekran;scribe:skryba;scruff:kark;scrutiny:kontrola;sculpted:wyrzeźbiony;
sea:morze;sealed:zapieczętowany;seam:szew;searching:poszukujący;seas:morza;
season:sezon;seconds:sekundy;secrecy:tajemnica;secret:sekret;sector:sektor;
secure:bezpieczny;security:bezpieczeństwo;sediment:osad;seeming:pozorny;seep:przesiąkać;
seized:zajęty;seldom:rzadko;selected:wybrany;selection:wybór;selfish:samolubny;
semi:pół;send:wysłać;senior:starszy;sense:zmysł;senses:zmysły;sensible:rozsądny;
sensitive:wrażliwy;sentry:strażnik;separation:separacja;sequence:sekwencja;serene:spokojny;
series:seria;serious:poważny;seriously:poważnie;serve:służyć;service:usługa;
setting:ustawienie;settle:osiąść;setup:ustawienie;sewage:ścieki;sewer:kanalizacja;
sewers:kanały;shack:chata;shackles:kajdany;shade:cień;shadowy:cienisty;shaft:szyb;
shake:potrząsać;shaken:wstrząśnięty;shaking:trzęsący się;shale:łupek;
shall:będzie;shallow:płytki;shaman:szaman;shambles:ruina;shards:odłamki;
share:dzielić;sharp:ostry;sharply:ostro;shatter:roztrzaskać;shattered:roztrzaskany;
shave:golić;sheath:pochwa;shed:szopa;shelves:półki;shepherd:pasterz;
shift:zmiana;shimmer:migotanie;shimmering:migoczący;shingles:gonty;ship:statek;
shiplap:deska;shipped:wysłany;shipping:wysyłka;ships:statki;shirt:koszula;
shiver:dreszcz;shivered:zadrżał;shivering:drżacy;shoal:ławica;shock:szok;
shocked:zszokowany;shocking:szokujący;shoe:but;shook:potrząsnął;shoot:strzelać;
shop:sklep;short:krótki;shortly:wkrotce;shove:pchnięcie;shoved:pchnął;
shovel:łopata;shower:prysznic;shred:strzęp;shredded:poszarpany;shrewd:bystry;
shriek:wrzask;shrill:przeraźliwy;shrine:świątynia;shrink:kurczyć się;
shroud:całun;shrug:wzruszenie ramion;shrugged:wzruszył ramionami;shudder:dreszcz;
shuddered:wzdrygnął się;shuffle:powłoczyć nogami;shuffled:pocztapał;shuffling:szurający;
shun:unikać;shut:zamknięty;shuts:zamyka;shutting:zamykający;sickle:sierp;
sigh:westchnienie;sighed:westchnął;sightless:niewidomy;sign:znak;signal:sygnał;
silent:cichy;silk:jedwab;silly:głupi;silver:srebro;similar:podobny;simple:prosty;
simper:uśmieszek;simply:po prostu;sin:grzech;sinew:ścięgno;sinewy:żylasty;
single:pojedynczy;sink:zlew;sins:grzechy;sire:pan;sister:siostra;site:miejsce;
situated:położony;sixth:szósty;sizable:spory;skeletal:szkieletowy;skeleton:szkielet;
skeptical:sceptyczny;skeptically:sceptycznie;sketch:szkic;skiff:łódka;skin:skóra;
skirmish:potyczka;skirt:spódnica;skull:czaszka;skulls:czaszki;slab:płyta;
slain:zabity;slam:trzaśnięcie;slammed:trzasnął;slant:pochyłość;slap:policzek;
slapped:uderzył;slashing:tnący;slate:łupek;slaughter:rzeź;slave:niewolnik;
slaves:niewolnicy;slay:zabić;slayer:zabójca;sleek:gładki;sleeves:rękawy;
slender:smukły;slew:zabił;slice:plasterek;slick:śliski;slide:zjeżdżalnia;
slight:lekki;slightly:nieznacznie;slime:szlam;sling:proca;slip:poślizg;
slipped:poślizgnął się;slippery:śliski;slit:rozcięcie;slither:pełzać;slits:szczeliny;
slope:zbocze;sloppy:niechlujny;slot:szczelina;slouch:garbić się;slow:powolny;
slowly:powoli;slug:ślimak;slumber:drzemka;slump:załamanie;slur:bełkot;sly:przebiegły;
slyly:chytro;smack:klaps;smart:sprytny;smash:roztrzaskać;smashed:roztrzaskany;
smell:zapach;smile:uśmiech;smith:kowal;smoke:dym;smoking:palący;smooth:gładki;
smuggled:przemycony;snack:przekąska;snag:szkopuł;snap:pstryknięcie;snapped:pstryknął;
snapping:pstrykający;snare:sidła;snarl:warknięcie;snarled:warknął;snatch:chwycić;
sneer:szyderstwo;sneeze:kichnięcie;sniff:powąchać;sniffed:powąchał;snippet:fragment;
snore:chrapanie;snort:parsknięcie;snout:pysk;soaked:przemoczony;soar:szybować;
sob:szloch;sober:trzeźwy;social:społeczny;society:społeczeństwo;sock:skarpeta;
sofa:sofa;softly:cicho;soil:gleba;sole:podeszwa;solemn:uroczysty;solid:stały;
solution:rozwiązanie;someday:pewnego dnia;somehow:jakoś;sometime:kiedyś;
sometimes:czasami;somewhat:nieco;somewhere:gdzieś;song:piosenka;soon:wkrotce;
soot:sadza;soothing:kojący;sorcerer:czarodziej;sorcery:czary;sore:obolały;
sorrow:smutek;sought:szukał;sour:kwaśny;source:źródło;southern:południowy;
sovereign:suwerenny;space:przestrzeń;spaces:przestrzenie;spade:łopata;spare:oszczędzić;
spark:iskra;sparkle:błysk;sparkling:błyszczący;spars:drzewce;spasm:skurcz;
spat:plunął;speech:mowa;speed:prędkość;spend:wydawać;spent:spędzony;spew:wyrzucać;
sphere:sfera;spice:przyprawa;spider:pająk;spies:szpiedzy;spill:rozlać;spilled:rozlany;
spin:kręcić;spine:kręgosłup;spinning:wirujący;spiral:spirala;spirit:duch;
spiritual:duchowy;spit:pluć;spite:złośliwość;splash:plusk;splatter:chlapać;
splendid:wspaniały;splinter:drzazga;split:podzielony;spoil:zepsuć;spoke:szprycha;
spokesman:rzecznik;sponge:gąbka;sponsor:sponsor;spook:straszyć;spoon:łyżka;
sport:sport;spot:miejsce;spotted:dostrzeżony;sprawl:rozwalisko;spray:spray;
spread:rozprzestrzenić;spreading:rozprzestrzeniający;springing:wyskakujący;sprint:sprint;
sprung:wyskoczył;spun:zakręcił;spur:ostroga;spy:szpieg;squad:oddział;squall:szkwał;
square:kwadrat;squat:przysadzisty;squeak:pisk;squeal:kwik;squeeze:ściskać;stab:dźgnięcie;
stabbing:dźgający;stable:stajnia;stables:stajnie;stack:stos;staff:personel;
stage:scena;stagger:chwiać się;staggered:zachwiał się;stained:poplamiony;
stair:schodek;stake:stawka;stale:nieświeży;stalk:łodyga;stall:stragan;
stamen:pręcik;stamp:znaczek;stance:postawa;stand:stać;standard:standard;
standing:stojący;staple:zszywka;startle:przestraszyć;startled:przestraszony;
starvation:głód;stash:schowek;statue:posąg;stature:postura;status:status;
staunch:zagorzały;stay:zostać;stead:miejsce;steady:stały;steak:stek;steal:kraść;
stealth:skradanie;steam:para;steed:rumak;steer:kierować;stem:łodyga;stench:smród;
stenchly:cuchnąco;stern:surowy;stew:gulasz;stick:kij;sticky:lepki;stiff:sztywny;
stiffen:usztywnić;stifle:stłumić;still:ciągle;stilted:sztywny;sting:żądło;
stink:smierdzieć;stint:okres;stipe:łodyga;stir:mieszać;stirred:zamieszał;
stirring:mieszanie;stitch:ścięg;stock:zapas;stockade:ostrokół;stole:ukradł;
stonily:kamiennie;stomp:tupać;stool:stołek;stoop:pochylać;storage:magazyn;
store:sklep;stored:przechowywany;stormy:burzliwy;stout:tęgi;strain:napięcie;
strained:napięty;strait:cieśnina;strand:pasmo;strange:dziwny;strangely:dziwnie;
strangle:dusić;strap:pasek;strata:warstwy;stratagem:podstęp;strategy:strategia;
straw:słoma;stray:zbłąkany;stream:strumień;strengthen:wzmocnić;stretch:rozciągać;
stretched:rozciągnięty;stricken:dotknięty;strict:ścisły;stride:krok;strife:waśń;
strike:uderzenie;striking:uderzający;string:sznurek;stripe:pas;striped:paslasty;
strive:dążyć;stroke:uderzenie;stroll:spacer;strong:silny;stronger:silniejszy;
strongest:najsilniejszy;stronghold:twierdza;strove:dążył;struck:uderzony;
structure:struktura;stubborn:uparty;studded:nabijany;student:uczeń;studio:studio;
study:badać;studying:studiując;stuff:rzeczy;stuffed:wypchany;stumble:potknąć się;
stumbled:potknął się;stump:pień;stun:ogłuszyć;stunned:ogłuszony;stupid:głupi;
stupidity:głupota;sty:chlew;style:styl;subdue:poskromić;sublime:wzniosły;
submerged:zanurzony;submit:poddać się;substance:substancja;subtle:subtelny;
subvert:obalić;succeed:odnieść sukces;succumb:ulec;suck:ssać;sudden:nagły;
suddenly:nagle;sue:pozywać;sufer:cierpieć;sufficient:wystarczający;suffocate:dusić;
sugar:cukier;suggest:sugerować;suicide:samobójstwo;suit:garnitur;suitable:odpowiedni;
sullen:ponury;sultry:parny;summon:przywołać;summoned:przywołany;sunk:zatopiony;
sunlight:światło słoneczne;sunlit:nasłoneczniony;superb:znakomity;superior:lepszy;
supernatural:nadprzyrodzony;superstition:przesąd;supple:giętki;supplies:zapasy;
supply:dostarczać;suppress:stłumić;supreme:najwyższy;surround:otaczać;
surroundings:otoczenie;suspect:podejrzewać;suspected:podejrzany;suspend:zawiesić;
suspicion:podejrzenie;sustain:utrzymać;swallow:połykać;swamp:bagno;swan:łabędź;
swap:wymienić;swarm:rój;sway:kołysać;swear:przysięgać;sweat:pot;sweep:zamiatać;
sweet:słodki;swell:puchnąć;swelled:spuchnięty;swift:szybki;swiftly:szybko;
swim:pływać;swing:huśtawka;swirl:wir;switch:przełącznik;swollen:spuchnięty;
swoop:nurkować;sword:miecz;swords:miecze;sycophant:pochlebca;symbol:symbol;
sympathy:współczucie;symptom:objaw;syrup:syrop;
tables:stoły;tact:dyplomacja;tactics:taktyka;tag:etykieta;tail:ogon;tailor:krawiec;
taint:skażenie;tale:opowieść;talent:talent;tally:zestawienie;tame:oswojony;
tangle:plątanina;tank:zbiornik;tap:stukać;tape:taśma;taper:zwężać się;tapestry:gobelin;
tar:smoła;tardy:spóźniony;target:cel;tarnish:matowić;task:zadanie;tassel:frędzel;
taunt:drwina;tavern:tawerna;tawny:brązowawy;tax:podatek;teaching:nauczanie;
tear:łza;tears:łzy;tease:droczyć się;technique:technika;tedious:nużacy;teeming:roiący;
telegraph:telegraf;temper:temperament;tempest:burza;temple:świątynia;temporary:tymczasowy;
tempt:kusić;temptation:pokusa;tenacity:wytrwałość;tend:opiekować się;tender:delikatny;
tense:napięty;tension:napięcie;tent:namiot;tepid:letni;term:termin;terms:warunki;
terrain:teren;terrible:okropny;terrify:przerażać;terror:terror;testament:testament;
testify:zeznawać;testimony:zeznanie;texture:tekstura;thank:dziękować;thankful:wdzięczny;
thaw:odwilż;theft:kradzież;theme:motyw;theory:teoria;thereby:w ten sposób;
thicket:gąszcz;thief:złodziej;thieves:złodzieje;thigh:udo;thin:cienki;thirst:pragnienie;
thong:rzemień;thorn:cierń;thorough:dokładny;thread:nić;threshold:próg;thrift:oszczędność;
thrill:dreszcz;thrive:rozkwitać;throat:gardło;throb:pulsować;throne:tron;
throng:tłum;throughout:w całym;throw:rzucać;thrust:pchnięcie;thud:łomot;thumb:kciuk;
thump:grzmotnięcie;thunder:grzmot;tick:tykanie;tide:pływ;tidy:schludny;tie:wiązać;
tier:poziom;tight:ciasny;tighten:dokręcać;tile:płytka;till:aż;timber:drzewo;
timepiece:zegar;timid:nieśmiały;tin:cyna;tinge:odcień;tingle:mrowienie;tinker:majsterkować;
tint:odcień;tiny:malutki;tip:koniec;tiptoe:na palcach;tire:opona;tired:zmęczony;
tissue:tkanka;toad:ropucha;toast:tost;tobacco:tytoń;toe:palec u nogi;toil:harować;
toilet:toaleta;token:żeton;tolerate:tolerować;toll:opłata;tomb:grobowiec;
tomorrow:jutro;tone:ton;tongue:język;tooth:ząb;topic:temat;topple:przewrócić;
torch:pochodnia;torment:męka;torn:rozdarty;torrent:potok;torso:tułów;torture:tortura;
toss:rzucić;totter:chwiać się;tough:wytrzymały;tournament:turniej;tow:holować;
towering:górujący;toxic:toksyczny;trace:ślad;track:ślad;tract:obszar;trade:handel;
trader:handlarz;tragedy:tragedia;trail:szlak;trait:cecha;traitor:zdrajca;
trample:deptać;trance:trans;tranquil:spokojny;transfer:przenosić;transform:przekształcać;
transgress:przekraczać;translate:tłumaczyć;transmit:przekazywać;transparent:przezroczysty;
transport:transportować;trash:śmieci;travel:podróżować;traveler:podróżnik;
traverse:przemierzać;tray:taca;treacherous:zdradziecki;tread:kroczyć;treason:zdrada;
treasure:skarb;treat:traktować;treatment:leczenie;treaty:traktat;trek:wędrówka;
tremble:drżeć;tremendous:ogromny;trench:okop;trend:trend;trespass:wtargnąć;
trial:proba;tribute:danina;trick:sztuczka;trickle:sączyć się;trifle:drobnostka;
trigger:spust;trim:przycinać;trip:podróż;triple:potrójny;triumph:triumf;trivial:błahy;
trophy:trofeum;trot:kłus;trouble:kłopot;troubled:zatroskany;troupe:trupa;
trout:pstrąg;truce:rozejm;truck:ciężarówka;trudge:wlóć się;true:prawdziwy;
truly:naprawdę;trumpet:trąbka;trunk:pień;trust:zaufać;trusted:zaufany;
try:próbować;tub:kadź;tuck:podwijać;tug:szarpać;tuition:czesne;tumble:przewrócić się;
tumor:guz;tumult:zgiełk;tune:melodia;tunnel:tunel;turf:torf;turmoil:zamieszanie;
turnip:rzepa;turquoise:turkusowy;tusk:kieł;tutor:korepetytor;twice:dwa razy;
twig:gałązka;twilight:zmierzch;twin:bliźniak;twine:sznurek;twinkle:mrugnięcie;
twirl:kręcić;twist:skręt;twisted:skręcony;typhoon:tajfun;tyranny:tyrania;
tyrant:tyran;
ugly:brzydki;ultimate:ostateczny;umbrella:parasol;unable:niezdolny;unarmed:nieuzbrojony;
unaware:nieświadomy;unbearable:nieznośny;unbroken:nieprzerwany;unburden:odciążyć;
unbutton:rozpiąć;uncanny:niesamowity;unclean:nieczysty;uncommon:niezwykły;
unconscious:nieprzytomny;uncover:odkryć;underdog:słabszy;underestimate:nie doceniać;
undergo:przejść;underneath:pod spodem;understand:rozumieć;undertake:podjąć;
undo:cofnąć;undress:rozebrać;uneasy:niespokojny;unending:niekończący;
unexpected:niespodziewany;unfair:niesprawiedliwy;unfamiliar:nieznany;unfold:rozwijać;
unfortunate:nieszczęśliwy;ungarrisoned:bez załogi;unguarded:niestrzeżony;
unhappy:nieszczęśliwy;unharmed:nietknięty;unholy:bezbożny;unhook:odczepić;
uniform:mundur;unify:jednoczyć;unimaginable:niewyobrażalny;unimportant:nieistotny;
uninhabited:niezamieszkały;unintelligent:nieinteligentny;union:unia;unique:unikalny;
unite:zjednoczyć;unknown:nieznany;unleash:rozpętać;unless:chyba że;unlike:w przeciwieństwie;
unlikely:nieprawdopodobny;unlimited:nieograniczony;unlock:odblokować;unlucky:pechowy;
unmanned:bezzałogowy;unmarked:nieoznaczony;unmistakable:niewątpliwy;unmoved:niewzruszony;
unnatural:nienaturalny;unnecessary:niepotrzebny;unnoticed:niezauważony;unpleasant:nieprzyjemny;
unprotected:niechroniony;unravel:rozwikłać;unreliable:niezawodny;unroll:rozwijać;
unruly:nieposłuszny;unsafe:niebezpieczny;unscathed:nietknięty;unseasoned:młody;
unseen:niewidoczny;unselfish:bezinteresowny;unsettled:niepewny;unshakable:niewzruszony;
unskilled:niewykwalifikowany;unspoken:niewypowiedziany;unstable:niestabilny;unsteady:chwiejny;
unsuccessful:nieudany;untie:rozwiązać;until:do;unto:do;untold:niewypowiedziany;
untouched:nieknięty;untrue:nieprawdziwy;unusual:niezwykły;unveil:odsłonić;
unwanted:niechciany;unwary:nieostrożny;unwelcome:niemile widziany;unwise:niemądry;
unworthy:niegodny;unyielding:nieugięty;upbringing:wychowanie;upcoming:nadchodzący;
update:aktualizować;upgrade:ulepszyć;upheaval:wstrząs;uphold:podtrzymywać;
upland:wyżyna;uplift:podnosić;upper:górny;upright:pionowy;uproar:wrzawa;
uproot:wyrywać;upset:zmartwiony;upside:górna strona;upstairs:na górze;
upward:w górę;urchin:ulicznik;urge:popęd;urgent:pilny;urn:urna;usable:użyteczny;
usage:użycie;useful:przydatny;useless:bezużyteczny;usher:wprowadzać;usual:zwykły;
usually:zwykle;usurp:uzurpować;utensil:przybór;utility:użyteczność;utilize:wykorzystać;
utmost:największy;utter:wypowiadać;utterance:wypowiedź;utterly:całkowicie;
vacant:pusty;vacate:opróżnić;vaccine:szczepionka;vacuum:próżnia;vagabond:włóczęga;
vague:niejasny;vain:próżny;vale:dolina;valiant:dzielny;valid:ważny;valley:dolina;
valor:męstwo;valuable:cenny;value:wartość;vanish:znikać;vanity:próżność;
vanquish:pokonać;vapor:para;variable:zmienny;variety:różnorodność;various:różny;
varnish:lakier;vary:różnić się;vase:wazon;vassal:wasal;vast:rozległy;vat:kadź;
vault:skarbiec;veer:skręcać;vegetable:warzywo;vegetation:roślinność;vehement:gwałtowny;
vehicle:pojazd;veil:welon;vein:żyła;velocity:prędkość;velvet:aksamit;veneer:fornir;
venerable:czcigodny;vengeance:zemsta;venom:jad;vent:otwór;ventilate:wietrzyć;
venture:przedsięwzięcie;verdict:werdykt;verge:krawędź;verify:zweryfikować;
vermin:szkodniki;verse:wiersz;version:wersja;versus:przeciwko;vertical:pionowy;
vessel:statek;vest:kamizelka;vestige:ślad;veteran:weteran;vex:drażnić;
vial:fiolka;vibrant:żywy;vibrate:wibrować;vice:nałóg;vicinity:pobliże;
vicious:zawzięty;victim:ofiara;victor:zwycięzca;victory:zwycięstwo;vie:rywalizować;
view:widok;vigil:czuwanie;vigorous:energiczny;vile:podły;village:wioska;
villain:łotr;vine:winorośl;vinegar:ocet;vineyard:winnica;violate:naruszać;
violence:przemoc;violent:gwałtowny;violet:fiołkowy;violin:skrzypce;virtue:cnota;
viscous:lepki;visible:widoczny;vision:wizja;visitor:gość;visual:wizualny;
vital:istotny;vivid:żywy;vocabulary:słownictwo;voice:głos;void:pustka;
volatile:lotny;volcano:wulkan;volley:salwa;volume:tom;voluntary:dobrowolny;
volunteer:ochotnik;vomit:wymiotować;voracious:żarłoczny;vote:głosowanie;
vouch:ręczyć;vow:przysięga;voyage:podroz morska;vulgar:wulgarny;
wade:broczyć;wafer:wafel;wage:pensja;wager:zakład;wail:lament;waist:talia;
waistcoat:kamizelka;wake:budzić;walken:budzik;wander:wędrować;wanderer:wędrowiec;
wane:zanikać;ward:okręg;warden:strażnik;wardrobe:garderoba;warehouse:magazyn;
warfare:działania wojenne;warily:ostrożnie;warlike:wojowniczy;warp:wypaczenie;
warrant:nakaz;warrior:wojownik;wary:ostrożny;wash:myć;wasp:osa;waste:marnować;
watchdog:pies stróżujący;waterfall:wodospad;wave:fala;waver:chwiać się;wavy:falisty;
wax:wosk;wealthy:bogaty;weaponry:uzbrojenie;weary:zmęczony;weave:tkac;web:sieć;
wedge:klin;weed:chwast;weekend:weekend;weep:płakać;weigh:ważyć;weird:dziwny;
welcome:witać;weld:spawać;welfare:dobro;well:także;wells:studnie;welter:zamęt;
wend:kierować się;werewolf:wilkołak;westward:na zachód;wet:mokry;whale:wieloryb;
wharf:nabrzeże;wheat:pszenica;wheel:koło;whelp:szczenię;whereabouts:miejsce pobytu;
whereas:podczas gdy;whereby:w ten sposób;wherein:w którym;wherever:gdziekolwiek;
whet:zaostrzyć;whiff:powiew;whim:kaprys;whimper:skomleć;whine:jęczeć;whip:bicz;
whirl:wir;whisper:szept;whistle:gwizdek;wholesale:hurtowy;wholly:całkowicie;
wicked:nikczemny;wicker:wiklinowy;wide:szeroki;widen:poszerzać;widespread:powszechny;
widow:wdowa;width:szerokość;wield:dzierżyć;wilderness:dzicz;wiles:podstępy;
willow:wierzba;wilt:więdnąć;wily:przebiegły;win:wygrać;wince:skrzywić się;
windy:wietrzny;wink:mrugnięcie;winnow:przesiewać;wipe:wycierać;wire:drut;
wiry:żylasty;wise:mądry;wisp:smuga;withdraw:wycofać;wither:więdnąć;
withhold:wstrzymywać;withstand:wytrzymać;witness:świadek;witty:dowcipny;
wizard:czarodziej;wobble:chwiać się;woe:biada;woeful:żałośny;wonder:cud;
wondrous:cudowny;wont:zwyczaj;wooden:drewniany;wool:wełna;workshop:warsztat;
worldly:światowy;worship:czcić;worth:warty;worthy:godny;wrangle:kłócić się;
wrap:owijać;wrath:gniew;wreak:wywołać;wreath:więniec;wreck:wrak;wrench:klucz;
wrest:wyrwać;wrestle:mocować się;wretch:nędznik;wretched:nędzny;wring:wyżymać;
wrinkle:zmarszczka;wrist:nadgarstek;writ:rozkaz;writhe:wić się;wrong:zły;
wrote:napisał;wrought:wykonany;wry:krzywy;
yank:szarpać;yard:podwórze;yarn:przędza;yawn:ziewać;yearly:roczny;yearn:tęsknić;
yeast:drożdże;yell:krzyk;yellow:żółty;yelp:skomleć;yield:ustąpić;yoke:jarzmo;
yonder:tamten;youngster:młodzik;
zeal:zapał;zealous:gorliwy;zenith:zenit;zephyr:zefir;zinc:cynk;
zigzag:zygzak;zombie:zombie;zone:strefa;zoom:przybliżenie;
"""
# Parse the compact data format
for line in DATA.strip().split('\n'):
    line = line.strip()
    if not line:
        continue
    for pair in line.rstrip(';').split(';'):
        pair = pair.strip()
        if ':' not in pair:
            continue
        parts = pair.split(':', 1)
        if len(parts) == 2:
            T[parts[0].strip()] = parts[1].strip()

print(f"Dictionary built with {len(T)} entries")

# Find all bracketed entries and replace
bracket_pattern = re.compile(r'(en: ")(.*?)(", pl: )"\[(.*?)\]"')

count = 0
def replace_match(m):
    global count
    en_word = m.group(2)
    if en_word in T:
        count += 1
        return f'{m.group(1)}{en_word}{m.group(3)}"{T[en_word]}"'
    return m.group(0)

new_content = bracket_pattern.sub(replace_match, content)

print(f"Applied {count} translations")

with open("C:/Users/R6X/opencode/klepanka/js/decks/baldursgate.js", "w", encoding="utf-8") as f:
    f.write(new_content)

# Count remaining
remaining = len(re.findall(r'"\[.*?\]"', new_content))
total = len(re.findall(r'en: "', new_content))
print(f"\n=== FINAL STATS ===")
print(f"Total entries: {total}")
print(f"Translated: {total - remaining}")
print(f"Remaining untranslated: {remaining}")
print(f"Translation rate: {((total-remaining)/total)*100:.1f}%")
